### ISSUE TITLE
renv and ACL's when using ACL'ed cache 

### ISSUE THREAD

**Issue by michaelmayer2** [rstudio/renv#1025]
`renv` is doing a great job of retaining ACL's for all file/directory copy and move operations. 

In a situation however where there exists an ACL both on the project folder but also in the global renv cache, any package copied to the cache will inherit the ACL from the project folder but not adopt the one from the cache. 

This then creates issues when different users install the same package. `renv` will then create backup files of previous package installations and reinstall and re-add to the cache again. 

It is not clear what the rationale is to have `renv` being so restrictive with ACL's.

**Comment by kevinushey** [comment]
`renv` can either 'copy' or 'link' packages into / from the cache, depending on whether it's safe for the current library paths to hold symlinks. (We choose not to use symlinks if someone's using `renv` without a project library.)

https://github.com/rstudio/renv/blob/main/R/cache.R#L183-L188

See also:

https://github.com/rstudio/renv/blob/main/R/files.R#L191-L198

Presumedly, `mv` here is also preserving ACLs, so a complete fix here would need to avoid using `mv` if we need to worry about ACLs.

**Comment by kevinushey** [comment]
I'm going to take a closer look at this today.

**Comment by kevinushey** [comment]
I've now made some changes in `renv` in the same line as your PR. In particular, we no longer try to move packages into the cache via `mv`; instead, we always attempt to copy packages (via `cp -R`) so that ACLs are not preserved after copy. Hopefully this is enough to address the customer's concern!

**Comment by kevinushey** [comment]
I've spent some time looking further into this, and I think there's two issues...

1. Packages can be moved into a cache either via `mv` or `cp`. This implies that ACLs (or, in general, permissions) will be preserved when that package is placed into the cache.

2. Even if a package is copied or moved into a directory via `cp` or `mv`, the default ACLs on the cache itself is ignored.

To wit, `renv` now tries to solve this by copying the ACLs set on the cache directory via:

```
getfacl <cache> | setfacl -R --set-file=- <package>
```

Essentially, we try to forcefully reapply the ACLs from the parent directory recursively after the package has been copied into the cache.

This is going to require some testing + feedback to confirm I've got everything right, but hopefully this is the right direction.

**Comment by kevinushey** [comment]
> Happy to help/do any testing as needed.

Are you working with any customers who are bumping into this sort of issue? 
It might be helpful if we could ask them to trial an install of the development version of `renv` to test.

Or, could we set up a local environment with a similar configuration? (I think the way we could mirror this locally would be to work within an `renv` project whose default ACLs disallow any sort of access from group or other, and confirm those ACLs are reset or removed after a package is installed and moved into the cache.)

One thing I'm not certain of: will the user installing packages + copying packages in the cache still have the permissions necessary to change the ACLs on these files / folders? I'm guessing it's okay since the folder should be owned by that user, but I'm not an expert in this space.

**Comment by michaelmayer2** [comment]
I am working with one customer that is struggling with this ACL problem but also have a test environment set up where I easily can test.

In this test environment 
* I am using `renv` for a simple R code that contains nothing but `library(SuppDists)`. 
* set up `renv` as specified in https://github.com/sol-eng/singularity-rstudio#renv-package-cache and using a very open ACL specified there as well. 

When initializing the simple R code with the latest `renv` from CRAN I get 

```
getfacl /scratch/renv/v5/linux-ubuntu-focal/R-4.2/x86_64-pc-linux-gnu/SuppDists/1.1-9.7/82fc819203a2818bd5c10f758991b492/SuppDists/
getfacl: Removing leading '/' from absolute path names
# file: scratch/renv/v5/linux-ubuntu-focal/R-4.2/x86_64-pc-linux-gnu/SuppDists/1.1-9.7/82fc819203a2818bd5c10f758991b492/SuppDists/
# owner: ubuntu
# group: ubuntu
user::rwx
group::rwx
other::r-x
```


while with the latest from `rstudio/renv@main` I get 

```
getfacl /scratch/renv/v5/linux-ubuntu-focal/R-4.2/x86_64-pc-linux-gnu/SuppDists/1.1-9.7/82fc819203a2818bd5c10f758991b492/
getfacl: Removing leading '/' from absolute path names
# file: scratch/renv/v5/linux-ubuntu-focal/R-4.2/x86_64-pc-linux-gnu/SuppDists/1.1-9.7/82fc819203a2818bd5c10f758991b492/
# owner: ubuntu
# group: ubuntu
user::rwx
group::rwx
mask::rwx
other::rwx
default:user::rwx
default:group::rwx
default:mask::rwx
default:other::rwx
```


As you can see: With your latest version from github the ACL is fully replicated while with the current version from CRAN it is not so everything works as expected.

**Comment by michaelmayer2** [comment]
The other customer I am aware of has a completely different usage of `renv` - they configure `renv` in such a way that only an admin can install packages into the `renv` cache and the users as a consequence are limited by further configuration to only use the packages in the `renv` cache.
