### ISSUE TITLE
Different dependencies per OS

### ISSUE THREAD

**Issue by mrkaye97** [rstudio/renv#1030]
Hey Kevin!

Potentially pretty niche question / request: Our process is set up such that we each develop on MacOS, but then deploy to production with Docker (`rocker` images). In one case, we want to use `rocker/cuda` to train XGBoost on a GPU. However, this is non-trivial since the GPU-compatible versions of XGBoost aren't able to be on CRAN -- see [this issue](https://github.com/dmlc/xgboost/issues/6654).

But then there's another caveat: our local machines don't have GPUs, so we don't need to use the pre-built binary on local. But even then, there would be a problem: The binaries are OS-specific, so we'd need to have one for MacOS (local) and one for Linux (production) if we wanted to correctly set up the lockfile such that it points to a local source. AFAICT, that won't work.

So on to the question: Is there any reasonable way to get this to play nicely with `renv`? The best I could come up with was to snapshot the correct _version_ of XGBoost and then when `restore`ing the `renv` cache, just completely removing the CRAN version of XGBoost after the restore finishes and replacing it with a version we install with `R CMD INSTALL`. It's super hacky, but it seems to work.

Let me know if you've got any ideas about a better way to manage this multi-OS, multi-source issue! Thanks a bunch :)

**Comment by kevinushey** [comment]
You might be able to take advantage of the `renv.records` override option here. Basically, this option is used to override certain records from the lockfile during restore -- for example:

```
options(renv.records = list(
  XGBoost = list(
    Package = "XGBoost",
    # other fields matching the desired remote location, as you might place in renv.lock
  )
)    
```

You could set this option in your CI pipeline, so that `renv::restore()` in CI would instead use that version of XGBoost.

Another avenue would be to make use of `renv` profiles, as described here:

https://rstudio.github.io/renv/articles/profiles.html

In effect, you'd have a separate profile for CI deployments, and you'd set those up to use a separate lockfile (with the GPU-accelerated version of XGBoost) to be installed there.

Let me know if any of these seem like tenable ways forward.

**Comment by mrkaye97** [comment]
Ah thanks, `renv` profiles sounds almost exactly like what I want! I'll give it a shot and report back 🎉

**Comment by mrkaye97** [comment]
looks great @kevinushey! thanks for the help. closing this
