### ISSUE TITLE
Explicit sources: Ensure that only explicit source is used

### ISSUE THREAD

**Issue by Klesel** [rstudio/renv#1079]
I use a package that is not on CRAN and use the explicit definition in the lock file as suggested here: [https://rstudio.github.io/renv/articles/cellar.html#explicit-sources](https://rstudio.github.io/renv/articles/cellar.html#explicit-sources).

The lock file looks like that:
```   
"relaimpo": { 
      "Package": "relaimpo",
      "Version": "2.2-5",
      "Source": "relaimpo_2.2-5.zip"
    }
```

It is important that the offline .zip file is used because this package has multiple versions (i.e., for US users and for non-US users).

Expected behavior: I would expect that the explict definition ensures that renv is exclusively refering to the source given and **does not** query other repositories.

Current behavior: Currently, MRAN is used to download a different package (i.e., the US version which I do not want to use) instead using the offline package.

**Comment by kevinushey** [comment]
Thanks for the bug report. The relevant code is here:

https://github.com/rstudio/renv/blob/b27db509dfb3740861bd8d7e4d8d06f4ca998eb4/R/retrieve.R#L158-L163

In particular, I think the issue is that `renv` is failing to detect this case because there's no slash in your source URI. A workaround might be something like:

```
"relaimpo": { 
      "Package": "relaimpo",
      "Version": "2.2-5",
      "Source": "./relaimpo_2.2-5.zip"
    }
```

We could also probably improve the heuristics for detecting package URIs provided in the `Source` field.
