### ISSUE TITLE
question re: using multiple caches

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1094]
I'm trying to use multiple caches on windows.  The documentation here https://rstudio.github.io/renv/articles/renv.html#multiple-caches  doesn't mention the semi-colon option for setting the RENV_PATHS_CACHE value. 

But more importantly,  I can successfully change the file/folder permissions  Sys.chmod(list.dirs(), "555")),  but then when I install a new package, it still copies to the cache location that I want to be turned off (global one) so that it resorts to the secondary one (project specific).   So in effect it only ever uses the first cache location and always ignores any others.  What am I doing wrong here ?

_Originally posted by @shug0131 in https://github.com/rstudio/renv/issues/653#issuecomment-1277376719_

**Comment by kevinushey** [comment]
> But more importantly, I can successfully change the file/folder permissions Sys.chmod(list.dirs(), "555")), but then when I install a new package, it still copies to the cache location that I want to be turned off (global one) so that it resorts to the secondary one (project specific). So in effect it only ever uses the first cache location and always ignores any others. What am I doing wrong here ?

What order do you have your caches in? Presumedly, if the "local" cache is first and the "global" cache is second, then `renv` should always prefer writing to the first cache (the local one) but use both when attempting to `restore()`.

**Comment by shug0131** [comment]
Yes the one that is first, is always the one that gets used, as far as I've experienced; adding a second cache path has no effect.  So if you have to change the order of the caches, to get it to change which is used, then what is the point of multiple caches? I hope I'm misunderstanding something here.  Maybe I need to use Access Control Lists in windows, rather than file permissions, or is there some other way to run a centralised Global Cache + local project cache.  A worked example of multiple caches would be very helpful.
