### ISSUE TITLE
{renv} checks dependencies when opening a project (0.17.2)

### ISSUE THREAD

**Issue by eastclintw00d** [rstudio/renv#1181]
I am not sure if this is intended behaviour. 

I just upgraded from {renv} 0.16.0. After upgrading opening a project and similarily restarting R session takes a long time and I get the result of dependency checks printed out.

Because this is a larger project and I tend to restart the session everytime I work on another script this is a problem for me.

```
Restarting R session...

* Project '<my-project>' loaded. [renv 0.17.2]

WARNING: One or more problems were discovered while enumerating dependencies.

<path/to/file1.R>
-------------------------------------------------

ERROR 1: invalid multibyte character in parser at line 32

<path/to/file2.R>
-------------------------------------------------

ERROR 1: invalid multibyte character in parser at line 835

Please see `?renv::dependencies` for more information.
```

The displayed errors will cause no problems as they are in older scripts that are no longer in use. I would like to avoid dependency checks on start-up anyway.

**Comment by kevinushey** [comment]
You can disable the startup check with:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

in your project's `.Renviron` file.

Alternatively, use a `.renvignore` to tell `renv` which files to parse for dependencies. See https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files for more details.

Otherwise, if you could share a reproducible example (e.g. the contents of the file giving the parse error) that would be helpful.

**Comment by eastclintw00d** [comment]
Don't get me wrong. A synchronized-check is still desired. I mean I want to make sure that the packages installed match the packages listed in the `renv.lock` file. What I don't understand is why the dependency check is triggered on session restart. That was not the case in versions prior to 0.17.0 I think. At least I did not get any console messages and a session restart took considerably less time.

I DID get those console messages when executing a `renv::snapshot()` which is OK because then `renv::snapshot()` should scan my scripts for packages I use. This is not necessary on session restart as all packages that should be installed are listed in `renv.lock`.

**Comment by kevinushey** [comment]
Thanks for clarifying -- I've made a change on the main branch; those dependency errors should no longer print when checking if the project is synchronized on startup.

**Comment by eastclintw00d** [comment]
That works well! Thanks for the quick responses!

**Comment by kevinushey** [comment]
Are you able to use a `.renvignore` file to ignore larger directories of files which don't contain any R source files? Or, switch to using explicit snapshots? https://rstudio.github.io/renv/reference/snapshot.html#snapshot-type

**Comment by eastclintw00d** [comment]
Yes, I suppose I can use the `.renvignore` file. I will look into this.

I posted this issue because I was under the impression that the dependency check is maybe triggered unintendedly. I will close this for now.

**Comment by kevinushey** [comment]
Just to clarify; on startup, `renv` calls `renv::status()` to check the project state. Doing this thoroughly requires knowing what the project's package dependencies are, so it can report things like:

- Packages which are used, but not installed;
- Packaged which are used, but not recorded in the lockfile;

We could, in theory, skip that step, and only check whether the project library is in sync with the lockfile -- that is, all the packages declared in the lockfile are installed. This would be a lighter-weight and quicker solution for cases like yours where dependency discovery takes a long time, but could potentially be confusing since `renv::status()` might report the project is out-of-sync even though the startup check didn't.

Do you have any strong opinions either way?

**Comment by eastclintw00d** [comment]
In my specific use case it would be sufficient to only check if the installed packages match those recorded in the lock file. I can imagine cases where the current procedure makes sense. So no strong opinion from my side.

I only wonder if this procedure has been changed when stepping up from 0.16.0 because it hasn't caused any trouble before the upgrade.

**Comment by michalovadek** [comment]
umm, I would maybe revisit the startup check here. I couldn't figure out why one of my projects took forever to load - turns out it had to do with how renv read the .gitignore file. renv checked all my data files (10 000s) everytime I loaded the R project, until .gitignore included /data/* (rather than /data/). I only figured this out when I tried running `renv::snapshot()` manually, which comes with the warning about how many files need to be scanned. But there is no such warning at startup

**Comment by kevinushey** [comment]
@michalovadek could you please file a new issue?

**Comment by eastclintw00d** [comment]
Can it be that - starting from 0.17.x on - you scan a wider range of files types? When I now upgraded to 1.0.0. `renv::status()` tells me that it has to scan more than 8000 files. While I might have well above 100 R scipts in the project it was sufficient to ignore some older ones with 0.16 or lower to get to acceptable start-up times.

I now copied over the contents of my .gitignore file to the .renvignore and I am back to good start-up times, again.

I was somehow under the impression that `renv` was only scanning R scripts and some other specific file types, maybe. My project also contains a large number of excel workbooks and pictures and so on. Do they get scanned, as well?

**Comment by kevinushey** [comment]
renv will try to enumerate all of the files within your project (excepting those ignored via a `.gitignore` rule), and then for `.R` files (or, multimode R files like `.Rmd`), `renv` will try to scan those files for dependencies.

I don't think there have been any substantial changes here, beyond `renv` now trying to better notify the user when it has discovered a large number of files.
