### ISSUE TITLE
Suggestion: An alternate workflow for reproducible environments

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#121]
Hey, over the last few months my work team has been trying to use `renv` and competing packages to make our DS pipelines easily reproducible and deployable in the cloud. We haven't really been able to create a jank-free experience that I had hoped for which is essentially:

* Git clone the project
* Run a command to build the project environment (download dependencies)
* Run the project

## Issues with `renv` workflow

We have faced two major challenges:
1. Depending on internal packages stored in Azure dev ops repositories.
2. Trying to stop our 'dev dependencies' from polluting the project environment.

With respect to 1, some work was done on `renv` to support that and I think the problems we have now might be particular to our cyber-security setup here at work. 😢

With respect to 2, The issue comes because while we can specify certain packages in `ignored.packages`, their dependencies are not ignored and thus the environment is polluted. Example dev dependencies are `styler`, `lintr`, `rlanguageserver` and many other tools that people use on an individual basis to make their R dev experience more comfortable.

There's a related problem in that often in development of a pipeline, you *trial* the use of a package, before later deciding not to use it. Those can pollute the environment in certain `renv` workflows if people are not vigilant.

## Proposed alternative

What we have come to realise is that while we have a need to create these dependency environments, we do not actually need to run our code within them *reproducibly* **and** *interactively*.

This is partly because our workflow uses `drake` heavily to orchestrate our pipelines. So while we build our functions interactively, we run the pipeline in a non-interactive mode - actually in another R session - using `drake::r_make()`. This is kind of similar to running projects in RStudio's job mode.

So we almost never need to 'switch' our interactive-mode package library to be the project-local one. To use the project-local library,  we can just use a simple wrapper for `r_make` e.g. `r_make_with_library()` or some such. Jobs users could have something similar.

It would be great if we could leverage some of the tools in `renv` to define/build/restore the project-local library without attaching the machinery that assumes we always want to use it for interactive use - that being the `.Rprofile` and associated `renv` bootstrapping.

This approach conveniently sidesteps all possible issues related to challenge 2. Our interactive environment is our 'dev' environment and contain anything, while our project-local environment is our 'prod' and contains only the packages on which the pipeline depends.

## Possible drawbacks

This kind of workflow requires the user to remain aware of the fact that their dev environnent could potentially generate different results to the prod one. So they'll want to be running their pipeline frequently in prod mode with the local library. The great thing about working with `drake` is this is fairly painless, and you're guaranteed to catch an issue introduced by code that works in one but not the other pretty much immediately.

The user would also presumably need some kind of way to switch into a prod environment for debugging these kinds of issues - knowingly sacrificing some of their dev creature comforts while doing so.

They'll also probably want some functions to diff the versions of packages in dev and prod libraries so they can make informed decisions about upgrading.

## Summary

This is a proposal for `renv` to support an alternative reproducible environment workflow that does not assume all work takes place inside the project-local library. Removing this assumption allows users to freely use dev environments packed with dependencies that make interactive development convenient, whilst keeping a well defined prod environment they can run their project in.

**Comment by kevinushey** [comment]
Thank you for taking the time to write up your experience with `renv`! I appreciate it. This is an issue we've struggled with for a while.

> With respect to 1, some work was done on renv to support that and I think the problems we have now might be particular to our cyber-security setup here at work. 😢

Let me know if you're able to confirm that one way or another -- if there's something I can do in `renv` to help I'd be glad to try.

> With respect to 2, The issue comes because while we can specify certain packages in ignored.packages, their dependencies are not ignored and thus the environment is polluted. Example dev dependencies are styler, lintr, rlanguageserver and many other tools that people use on an individual basis to make their R dev experience more comfortable.

We've struggled with this issue internally as well. The current solution (just include everything in the private library) is at least 'correct' insofar that the project always contains the packages you need, but does result in 'cruft' in some deployment situations. (In theory, the `renv` cache fixes this issue, since your development dependencies will just be re-used from the cache, but I can understand if this isn't satisfactory -- especially if you have your own deployment workflow.)

Note that right now, since we don't crawl the project for used packages during snapshot, we cannot tell whether a package is used as a 'dev dependency' or is a real requirement for the project. The assumption instead is that if it's installed in the project library, then you need it, and it should enter the lockfile.

> It would be great if we could leverage some of the tools in renv to define/build/restore the project-local library without attaching the machinery that assumes we always want to use it for interactive use - that being the .Rprofile and associated renv bootstrapping.

Can you elaborate a bit more? In theory, you could just remove the `renv` autoloader (or we could add a configuration option to disable it) but you should be able to use `renv`'s machinery standalone, without explicitly activating a project. (You may need to explicitly specify the project and library when required, though.)

---

The other thing we could do is implement a Packrat-style snapshot mode, where the things that enter the lockfile are the intersection of:

1. Packages installed in your library, and
2. Packages used in your project (as discovered by `renv::dependencies()`)

This solution scares me a bit since we try to call `renv::snapshot()` fairly eagerly, especially when automatic snapshots are enabled, but we have no clue how large the projects people might be using are. (The issue again can be mitigated through the use of `.renvignore` files + user education, but I still worry) Still, perhaps this is worth exploring.

**Comment by kevinushey** [comment]
I've now implemented Packrat-style snapshotting in `renv`, where only the packages installed in the library that are actually in use within the project will enter the lockfile. If you have the time, please try `renv::upgrade()`-ing and let me know if things look better in the lockfile.

**Comment by MilesMcBain** [comment]
Thanks for your respnses @kevinushey.

### Expanding on "support" for the workflow:

A slightly more detailed sketch of what I was thinking `renv` could implement:

(1)
It would be nice to be able to create the project-local library without having to switch to it, e.g. something like:

```r
use_renv() ## I create the folder and .gitignore 

with_renv({
  install.packages( 
  c("tidyverse", 
     "drake")
  ) ## In here I'm an renv shim
  install_github("milesmcbain/slippymath") ## and I'm an renv shim too
}) ## I execute stuff within context of the renv.
```

(2) 
Don't need .Rprofile so not created in this mode?

(3) 
Some kind of wrapper facilitator.
```
renv_fn <- function(fn) {
  function(...) with_renv(fn(...))
}
r_make_renv <- renv_fn(drake::r_make)

r_make_renv() ## Now I make the pipeline in a well-defined project-local environment.

render_renv <- with_renv(rmarkdown::render)

render_renv("foo.Rmd") ## Now I render it inside the renv
```

(4) 
To rebuild from the lockfile created by the shims I should just be able to use restore()? That won't try to switch me into the project local env right?

(5)
A way to switch to the renv for debugging, possibly:
```
debug_renv() ## Now your interactive-mode library is the renv() - needs restart?
undebug_renv() ## Now you're back to your regular R library
```
(6?)
You could still have snapshot() in this workflow although it's possibly not required if shims exist for removing packages.

### Re snapshot changes

This seems like it could prevent the dev deps making it into the lockfile which is nice. They still have to be installed into the renv local library after restore to be used right? So they could affect versions of dependencies installed - upping the version of those unnecessarily?

I'll try out the new changes.

**Comment by cderv** [comment]
This is a really interesting workflow. I allow myself to schime in to share views 😉 

# About switching library
I tend to use sometimes something close while developping packages to switch between a dev library and my user library. Kind of the opposite use case in fact :) 

Basically, the switching part was done using `devtools::dev_mode()` in no use of packrat, or `packrat::packrat_mode()` if developping using packrat. I use that before doing some stuff that implies dev packages or before installing a dev version so that my user library is not impacted. 

Finally, I have done wrapper that would use one of this command before executing some code. 

Maybe a similar `renv_mode()` could be useful to easily switch between project lib or not.

For this need, I stumble upon another interesting implementation: [switchr](https://github.com/gmbecker/switchr) but stayed at the end with `dev_mode()` for dev lib and `packrat::on()` / packrat::off()' for project lib.

# About packrat snapshot  for undesired package

Again comparing packrat I use a lot, I sometimes use `ignored.packages` options to tell packat to not track some packaging - often some dev / helpers packages that I are not really dependent of my code.

Also, I find the packrat  `ignored.directories` useful for some script I have where I use dev package and I don't want packrat to track the packages I use in those script because I know I won't deploy to production those script and I don't want them in the lock file. 

Those options where useful in packrat and I don't think they have been reporting in renv config system.

@MilesMcBain I would be interested to know if you used packrat before renv with the workflow you describe ? 

I find that renv could still miss some feature of packrat that would help for a workflow like that.
@kevinushey  do you plan to not move to renv those packrat features?

**Comment by kevinushey** [comment]
> (1) It would be nice to be able to create the project-local library without having to switch to it <...>

This is challenging, but maybe not undoable. The main hiccup here is that `renv` does a lot of state management that can be difficult to undo without restarting the whole session.

> (4) To rebuild from the lockfile created by the shims I should just be able to use restore()? That won't try to switch me into the project local env right?

That's right; you can use all of the `renv` APIs without explicitly activating a project -- you just need to explicitly specify the project path when you do so.

> (5) A way to switch to the renv for debugging, possibly <...>

I think this is effectively the same as (1), and the challenge comes in properly managing state when activating and deactivating `renv` in a single session. (The safest thing is still to just restart the R session whenever you need to switch)

> This seems like it could prevent the dev deps making it into the lockfile which is nice. They still have to be installed into the renv local library after restore to be used right? So they could affect versions of dependencies installed - upping the version of those unnecessarily?

I don't follow on the "versions of dependencies installed" concern -- can you elaborate? But right, they would need to be installed in the project library. Or, in theory, you could use the project setting `external.libraries`, install all your development dependencies in there, and load from there.

Note that you could run into problems with this approach, since your project and your external library might contain different versions of the same package (e.g. imagine you had an old project requiring `rlang 0.3.1`, but your dev. dependencies used `rlang 0.4.0`).

**Comment by kevinushey** [comment]
> Again comparing packrat I use a lot, I sometimes use ignored.packages options to tell packat to not track some packaging - often some dev / helpers packages that I are not really dependent of my code.

`renv` has the same concept of `ignored.packages` in a project -- see `settings$ignored.packages()`.

> Also, I find the packrat ignored.directories useful for some script I have where I use dev package and I don't want packrat to track the packages I use in those script because I know I won't deploy to production those script and I don't want them in the lock file.

`renv` has something much more powerful here -- we use `.renvignore` files (like `.gitignore`) to instruct `renv` to ignore certain files and directories. And, in fact, we respect `.gitignore` by default, under the assumption that if you don't want `git` to see something then you probably don't want `renv` to see it either. See the documentation in `?renv::dependencies` for more details.

**Comment by kevinushey** [comment]
IMHO the safest and most straightforward solution still seems like "always use the project library" so I'd be curious to know:

1. What problems are being solved by switching back and forth between user + project library?

2. What, if anything, prevents us from solving those when just using the project library?

**Comment by MilesMcBain** [comment]
The main problem I've been concerned with is development dependencies. 

I work in a pretty diverse team so if we put all the dev deps into the project library it could conceivably contain things related to R dev with  RStudio, VSCode, and Emacs. So there'd be a lot of non-prod related stuff.

@kevinushey you got to the point that I was trying to make being that: whilst you can try to be clever about excluding unused packages, you will very likely have cases where the installation of development dependencies changes versions in of true dependencies in the project-local environment from their snapshotted state. That could be a source of confusion.

From my perspective the problem being solved by switching is just that of interactively debugging within a project-local dependency environment. Since in my proposed workflow you do not normally execute code in your project-local dependency environment interactively. 

@cderv I wasn't aware of `packrat_mode` or `on/off`, this is nice. I could use this in `renv` to implement parts of my workflow for sure.

**Comment by kevinushey** [comment]
FWIW, you can use `renv::deactivate()` to disable the automatic loading of the project library, and `renv::activate()` to re-activate it. So I think one mode here could be to just "deactivate" when you want to use your global library, and re-activate when you need to run something for production.

Another thing we could consider is a way to switch between different libraries in a project. Something like:

```
renv::settings$devmode(TRUE)
```

to activate 'development mode', and effectively just switch to a different (dev) project library. Or something more general like:

```
renv::settings$project.library("dev")
```

to activate an arbitrarily-named R library in a project.

In theory, you could also homebrew this by writing a function that changes `RENV_PATHS_LIBRARY` and writes that to a project `.Renviron`, so that the library chosen when R is launched differs based on that value.

**Comment by kevinushey** [comment]
@MilesMcBain: do you think `renv::activate()` and `renv::deactivate()` are sufficient for what you want, or would it be worth implementing the notion of multiple project libraries that can be activated / changed?

**Comment by MilesMcBain** [comment]
I'm about to try to package up some work to be shared this week, I'll let you know how this approach goes in a couple of days.

**Comment by MilesMcBain** [comment]
I haven't gotten completely through the workflow. Here are some rough notes from this afternoon: https://gist.github.com/MilesMcBain/519e31e0c68e2fba63e0f16dd763037f

One thing I think would be nice is if the `library` arg looked for an renv library in the working directory or project root and used that as its default.

**Comment by kevinushey** [comment]
Some comments:

1. If you used `renv::init()` without `bare = TRUE`, then packages you had installed from GitHub would automatically be pulled into the project library, skipping the step of manually resolving package dependencies. Although I can understand if you want to be more explicit about what happens at that stage.

2. We could consider an API for retrieving some of the common paths used for a project.

3. The snapshot failed in your case because it took `renv` too long to discovery dependencies in Packrat mode. I need to find a better way to surface that error.

**Comment by kevinushey** [comment]
I've now added a `path` utility object for accessing some common paths used by `renv` -- for example, `renv::paths$library()` gives the path to the project library.

Snapshot now no longer gives a timeout error if it takes too long to run; instead, it prints a warning and suggests switching to 'simple' snapshots or using `.renvignore`.

**Comment by MilesMcBain** [comment]
@kevinushey thanks to your help and some accommodating changes, I've been able to codify this suggestion into a package that is so far meshing really nicely with our `drake` workflow at my work. :+1:

https://github.com/milesmcbain/capsule

**Comment by kevinushey** [comment]
Awesome! I'm glad to hear it.
