### ISSUE TITLE
Doesn't support `download.file.extra`

### ISSUE THREAD

**Issue by kenahoo** [rstudio/renv#128]
(Continued from https://github.com/rstudio/packrat/issues/528)

The `renv::init()` method does not seem to respect parameters in `options(download.file.extra)`:

```
% cat DESCRIPTION 
Package: AppPackage
Title: AppPackage
Version: 1.0
Authors@R: as.person("A. U. Thor <author@a.galaxy.far.far.away> [aut, cre]")
Description: Built for creating Docker image
Depends: MyLocalPackage (== 7.4)

% R
> getOption('download.file.method')
[1] "curl"
> getOption('download.file.extra')
[1] "--netrc"
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Resolving missing dependencies  ... 
* Querying repositories for available source packages ... Done!
Retrieving 'https://nexus.mylocalrepo.com/repository/my-repo/src/contrib/MyLocalPackage_7.4.tar.gz' ...
curl: (22) The requested URL returned error: 401 Unauthorized
curl: (22) The requested URL returned error: 401 Unauthorized
The following package(s) were not installed successfully:

	[LoadFX]: download failed [error code 22]

You may need to manually download and install these packages.

* Lockfile written to '~/git/loadfx/app-renv/renv.lock'.
* renv activated -- please restart the R session.
```

By itself, `download.file()` can successfully download the file, using the credentials that are in `.netrc`:

```
> download.file('https://nexus.mylocalrepo.com/repository/my-repo/src/contrib/MyLocalPackage_7.4.tar.gz', 'dest.tgz')
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3537k  100 3537k    0     0  5356k      0 --:--:-- --:--:-- --:--:-- 5351k
```

**Comment by kenahoo** [comment]
Note what might be a secondary bug - despite the failure, the call to `renv::init()` appears to succeed, and writes a `renv.lock` file that has an empty `Packages` section.

**Comment by kevinushey** [comment]
Thanks! I've just pushed a commit that should fix this so that `download.file.extra` is respected during downloads.

> Note what might be a secondary bug - despite the failure, the call to renv::init() appears to succeed, and writes a renv.lock file that has an empty Packages section.

This is actually intentional: rather than making the whole `init()` fail, I think it's more useful to instead report the failure to install the package to the user, so they can try to figure out what happened and fix the problem post-hoc.

This is especially true since `renv::init()` depends on R dependency discovery within the project's R source files, and in some cases that machinery could fail. In other words, `renv::init()` takes an educated guess on what packages your project needs, but ensures that failure to install some packages is not fatal.

**Comment by kevinushey** [comment]
As an aside -- if you need to upgrade `renv` in an existing project, you can use `renv::upgrade(version = "master")`.

**Comment by kenahoo** [comment]
Thanks, this did indeed allow the package to be downloaded & installed successfully.

**Comment by kevinushey** [comment]
Great! I'm glad to hear it.
