### ISSUE TITLE
Error in eval(quote({ : object '..version..' not found

### ISSUE THREAD

**Issue by schoulten** [rstudio/renv#1546]
I'm experiencing this error locally and in one of my [GH Actions](https://github.com/schoulten/macro_report/actions/runs/5533292982) workflows. I'm not sure if it's due to the latest `renv` update (1.0.0) because I noticed it started happening after this commit ([#11a22a9](https://github.com/r-lib/actions/commit/11a22a908006c25fe054c4ef0ac0436b1de3edbe)).

I tried to create a reproducible example of what's happening in the workflow above. I believe the problem is installing a newer version of `renv` and activating the project without restarting the session (if I restart, the error doesn't occur). However, the [setup-renv](https://github.com/r-lib/actions/tree/v2/setup-renv) action seems to install a new version of renv and activate the project without restarting the session. And so I'm stuck with this error.

Here's the reproducible example:

```
# console
install.packages("remotes")
remotes::install_version("renv", "0.16.0")
```
Create an R file with any code, for example:

```
library(ggplot2)
print(head(ggplot2::economics_long))
```

And then continue with:

```
# console
renv::init()
renv::status()
renv::snapshot() # y
install.packages("remotes")
remotes::install_version("renv", "1.0.0")
renv::activate()
.rs.restartR()
```

After the last command, to restart the session, this error will be displayed:
```
# Error in eval(quote({ : object '..version..' not found
```

I apologize if the issue is not with `renv` but with the action.

**Comment by kevinushey** [comment]
The problem here occurs because you still have an older version of renv loaded, but a newer version of renv is installed. So you end up with renv 0.17.3 trying to write an activate script, but instead of the activate script for renv 0.17.3 being available, the version for 1.0.0 is available instead, and because of a small change that was made this error occurs.

I'll need to think about how to make `renv` more robust in these scenarios, but the simple fix here is to call `renv::activate()` and then restart the R session.

**Comment by kevinushey** [comment]
It's also possible that this recent change in the action will have resolved the issue:

https://github.com/r-lib/actions/commit/11a22a908006c25fe054c4ef0ac0436b1de3edbe

**Comment by sgvignali** [comment]
This happens also with `renv::upgrade()`. In my case form version 0.17.3 in Windows.
The command also raises several warnings:

```r
renv::upgrade()
A new version of the renv package will be installed:

# CRAN ===============================
- renv   [0.17.3 -> 1.0.0]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Installing renv [1.0.0] ...
	OK [linked cache in 1.7 milliseconds]
Warning message:
In eval(handler$expr, handler$envir) : internal error -3 in R_decompress1
warning messages from top-level task callback 'renv_sandbox_task'
Warning messages:
1: In callback() : internal error -3 in R_decompress1
2: renv background task 'renv_sandbox_task' failed; it will be stopped 
warning messages from top-level task callback 'renv_snapshot_task'
Warning messages:
1: In callback() : internal error -3 in R_decompress1
2: renv background task 'renv_snapshot_task' failed; it will be stopped 
```
Then, if  I restart the R session I get the same error:

```
Restarting R session...

Error in eval(quote({ : object '..version..' not found
```

Starting a new session and running `renv::activate()` works, but is there a better workflow to upgrade `renv`?

And is it possible to change the URL in the lock file to use Posit Public package Manager (same as the default for `renv 1.0.0`)?

At the moment `renv::upgrade()` updates the `renv` version in the  `lockfile` but leaves the old URL pointing to https://cloud.r-project.org

**Comment by kevinushey** [comment]
The following seems to work for me:

```
renv::upgrade()
renv::activate()
```

That is, if you ignore the errors you see from `renv::upgrade()`, and then call `renv::activate()` afterwards, the activate script is appropriately updated, so future session launches should work as expected.

The warnings are really unfortunate; it appears they're caused because we try to unload and reload `renv` in the same R session, but R is still holding on to older bits of the R session. I believe this worked with a previous release of R, but appears to no longer be functional. I'll have to figure out why.

I'm deeply sorry for the trouble; this is not how I wanted the upgrade experience to 1.0.0 to pan out. :-/ The good news is that this is a one-time issue; once a project has been updated to 1.0.0 you shouldn't encounter this again.

**Comment by sgvignali** [comment]
No problem, I've just reported for you. I'm totally fine with the double steps approach :) 

For the url, how can I set it to use rspm?

**Comment by kevinushey** [comment]
> For the url, how can I set it to use rspm?

You can either edit the lockfile by hand, or update the repository in the session and call snapshot, e.g.

```
options(repos = c(PPM = "https://packagemanager.posit.co/cran/latest"))
renv::snapshot()
```

Or, you can manually read and edit the lockfile in R, e.g.

```
lockfile <- lockfile_read("renv.lock")
lockfile <- lockfile_modify(repos = c(PPM = "https://packagemanager.posit.co/cran/latest"))
lockfile_write(lockfile, "renv.lock")
```

**Comment by kevinushey** [comment]
As a mitigation, we should automatically re-activate a project (if it's currently activated) after upgrade, or at least instruct the user to do so.
