### ISSUE TITLE
Feature Request: support arbitrary pip install arguments

### ISSUE THREAD

**Issue by jeffkeller-einc** [rstudio/renv#1669]
I have a project where `numpy` needs to be installed from source to avoid issues with R and Python being linked to different versions of (Open)BLAS. To do this, I add `--no-binary=numpy` to the requirements.txt file.

However, `renv::snapshot` overwrites this portion of the requirements file and `renv::restore` does not provide a means of specifying additional arguments to `pip install`.

It would be nice if there was a way to do this, perhaps as a new `pip_args` argument to `renv::restore`.

**Comment by kevinushey** [comment]
`renv` basically just runs `pip freeze` to create a `requirements.txt` file, and `pip install --upgrade -r requirements.txt` to install from the `requirements.txt` file.

IMHO, the better solution here would be to have some way to transform the `requirements.txt` file when `pip freeze` is invoked, so that the necessary flags are added post-hoc. This would ensure the project has a `requirements.txt` file that works regardless of whether you're using it in `renv` or not.

**Comment by kevinushey** [comment]
For internal reference:

```
> Sys.setenv(RENV_PYTHON = "~/.virtualenvs/r-reticulate/bin/python")
> renv:::pip_freeze()
 [1] "appnope==0.1.3"           "asttokens==2.2.1"         "backcall==0.2.0"         
 [4] "comm==0.1.3"              "contourpy==1.0.7"         "cycler==0.11.0"          
 [7] "debugpy==1.6.7"           "decorator==5.1.1"         "executing==1.2.0"        
[10] "fonttools==4.39.4"        "ipykernel==6.23.1"        "ipython==8.14.0"         
[13] "jedi==0.18.2"             "jupyter_client==8.2.0"    "jupyter_core==5.3.0"     
[16] "kiwisolver==1.4.4"        "matplotlib==3.7.1"        "matplotlib-inline==0.1.6"
[19] "nest-asyncio==1.5.6"      "numpy==1.24.3"            "packaging==23.1"         
[22] "pandas==2.0.2"            "parso==0.8.3"             "pexpect==4.8.0"          
[25] "pickleshare==0.7.5"       "Pillow==9.5.0"            "platformdirs==3.5.1"     
[28] "prompt-toolkit==3.0.38"   "psutil==5.9.5"            "ptyprocess==0.7.0"       
[31] "pure-eval==0.2.2"         "Pygments==2.15.1"         "pyparsing==3.0.9"        
[34] "python-dateutil==2.8.2"   "pytz==2023.3"             "pyzmq==25.1.0"           
[37] "scipy==1.10.1"            "six==1.16.0"              "stack-data==0.6.2"       
[40] "tornado==6.3.2"           "traitlets==5.9.0"         "tzdata==2023.3"          
[43] "wcwidth==0.2.6"          
```

**Comment by kevinushey** [comment]
@jeffkeller-einc -- do you have any opinion on what the right way to allow users to hook into how `requirements.txt` is generated here?

**Comment by jeffkeller-einc** [comment]
My understanding is that `pip install -r requirements.txt` is roughly equivalent to `cat requirements.txt | xargs pip`, which means there can be a lot going on in a single valid `requirements.txt` file. For example, it can reference another file as additional requirements or as constraints.

Unfortunately, `pip freeze` does not provide an interface to any of that, and it seems like most people are manually curating their `requirements.txt` files. A more recent standard ([PEP 621](https://peps.python.org/pep-0621/)) appears more comprehensive, but I see no mention of the `--no-binary` flag.

At any rate, I think exposing the complete set of `pip` and `requirements.txt` functionality through `renv` would be a large and complex undertaking.

Perhaps we can leverage the flexibility of `requirements.txt` to our advantage here. Suppose `renv` gets a new project setting option like `renv.python.requirements_extras` which takes a file path to a `requirements_extras.txt` file where the user can specify arbitrary flags. When this option is set, `renv:::pip_freeze` would append the extras file to the main `requirements.txt`.

**`requirements_extras.txt`**
```text
--no-binary=numpy
```

**`requirements.txt`**
```text
...
numpy==1.24.3
...
-r requirements_extras.txt
```

**Comment by kevinushey** [comment]
> My understanding is that pip install -r requirements.txt is roughly equivalent to cat requirements.txt | xargs pip

😱 

The only thing I dislike about that approach is that the `requirements.txt` file is no longer standalone; perhaps we could just copy the contents directly to the generated `requirements.txt` file. The other downside is that it doesn't let you edit existing entries; e.g. if for some reason you wanted to adjust the version or path of a particular package.

I kind of feel we should allow for an R hook / callback function which can be used to generate `requirements.txt` directly. This would give us the maximum amount of flexibility.

**Comment by jeffkeller-einc** [comment]
I agree, though I'm not too bothered by the fact that `requirements.txt` is no longer standalone. I've come across quite a few Python projects that have a `requirements.txt` file with references to other files on the local filesystem or Internet via the `--requirement`, `--constraint`, or `--find-links` flags, so it seems like a fairly common pattern. I'm not a fan of the design of `pip` to begin with, so I'm hesitant to suggest tying `renv` closely to it.

A hook / callback function could work, though it isn't immediately obvious to me how it would be designed to persist these extra flags within the project. Putting them in `renv/settings.dcf` / `renv/settings.json` didn't feel right when I thought about it.

**Comment by kevinushey** [comment]
What about within the `.Rprofile` directly, or within a file `renv/settings.R`? Or a similarly-named startup file?

**Comment by kevinushey** [comment]
> Do you have any specific facilities in mind for modifying pip behavior?

I'm basically thinking of two options:

1. Rather than let `renv` run `pip freeze`, have an R hook provided by the user that runs `pip freeze` in whatever manner it thinks is appropriate;
2. Run `pip freeze`, then input that into a user-defined hook, and take the result of calling that hook.

I think (1) is the best scenario -- I could imagine some people wanting to bypass `pip freeze` altogether and just compute `requirements.txt` in their own way?

**Comment by JavadocMD** [comment]
Not sure if it would be useful to have another use-case to consider or if this would qualify as a separate issue, but here goes --

I'm running into an issue with a colleague on Windows, I'm on Linux. The project is R + Python (a Quarto book). Doing a `renv::snapshot()` on their machine will add "pywin32" and a couple other libraries to the requirements.txt which then causes `renv::restore()` to fail on my side because pywin32 is not a valid package on Linux.

I can currently work around this by modifying requirements.txt so that those lines read: `pywin32==306; sys_platform == "win32"`, for instance, but of course these changes get overwritten the next time `renv::snapshot()` is run.

(Also it's a bit awkward having sys_platform flags: `renv::restore()` always reports there are packages to install -- that is it never says "The Python library is already up to date." -- and then pip will report every time that those packages have been ignored. But that's a minor thing.)

I'm not sure what an ideal solution would look like.

- `pip freeze` allows an `--exclude` flag which might work (as long as we can identify the troublesome packages) if renv could be configured to pass through those options.
  - I tried `renv::snapshot(exclude=...)` but that doesn't seem to extend to python packages?
- Or I could see using a post-snapshot hook which deletes or modifies the offending lines. (I think I might resort to writing a git pre-commit hook anyway for the time being.)

**Comment by kevinushey** [comment]
Now implemented in https://github.com/rstudio/renv/commit/c723b5688de11cf8c3b3c631b165b7417eeceeca -- you can now set hooks like:

```
options(renv.hooks.pip_freeze = function(python) { ... })
```

and take your own action to generate a `requirements.txt` file. Let me know if that seems sufficient; if so, I can document the interface.

**Comment by jeffkeller-einc** [comment]
I'm a bit swamped atm but plan to look at this eventually. If you have any hints for how these hooks might be used, I'd appreciate it :)

**Comment by kevinushey** [comment]
My recommendation would be to put them into one of your R installation's startup R profiles, e.g. `etc/Rprofile.site`. The R documentation in `?Startup` may be helpful.

You could then do something like `system2(python, "-m pip freeze", intern = TRUE)` to generate the `requirements.txt` file, and then modify that with R code as appropriate.

**Comment by jeffkeller-einc** [comment]
Using the new `renv.hooks.pip_freeze` hook, I can modify `requirements.txt` as desired, but I am struggling to get the behavior I want when `renv::restore()` is invoked.

```r
options(renv.hooks.pip_freeze = function(python) {
	
	python <- renv:::renv_path_canonicalize(python)
	args <- c("-m", "pip", "freeze")
	action <- "invoking pip freeze (via renv.hooks.pip_freeze)"
	packages <- renv:::renv_system_exec(python, args, action)
	packages <- c("--no-binary=numpy", packages)
	return(packages)
	
})
```

How I can use any of the hooks to get past the diff performed in `renv_python_virtualenv_restore()`? It always sees `--no-binary=numpy` as having not changed, and so it is never added to the temporary `requirements.txt` file created in `pip_install_requirements()`.

**Comment by kevinushey** [comment]
It should be diffing the current state of your `requirements.txt` file, with whatever is being produced by `pip_freeze()`; doesn't this imply that your Python virtual environment is already in sync with the `requirements.txt` file? Or am I misunderstanding something?

I believe you're referring to this code: https://github.com/rstudio/renv/blob/de3af61f7e1d69f0f8320ec7251a7340e740f233/R/python-virtualenv.R#L118-L124

**Comment by jeffkeller-einc** [comment]
Yes, that is the code I am referring to.

Consider an existing renv project freshly cloned to a new workspace with these files:

`.Rprofile`
```r
options(renv.hooks.pip_freeze = function(python) {
	
	python <- renv:::renv_path_canonicalize(python)
	args <- c("-m", "pip", "freeze")
	action <- "invoking pip freeze (via renv.hooks.pip_freeze)"
	packages <- renv:::renv_system_exec(python, args, action)
	packages <- c("--no-binary=numpy", packages)
	return(packages)
	
})
```

`requirements.txt`
```txt
--no-binary=numpy
numpy==1.26.3
```

When first running `renv::restore()`, only the line `numpy==1.26.3` will be detected as changing because `renv:::pip_freeze` is always injecting `--no-binary=numpy` (via the hook).

**Comment by kevinushey** [comment]
Ah, got it -- and we only supply the diff when invoking `pip_install_requirements`.

https://github.com/rstudio/renv/blob/4e4633ee5c0f1a10662b7f7cb355dc0da674f499/R/python-virtualenv.R#L130

That seems unnecessary to me, since `pip` will be smart enough to check if a requirement is already satisfied?

**Comment by jeffkeller-einc** [comment]
I tried this with [7cdc28b](https://github.com/rstudio/renv/commit/7cdc28ba2593f3bf5651446cef7a1a85597f5145) and it works for the fresh clone scenario I described above.

Though, it doesn't produce the correct behavior during development. If I have a `requirements.txt` file with contents:

```text
numpy==1.26.3
```
And I run `renv::restore()`, then realize I need to create a hook that adds `--no-binary=numpy`, do that as above, run `renv::snapshot()` and then `renv::restore()`, nothing happens because this condition is still looking at `diff`.

https://github.com/rstudio/renv/blob/de3af61f7e1d69f0f8320ec7251a7340e740f233/R/python-virtualenv.R#L121

But my overall concern is that these hooks are not very user accessible (at least to me). I feel like I need intimate knowledge of renv's inner workings and order of operations to use them effectively. I almost just want to be able to inject elements into the `requirements` vector of `renv:::pip_install_requirements()`, but of course, then any modifications wouldn't be persisted in `requirements.txt`.

**Comment by kevinushey** [comment]
> And I run renv::restore(), then realize I need to create a hook that adds --no-binary=numpy, do that as above, run renv::snapshot() and then renv::restore(), nothing happens because this condition is still looking at diff.

In this scenario, I _think_ you would need to run `renv::restore()` after setting your hook, rather than `renv::snapshot()`.

> But my overall concern is that these hooks are not very user accessible (at least to me). I feel like I need intimate knowledge of renv's inner workings and order of operations to use them effectively. I almost just want to be able to inject elements into the requirements vector of renv:::pip_install_requirements(), but of course, then any modifications wouldn't be persisted in requirements.txt.

Yeah, this hook really just sort of punts on the issue -- I'm just not sure what would be a better solution. :-/
