### ISSUE TITLE
How to init a fully isolated renv?

### ISSUE THREAD

**Issue by stefanoborini** [rstudio/renv#1732]
From my understanding of the renv::init() process, the resulting environment still allows you to reach libraries in the system installation. This however has a side effect of letting older deployment of a library that is system installed (in my case, Matrix) "bubble in".

What I want is a fully isolated renv that does not see the system-level installed libraries. How does one do that? I tried to remove the appropriate link entries in the cache, but it appears that some smart system recreates the link when the library is loaded (e.g. by doing tab complete to Matrix::)

**Comment by kevinushey** [comment]
For background, `renv` creates a sandbox for the default library path, so that only so-called "base" and "recommended" R packages are made visible. This is described a bit in https://rstudio.github.io/renv/reference/config.html#renv-config-sandbox-enabled, and happens here:

https://github.com/rstudio/renv/blob/8a1b7fdf2b01d47b8e83a3387dcb4e6c190e9710/R/sandbox.R#L147-L190

If you wanted only "base" packages to be made available in the sandbox, you should be able to set:

```
options(renv.sandbox.priority = "base")
```

in an appropriate startup R profile.

I believe R assumes that all "base" level packages are available in the default library path, so it might not be safe to further exclude those packages, though.

Let me know if you think this is sufficient; if not I can try to make this a bit more configurable.
