### ISSUE TITLE
Warning: requested TAR '/usr/bin/tar' does not exist; using '/bin/tar' instead (renv 1.03, R 4.3.2, Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by mabuimo** [rstudio/renv#1794]
Hi, I have noticed that when I load any project which uses renv 1.03 under Ubuntu 20.04 LTS and using R 4.3.2 I get this warning:

```R
renv::activate()
Warning message:
requested TAR '/usr/bin/tar' does not exist; using '/bin/tar' instead 

Restarting R session...

Warning message:
requested TAR '/usr/bin/tar' does not exist; using '/bin/tar' instead 
```

I don't get this message if I use R 4.2.2,  Ubuntu 20.04 LTS, and renv 1.03.

**Comment by kevinushey** [comment]
R uses the value of the `TAR` environment variable when attempting to figure out what `tar` executable should be used. It looks like you have `TAR` set to a location that doesn't exist, so `renv` is detecting that and recovering.

That said, I don't know how your machine got into this state, since:

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ which -a tar
/usr/bin/tar
/bin/tar
```

You could try manually reinstalling `tar`, e.g. `sudo apt install tar`.

**Comment by kevinushey** [comment]
Strange, it looks like you're right... but I've always seen a `tar` installation at `/usr/bin/tar`, even though it's not provided by any `apt` package. Even a plain Ubuntu 20.04 Docker image has `/usr/bin/tar` available.

Either way, your solution should be fine, but the alternative would be to find where the `TAR` environment variable is being set and update that. Usually that's set here:

```
$ cat $(R RHOME)/etc/Renviron | grep tar
## used by untar(support_old_tars = TRUE) and installing grDevices
## Prefer a tar that can automagically read compressed archives
TAR=${TAR-'/bin/tar'}
```

so it might be worth checking whether your R installation is referring to `/usr/bin/tar` instead of `/bin/tar`.

**Comment by kevinushey** [comment]
How was R installed?

**Comment by kevinushey** [comment]
Thanks! I think this is an issue with the binary builds of R being distributed by Posit then -- it should prefer using `/bin/tar` instead of `/usr/bin/tar` here. I'll forward this issue on in the appropriate channels.

**Comment by kevinushey** [comment]
In the meantime, I think we've found a workaround for your case (use a symlink in `/usr/bin`) and I think that will be sufficient.
