### ISSUE TITLE
Make renv::status() happy with local package

### ISSUE THREAD

**Issue by andreasleha** [rstudio/renv#1797]
My question is:  How do I make `renv::status()` happy with a (bioconductor) package installed from a local source.

I have installed [PowerExplorer](https://bioconductor.org/packages/3.10/bioc/html/PowerExplorer.html) (which was removed from bioconductor several releases ago) from a local source.

Following [the documentation](https://mpn.metworx.com/packages/renv/0.12.2/articles/local-sources.html#explicit-sources) I have this in my `renv.lock`:

```
    "PowerExplorer": {
      "Package": "PowerExplorer",
      "Version": "1.6.0",
      "Source": "share/PowerExplorer_1.6.0.tar.gz",
      "Requirements": [
        "Biobase",
        "BiocParallel",
        "DESeq2",
        "MASS",
        "R",
        "ROTS",
        "S4Vectors",
        "SummarizedExperiment",
        "data.table",
        "ggplot2",
        "gridExtra",
        "methods",
        "stats",
        "utils",
        "vsn"
      ],
      "Hash": "9492a1b5ec179913aeb2973e85d62260"
    }
```

I very much like that as that

1. makes the local source explicit and
2. allows `renv::restore()` to restore the package (given that `share/PowerExplorer_1.6.0.tar.gz` is available, of course)

But `renv` itself does not seem to be too fond of that as it keeps telling me that

```
- The project is out-of-sync -- use `renv::status()` for details.
```

The output of `renv::status()` is

```
The following package(s) are out of sync [lockfile -> library]:

# Bioconductor ---------------------------------------------------------------
- PowerExplorer   [1.6.0: share/PowerExplorer_1.6.0.tar.gz -> Bioconductor]


See ?renv::status() for advice on resolving these issues.
```

`renv::restore()`  does not solve the issue:

```
> renv::restore()
The following package(s) will be updated:

# share/PowerExplorer_1.6.0.tar.gz -------------------------------------------
- PowerExplorer   [1.6.0: Bioconductor -> share/PowerExplorer_1.6.0.tar.gz]

Do you want to proceed? [Y/n]: 
# Installing packages --------------------------------------------------------
- Installing PowerExplorer ...                  OK [linked from cache]
```

So, `renv::restore()` works but `renv::status()` still complains about `out-of-sync`.

And `renv::snapshot()` replaces the local source with 'Bioconductor':

```
> renv::snapshot()
The following Bioconductor packages appear to be from a separate Bioconductor release:
- PowerExplorer [installed 1.6.0 != latest <NA>]
renv may be unable to restore these packages.
Bioconductor version: 3.16

Do you want to proceed? [Y/n]: Y

The following package(s) will be updated in the lockfile:

# Bioconductor ---------------------------------------------------------------
- PowerExplorer   [1.6.0: share/PowerExplorer_1.6.0.tar.gz -> Bioconductor]

Do you want to proceed? [Y/n]: 
- Lockfile written to "renv.lock".
```

While this makes 'renv::status()` happy

```
> renv::status()
No issues found -- the project is in a consistent state.
```

this makes the project un-reproducible, as the installation of `PowerExplorer` from Biocondutor later fails (`renv::restore()` complains about `Error: failed to retrieve package 'PowerExplorer@1.6.0'`)

So my question is:  How can I make `renv::status()` happy with using the local package?

Update: Version info:
This is with `renv 1.0.3` running in `R 4.2.3`

**Comment by kevinushey** [comment]
Thanks for the bug report! I think the most appropriate solution would be to modify the package's DESCRIPTION file, so that it declared an explicit remote source in the way you're trying to do in the lockfile. In other words, `status()` isn't really lying -- it's saying that the source declared in the lockfile doesn't match what it sees in the currently-installed package.

That said, it looks like PowerExplorer 1.6.0 is available for Bioconductor 3.10:

https://bioconductor.org/packages/3.10/bioc/html/PowerExplorer.html

Is it possible your `renv` project has been configured to use an older version of Bioconductor? Or are you trying to mix packages from different Bioconductor releases?

The other option would be to explicitly install that package from the BIoconductor `git` repository; for example:

```
renv::install('git::https://git.bioconductor.org/packages/PowerExplorer')
```

You could also use the git log to pick an appropriate revision if needed, e.g.

```
renv::install('git::https://git.bioconductor.org/packages/PowerExplorer@728f06206db886f57e90cbe651c66ecfe30fa33a')
```

That revision would need to be gleaned from the git repository at that URL; you could look through the older revisions and see which one is most appropriate.

**Comment by andreasleha** [comment]
@kevinushey Thanks for looking into this!

Could you elaborate on your suggested most appropriate solution?  I am not aware of a possibility to declare an explicit remote source in the `DESCRIPTION` file.  How would that be done?

(Yes, PowerExplorer is from bioconductor, and yes, I am trying to mix, since PowerExplorer was removed in bioconductor release 3.12, and bioconductor 3.11 was released in spring 2020 and marked as compatible with R 4.0)

Installing from the git repo works fine, thanks for this.

And a final question for me to understand this:

If I install from git, then the git source overrides whatever is in the DESCRIPTION.  But if I install from a local source, there is no way to override whatever is in the DESCRIPTION.  Is that a fair summary?

If that is a fair summary, then I'd suggest to make it somehow possible to also have a local source override the DESCRIPTION.

**Comment by kevinushey** [comment]
> I am not aware of a possibility to declare an explicit remote source in the DESCRIPTION file. How would that be done?

This is usually done behind the scenes for you by packages like `remotes` / `pak` and also `renv`; they place a number of `Remote*` fields in the DESCRIPTION after install. So I guess I should back-pedal a bit: setting these manually probably isn't the best solution, since other tools will want to write these based on how a package was installed.

> If I install from git, then the git source overrides whatever is in the DESCRIPTION.

To be more specific, when the package is installed from a `git` remote, a number of `Remote*` fields are written into the package's DESCRIPTION file, so that tools like `renv` or `devtools` can see remote source for this package. This lets tools like `renv` infer the source for the package in `renv::snapshot()`.

> But if I install from a local source, there is no way to override whatever is in the DESCRIPTION. Is that a fair summary?

It's more that if you install from a local source, then the remote location for that package (the `Remote*` fields) are never written to the DESCRIPTION file, so `renv` doesn't know what the appropriate remote source is.

I think there are two paths forward:

1. Install the package from a `git` remote, like I described above;
2. Rather than try to change the lockfile, use something like the [Cellar](https://rstudio.github.io/renv/articles/package-sources.html#the-package-cellar) to provide a specific override for that package.

There is also a (currently undocumented) feature where you can override records for restore with the `renv.records.override` option. For example:

```
options(renv.records = list(
  PowerExplorer = list(
    Package = "PowerExplorer",
    Version = "1.6.0",
    Source = "share/PowerExplorer_1.6.0.tar.gz"
  )
))

renv::restore()
```

**Comment by andreasleha** [comment]
Thank you for the detailed and updated answer!
