### ISSUE TITLE
Processing R scripts outside of project folder

### ISSUE THREAD

**Issue by BrianCollinss** [rstudio/renv#1805]
I usually have some files from other projects that are used/sourced in the current project. Is there any way to include those files/folders in Init or Snapshot so when those files are sourced, their packages are already available?

**Comment by kevinushey** [comment]
There isn't anything directly available in `renv` to support this, but one option would be to symlink those files into your project into some location, so that `renv` can see them within the project. This would also ensure that any updates made to those files in the other project(s) would be visible to `renv` as well.
