### ISSUE TITLE
Restore not respecting options(pkgType="binary")

### ISSUE THREAD

**Issue by scarnecchia** [rstudio/renv#1875]
I'm not sure how to reprex this, so please let me know if there is anything I should add. On machines without Rtools installed, renv is attempting to build some packages from source instead of using binaries when restoring. `options(pkgType="binary")` is set in .Rprofile.

```
source("renv/activate.R")
options(pkgType = "binary")
renv::restore(prompt=FALSE)
```

```
- Installing xfun ...                           FAILED
Traceback (most recent calls last):
13: renv::restore(prompt = FALSE)
12: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
Error: Error installing package 'xfun':
================================

* installing *source* package 'xfun' ...
** package 'xfun' successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  : 
  'make' not found
* removing 'C:/REDACTED/renv/staging/1/xfun'
install of package 'xfun' failed [error code 1]
Execution halted
```

Several users without RTools need to be able to use this script and outside of having each of them run renv::install with type set to binary for each package, I'm at a loss as to how to solve this.

**Comment by kevinushey** [comment]
A reproducible example (not necessarily a reprex) would be helpful -- even if it just means sharing the lockfile you're using during restore. The output of `renv::diagnostics()` may also be useful.

What version of the `xfun` package is being installed? Is it possible that an older version of `xfun` is being installed, for which no binaries are available?

I'm also surprised because renv should be smart enough to automatically activate / use Rtools when installing packages from sources, so more details will definitely help here.

**Comment by scarnecchia** [comment]
On your last point, these users do not have RTools installed. That said, I'm closing this issue: It appears to be corporate IT randomly blocking CRAN and P3M binaries is to blame. Thanks!
