### ISSUE TITLE
Dependency discovery taking lot of time.

### ISSUE THREAD

**Issue by asif7adil** [rstudio/renv#1898]
Why is my renv behaving like this. I tried to add an .renvignore flle and added entries for data and R markdown files (which I thought were causing the problem), but it is still taking a lot of time on `renv::snapshot()` as well as at the time of loading the R.

```
- Project '~/Desktop/workspace/pdac_nac' loaded. [renv 1.0.7]

NOTE: Dependency discovery took 3200 seconds during snapshot.
Consider using .renvignore to ignore files, or switching to explicit snapshots.
See `?renv::dependencies` for more information.

Warning messages:
1: In parse(text = text, keep.source = FALSE, srcfile = NULL) :
  1271:1: unexpected input
1270:      "data"= list(
1271: <<
      ^
2: In parse(text = text, keep.source = FALSE, srcfile = NULL) :
  232:1: unexpected input
231:    "source"= list(
232: <<
     ^
3: In parse(text = text, keep.source = FALSE, srcfile = NULL) :
  56:1: unexpected input
55:    "cell_type"= "code",
56: <<
    ^
4: In gregexpr(pattern, text, perl = TRUE) : PCRE error
        'match limit exceeded'
        for element 1
``` 

I am seeing 2 R folders in my renv R 4.3 and R 4.4 can they be a part of problem?
please help

**Comment by asif7adil** [comment]
I tried deleting the R folders and the old lockfile, but the problem still remains. After deleting the lockfile, the R loaded quickly (with obvious inconsistencies in renv) but when I tried to do the snapsho, it again took hell lot of time.

**Comment by kevinushey** [comment]
It's hard to provide concrete advice without a reproducible example, but you could also try using "explicit" snapshots instead of "implicit" snapshots, and record your package dependencies in the project DESCRIPTION file. This would allow you to sidestep the issue with dependency discovery altogether. Please see https://rstudio.github.io/renv/reference/snapshot.html#snapshot-types for more details.
