### ISSUE TITLE
Error with renv_file_copy_dir when activate renv 

### ISSUE THREAD

**Issue by EgirardBioinfo** [rstudio/renv#210]
Hi, 

I have two jobs running at the same time, and both activate the renv path to load packages.  Sometimes, I get the following error with both jobs (but they work when run separately) : 

Error in file.rename(tempfile, target) : 
  cannot rename file '{path_to_packages}/renv/library/R-3.6/x86_64-conda_cos6-linux-gnu/renv-copy-7a7b3826858b/renv' to '{path_to_packages}/renv/library/R-3.6/x86_64-conda_cos6-linux-gnu/renv', reason 'File exists'
Calls: .First ... renv_file_copy -> case -> eval -> eval -> renv_file_copy_dir
Traceback (most recent calls first):
12: .First()
11: renv::activate("/data/tmp/egirard/renv/renv_36_new")
10: renv_activate_impl(project, NULL, FALSE, FALSE)
 9: renv_bootstrap_impl(project)
 8: renv_bootstrap_self(project)
 7: renv_bootstrap_self_binary(source, target)
 6: renv_file_copy(source, target, overwrite = TRUE)
 5: case(identical(info$isdir, FALSE) ~ renv_file_copy_file(source, 
        target), identical(info$isdir, TRUE) ~ renv_file_copy_dir(source, 
        target))
 4: eval(expr, envir = environment(dot))
 3: eval(expr, envir = environment(dot))
 2: renv_file_copy_dir(source, target)
 1: stop(status)
Execution halted

Is there a way to avoid this copy ? 
Thanks, 
Elodie

**Comment by kevinushey** [comment]
I wonder if you want to call `renv::load()` instead of `renv::activate()`? At least, that would skip the bootstrap step (where `renv` ensures the version of `renv` you're using gets installed into the project library). I'm not sure if that's necessary for your workflow or not.

If using `renv::load()` does indeed work for you, then perhaps I need to update the documentation somewhere?

**Comment by kevinushey** [comment]
To the best of my knowledge, `renv::load()` should be sufficient. Feel free to re-open if you find it is not.
