### ISSUE TITLE
Should cleanup() remove non-dependencies from the library?

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#22]

**Comment by jjallaire** [comment]
We explored this in packrat and one problem is that you can have "dependencies" that aren't visible in your code (e.g. the code of a Shiny app doesn't technically need to `library(shiny)`, an Rmd doesn't need to reference rmarkdown, a project where you want to use pkgdown or usethis doesn't reference them in code, etc.). We could try to run down 100% of these cases but it wouldn't be perfect so "cleanup" would often end up removing packages that you'd then need to reinstall.

**Comment by hadley** [comment]
But `dependencies()` must have captured these in the first place? Otherwise how did they get into your library?

**Comment by jjallaire** [comment]
Couldn't you just install them with `install.packages()` and they'd go into your project level library (maybe I'm missing something about how renv works?). Note that these dependencies might not be runtime dependencies (i.e. you don't need them for deployment) but simply tools (e.g. utilities, RStudio Addins, etc.) you like to use alongside your project.

**Comment by hadley** [comment]
My gut feeling is that those should live in your system library, but I haven't thought through all the consequences of that.

Overall, it seems to me like having a library that is partly managed by packrat and partly managed by the user is a recipe for confusion.

**Comment by kevinushey** [comment]
Right, new packages would enter the library + lockfile as the user installs them and later snapshots the new changes.

Note that library cleanup becomes less of a concern with a global cache (since now the only cost you're paying in the private library is some symlinks that you're not using) but may still be worth doing for 'hygiene'.

**Comment by kevinushey** [comment]
Things become quite a bit more complicated once we start thinking about management of multiple active libraries -- e.g. if you wanted to use `devtools` from an external library, but needed to depend on the development version of one of its dependencies (say, `remotes`) while still keeping the CRAN version of `remotes` in the external library.

In theory you could just store the development version of remotes in the private library and snapshot just that change but then you run into problems restoring later since now you have a project depending on `devtools` + a dev. version of `remotes` but that depenency on `devtools` is not declared anywhere.

Keeping everything in a single library is much safer, and with a global cache + symlinks is still very cheap (even if it means some lockfile bloat)

**Comment by hadley** [comment]
It's going to take me some time to get my head around the idea of the project library just being symlinks — this resolves my concerns.

**Comment by hadley** [comment]
What I'm finding useful is to run R in the console with `R --no-init-file` — that allows me to use all the interactive helpers I usually have set up, without renv having to know anything about them.

**Comment by kevinushey** [comment]
What do you think `renv` should do here?

1. Only source the project's `.Rprofile` (current behavior),
2. Source both the project `.Rprofile` and a user profile at `~/.Rprofile`,
3. Provide a project setting (or environment variable?) that lets users control this behavior.

I'm a bit wary of (2) because some users might try to munge their libpaths in the global `.Rprofile`, but I suppose we could always override that by sourcing the user profile _then_ initializing `renv`.

**Comment by hadley** [comment]
I think (2) should probably be the default, sourcing the user profile first, then fixing the libpaths.

**Comment by hadley** [comment]
But it would be good to have an option so you could get "stricter" reproducibility by eliminating the user Rprofile

**Comment by khughitt** [comment]
It's probably worth adding a note in the docs or warn the user since this could impact portability..

**Comment by kevinushey** [comment]
@khughitt can you elaborate?

**Comment by khughitt** [comment]
Sure - for example, if a user has:

```r
options(stringsAsFactors=FALSE)
```

in their `~/.Rprofile`, code will behave differently for them than for others who may be attempting to recreate the environment using renv.
