### ISSUE TITLE
Multiple named renv profiles?

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#253]
I might be missing something but it seems that currently renv doesn't allow for multiple named "profiles" to co-exist. 

I often work simultaneously with multiple versions of R and dependency packages. Would be really great if renv.lock could store multiple profiles, dev, test, deploy etc. 

Even more so, for the interactive use one of them could be chosen automatically depending on the version of R.  Currently, if I start with a different version of R, I am getting an incompatibility error and the renv is not loaded. What would be the easiest way to accommodate multiple R versions right now? Thanks!

**Comment by kevinushey** [comment]
You are correct, there is only a single "profile" per `renv` project. (Although, I think if we were to support multiple profiles, I would prefer to accomplish that with with separate lockfiles for each profile rather than within a single, unified lockfile.)

> Even more so, for the interactive use one of them could be chosen automatically depending on the version of R. Currently, if I start with a different version of R, I am getting an incompatibility error and the renv is not loaded. What would be the easiest way to accommodate multiple R versions right now?

Currently, I think the onus is on the front-end hosting R, or the user, to find and choose an appropriate version of R based on what is recorded within `renv.lock`. In theory, `renv` could try to support this in some way, but right now I'd rather punt on that issue until it's demonstrated that it needs to be solved at the `renv` level.

I could imagine this being accomplished in a similar way as Python virtual environments -- e.g. using symlinks back to known R installations, and "activating" those installations by updating the PATH and so on. Not sure if there's an analog that could work for Windows, though.

**Comment by vspinu** [comment]
> I would prefer to accomplish that with with separate lockfiles for each profile rather than within a single, unified lockfile.

It's not very common in my experience, but can be of course. The important part is to allow some kind of inheritance. For instance, one might want to add just a few packages to the default profile, or simply change the R version across various profiles. 

>  to find and choose an appropriate version of R based on what is recorded within renv.lock

I am actually more interested in making it work the other way around. I start an R-x.y.z and renv would activate the appropriate environment. This would allows seamless switching between say dev and production setups. Right now I don't see how to easily run a travis matrix across different versions of R with renv. Something like `renv::use("dev")` and a corresponding variable would have been great.

**Comment by kevinushey** [comment]
> It's not very common in my experience, but can be of course. The important part is to allow some kind of inheritance. For instance, one might want to add just a few packages to the default profile, or simply change only the R version across various profiles. So replicating the entire list of deps seems unnecessary.

I don't really view the set of packages within a lockfile as a "profile" in this way, though. It's just a snapshot of the project + R library state at some point in time. I think what you want might be somewhat different from `renv`'s notion of a lockfile.

Using Node as an example, `renv.lock` is more akin to `package-lock.json` than `package.json`. Right now, nothing in R / `renv` serves the exact role of `package.json` (although the `DESCRIPTION` file is somewhat close?)

I might be misunderstanding your point a bit, though.

> I am actually more interested in making it work the other way around. I start an R-x.y.z and renv would activate the appropriate environment. This would allows seamless switching between say dev and production setups.

This makes sense to me... I'll try to think a bit more about what this might look like.

**Comment by vspinu** [comment]
> I don't really view the set of packages within a lockfile as a "profile" in this way, though. It's just a snapshot of the project + R library state at some point in time. I think what you want might be somewhat different from renv's notion of a lockfile.

Indeed. My expectation is probably somewhat different and maybe out of scope. I see a working environment as a collection of settings. I am coming from [clojure's lein profiles](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md) where profiles are dictionaries of arbitrary settings and I can [inherit or merge](https://cb.codes/leiningen-profile-overrides/) profiles arbitrary.

As an example, for different development/usage scenarios I want to be able to restore different (sub)sets of the packages. When running in a travis I want `renv:restore("test")` which would include testthat, styler etc. With "test-local" I would require "microbenchmark". On a production docker I want the `renv:restore("prod")` profile with bare minimum dependencies. For `renv:restore("dev")` I want the comprehensive set of development packages. For `renv:restore("dev-next")` it's the most recent R and packages versions.

Relatedly, I think renv should be able not just to track but also load/attach packages from a profile (say `renv::load("dev")`). Currently one needs to do some annoying duplication. Packages are listed in DESCRIPTION (and `renv::install` relies on it), but the developer (in non-R-package contexts at least) still needs to duplicate those with `library(..)` calls in the main code.

**Comment by grepinsight** [comment]
Chiming in here, 

I like to have an idea of having multiple profiles. This is sort of resonating with `one codebase, multiple deploys` mantra of [12 factor app](https://12factor.net/codebase).

My use case would be that I mostly develop stuff locally but want to run the code using remote machines since the latter can handle more computationally heavy tasks. 

Locally, I would use a lot of dev productivity tools such as `devtools`, `usethis`, etc, but in the remote machine, I would just use the minimal set of packages to run the task.

**Comment by kevinushey** [comment]
> Locally, I would use a lot of dev productivity tools such as devtools, usethis, etc, but in the remote machine, I would just use the minimal set of packages to run the task.

Note that by default (that is, when using "packrat"-style snaphsots) the lockfile will only capture 'runtime' or 'deployment' dependencies. That is, only packages which are explicitly referenced and used in your codebase (alongside their recursive dependencies) will enter the lockfile.

**Comment by kevinushey** [comment]
> Relatedly, I think renv should be able not just to track but also load/attach packages from a profile (say renv::load("dev")). Currently one needs to do some annoying duplication. Packages are listed in DESCRIPTION (and renv::install relies on it), but the developer (in non-R-package contexts at least) still needs to duplicate those with library(..) calls in the main code.

There are a few downsides to auto-loading packages:

1. On Windows, attempting to update loaded packages often fails, due to the way Windows locks loaded DLLs. A change like this could make it more difficult for Windows users to upgrade packages in their projects. In reality, we're a bit insulated from this issue due to the use of the `renv` cache + junction points, but not all users will want to enable the cache.

2. The way you write scripts in an `renv` project now becomes different from how you might run it within a "normal" project. I'd prefer to avoid imposing `renv`-specific workflows into user code if possible.

**Comment by vspinu** [comment]
> auto-loading packages:

I actually didn't mean to "autoload" the packages, but thought of an utility similar to `pacman::p_load`. Opened #278 for this.

**Comment by vspinu** [comment]
A few more concrete use cases here:

 1) Explore caching during docker build. 
     We have a setup whith a few internal packages rotating very fast and other dependencies not. Would be nice if inside a docker one would be able to have to `renv:restore` layers. First, for slow packages, second for fast packages. So te first run would be cached by the docker and only second RUN would be re-build wen only fast packages change. This can be achieved by nested profiles, where child profile would include everything from the parent profile + fast packages. 

 2) Reusing R-env across multiple projects. 
     Often its needed that multiple projects should use the same version. For instance, training can live in a separate repo from the deployment package. Or data fetchers, feature extractors, preprocessing etc. can live in a separate place from the code which consumes that data. Would be great to be able to split the renv into different functional parts. 
     
One way of achieving both of the above might be to allow for .renv.lock to be a directory with related renv.lock files inside. Then `renv:restore()` would restore all of them, but `renv::restore(profile = "foobar")` would restore only one of them. This way one can have `.renv.lock` as a git submodule which other projects could contain. 

I believe such a solution could be achieved transparently with minimal changes to the current code by insulating the lock storage backend from the rest of the code with some minimal backend API.

**Comment by jameshowison** [comment]
@vspinu Sounds a little like a case for multi-stage docker builds? But that might need separate renv.lock files, otherwise Docker sees the changed file and invalidates caches for both stages.  I've been idly wondering if `git diff` to create a "just the changes" file makes any sense?

**Comment by vspinu** [comment]
Precisely. That's why I think storing renv profiles in a `.renv.lock` folder as separate files is a good idea.
