### ISSUE TITLE
renv::activate/deactivate clobber .Rprofile

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#259]
Renv treats .Rprofile pretty harshly. 

First, it removes all the indentation. 

Second, `renv::deactivate()` removes the `source("renv/activate.R")` and then `renv::activate()` adds it to the end of the file. This is not right in most of the use cases except of the very basic one. One would normally want to run some custom code/setup after renv/activation. 

Looks to me that right approach would be to simply comment/comment the `source("renv/activate.R")` and let it to the user to decide where it should be located.

**Comment by kevinushey** [comment]
Thanks; I agree that this would be cleaner.

**Comment by kevinushey** [comment]
I'm recalling now why this worked the way it did. Previously, calling `renv::deactivate()` would remove the `.Rprofile` if the only thing it contained was the `source("renv/activate.R")` script; I believe that behavior needs to be maintained for otherwise-empty `.Rprofile`s.

Currently, having a blank `.Rprofile` means the user profile is not sourced for R projects launched within a "deactivated" project, which I believe is undesired.
