### ISSUE TITLE
rethink including R version when building hash?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#265]
E.g.

https://github.com/rstudio/renv/blob/39ad7ee9590ed55ad68b4c6fe0b9c6cfefceba2d/R/hash.R#L22-L23

It's no longer clear to me what the motivation for this decision was.

**Comment by aronatkins** [comment]
Is the cache directory specific to one R version or shared across R versions? This code include MAJ.MIN in the hash but ignores the final patch component. Was there discussion about having a shared cache directory that needed to split entries by version?

**Comment by kevinushey** [comment]
The cache directory does always include the version of R + platform:

```
> renv::paths$cache()
[1] "/Users/kevin/Library/Application Support/renv/cache/v4/R-3.5/x86_64-apple-darwin15.6.0"
```

What's not clear to me is whether the version of R also needs to be included when computing the hash for a particular package.

Put another way: should the hash for `digest_0.4.1.tar.gz` differ depend on whether I'm using R 3.4.4 or R 3.5.2?

I can imagine this causing problems when attempting to validate the hashes for a lockfile if one did not use the same version of R as encoded in the lockfile.

**Comment by aronatkins** [comment]
Since the cache directory structure includes R version, it feels OK to exclude R version from the hash. That's good because it means your hash can be stable across R versions (assuming the package DESCRIPTION data is all present and available and there are no issue with R version compatibility).

The unfortunate thing is that changing it now will alter in-the-wild hashes.

Related: Was R version initially meant to differentiate between binaries built with different R distributions? Open-source R versus the other R distributions? That's something we talked about w.r.t. the packrat cache...

**Comment by kevinushey** [comment]
> The unfortunate thing is that changing it now will alter in-the-wild hashes.

To accommodate this, I've added a function `renv::rehash()` that basically re-orients packages in the cache based on newly-computed hashes. Existing cache entries are preserved as symlinks to the newly-hashed location.

For safety, the `renv` cache version has been bumped regardless.

> Related: Was R version initially meant to differentiate between binaries built with different R distributions? Open-source R versus the other R distributions? That's something we talked about w.r.t. the packrat cache...

That wasn't the intention, but is perhaps something we should still consider. There's also a question about maintaining different caches for the same version of R, but where each version of R is configured to use different compilers.
