### ISSUE TITLE
Allow explicit list of packages to snapshot with `renv::snapshot`

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#275]
It's occasionally necessary to snapshot some packages but to restore another set of packages. `restore` already has `packages` argument. I think it would be nice to add this argument to the `snapshot` as well. 

I just had the following use case:

 1) I am using the most recent version of `renv` 
 2) I pull a PR from a collaborator which rolls back a bunch of packages, but uses a different version of `renv`. 
 3) I want to restore the packages that my colaborator wants to restore, but to snapshot the new version of `renv`. 

Would be nice if I could do `renv::snapshot(packages="renv")` and then `renv::restore()`. Currently I have to either restore the package list selectively (all without renv), or restore all then upgrade renv and then snapshot. 

More generally the exclusion argument begs itself here. For a consistent API, all 3 core functions `update`,  `snapshot`, and `restore` could have `include_packages` and `exclude_packages` arguments. With these, I wouldn't know what would one need more in order to manipulate `renv.lock`. 

Somewhat related #157

**Comment by kevinushey** [comment]
FWIW I think you could accomplish effectively the same thing with:

```
# restore from collaborator's lockfile
renv::restore()

# install new version of renv
renv::install("rstudio/renv@<version>")

# snapshot the newly-installed renv
renv::snapshot()
```

**Comment by kevinushey** [comment]
If someone executes:

```
renv::snapshot(packages = "dplyr")
```

should that also include `dplyr`'s dependencies and their versions in the lockfile?

**Comment by vspinu** [comment]
> should that also include dplyr's dependencies and their versions in the lockfile?

I think so, a package and its dependencies is a unit that renv should operate upon, or not? I certainly would be surprised if it didn't.

**Comment by vspinu** [comment]
We just stumbled with another use-case for which the `packages` argument would have been extremely useful. 

Our production branch has slightly older packages. A colaborator deleted the cache and 1) restored the packages on a dev branch (all up-to-date) then moved to production branch and 2) attempted to restore the older packages. For some unclear reason older version of  KernSmooth failed. But the newer version of KernSmooth could be installed successfully. Now, what he wanted is to snapshot the new version of KernSmooth only, but because there is no such option the only way to quickly move over was to snapshot all 30 other packages with the new version which he installed in step 1.

**Comment by kevinushey** [comment]
That makes sense and seems like a pretty compelling reason for handling this better.

However, it still feels slightly outside of the contract for `renv::snapshot()`. In this case, you want to _update an existing lockfile_, which is still a distinct action from _save the library state of a subset of packages_ (which is theoretically what `renv::snapshot(packages = ...)` would do).

If I understand correctly, in your example you want to preserve existing lockfile records; you only want to update or change a single record.

Thinking out loud, I think the appropriate API would be something like:

```
renv:::lockfile_add(KernSmooth = "1.0.0")
```

which would basically say, "update the lockfile so that KernSmooth 1.0.0 is used from CRAN (or, more concretely, the active R repositories).

**Comment by vspinu** [comment]
> you want to update an existing lockfile, which is still a distinct action from save the library state of a subset of packages (which is theoretically what renv::snapshot(packages = ...) would do)

Hmm, interesting distinction. I surely never thought of it that way. For me `snapshot` was always equivalent to _add a bunch of packages to the lock file_. `library` itself is somehow always in the shadow where the magic happens. To be frank, for long time I was under impression (somewhat unconsciously) that `renv` is supposed to automatically keep the library and renv in sync. It only recently after quite a few `renv::restore` it started truly sinking to me that `library` and `renv.lock` are distinct states that could be under many scenarios very different. 

> renv:::lockfile_add(KernSmooth = "1.0.0")

That could be but it would make the api even more complex and the above distinction enforced. 

Also thinking out loud, an alternative approach would be to stick to your definition of `snapshot(packages= ...)` and simply use the `update(packages = ...)` intermediate step. So basically in my case it would be:

```R
renv::update("KernSmooth")
renv::snapshot("KernSmooth")
```

More generally regarding #157, I think the entire API could be reduced to reading the lockfile into a list and writing it back. This way people truly interest in manipulate the renv.lock can do it with familiar tooling.

**Comment by vspinu** [comment]
> in my case it would be:

Actually for the `update` -> `snapshot` strategy to work satisfactory one would need to be able to "update" to specific versions. Like `renv::update("mlr@2.14.0")` which I don't think works right now.

**Comment by kevinushey** [comment]
> Hmm, interesting distinction. I surely never thought of it that way. For me snapshot was always equivalent to add a bunch of packages to the lock file. library itself is somehow always in the shadow where the magic happens.

That's the heart of the way `renv` works, though -- `snapshot()` saves the library state to a lockfile, and `restore()` restores the library state from a lockfile. That is, they just "save" and "load" the library state.

> To be frank, for long time I was under impression (somewhat unconsciously) that renv is supposed to automatically keep the library and renv in sync. It only recently after quite a few renv::restore it started truly sinking to me that library and renv.lock are distinct states that could be under many scenarios very different.

In fact, there's a configuration option `auto.snapshot` to control this to help try and keep the two in sync -- so that any time `renv` does something that mutates the project library, `renv` will automatically snapshot to update the lockfile. See the documentation in `?config` for more details.

We decided to turn this off by default because ultimately it's still possible for users to do things that get the library + lockfile out-of-sync, and trying to enforce a world where they're _always_ in sync will just lead to some surprises. Forcing users to confront this reality ultimately seemed like the safest way forward.

> Actually for the update -> snapshot strategy to work satisfactory one would need to be able to "update" to specific versions. Like renv::update("mlr@2.14.0") which I don't think works right now.

FWIW, `renv::update()` is used to update packages within the project library, not directly in the lockfile. It should be used to take any currently-installed packages, and update to whatever is latest on the associated remote source. I think you want instead:

```
renv::install("mlr@2.14.0")
```

which is indeed a way to install a particular version of a package from CRAN.

Note that the workflow implied here is (1) install package, then (2) snapshot to update lockfile. It sounds like you might want to reverse this; e.g. (1) update lockfile with required package, and (2) `renv::restore()` to install that package.

**Comment by vspinu** [comment]
>  I think you want instead: renv::install("mlr@2.14.0")

Right, slipped my mind.

> Note that the workflow implied here is (1) install package, then (2) snapshot to update lockfile. It sounds like you might want to reverse this; e.g. (1) update lockfile with required package, and (2) renv::restore() to install that package.

Arent' these equivalent? The first workflow needs the OP proposal. The second workflow needs lockfile modification API. If the first workflow is implemented there is not so much need for lockfile API. Isn't it?

**Comment by kevinushey** [comment]
> Arent' these equivalent in terms of the end result? The first workflow needs the OP proposal. The second workflow needs lockfile modification API. If the first workflow is implemented there is not so much need for lockfile API. Isn't it?

They are indeed equivalent, but I think I can understand why some users would prefer the first approach and others the second.

Based on your example:

> Our production branch has slightly older packages. A colaborator deleted the cache and 1) restored the packages on a dev branch (all up-to-date) then moved to production branch and 2) attempted to restore the older packages. For some unclear reason older version of KernSmooth failed. But the newer version of KernSmooth could be installed successfully. Now, what he wanted is to snapshot the new version of KernSmooth only, but because there is no such option the only way to quickly move over was to snapshot all 30 other packages with the new version which he installed in step 1.

It seems like getting out of this state is challenging, since `renv::restore()` cannot run to completion (so the library cannot be synchronized with the lockfile), and the lockfile cannot be updated unless the library can be restored. If one could instead modify the lockfile directly, then they could sidestep issues related to failure to install or restore packages.

All that said; one can of course just modify their `renv` lockfile by hand to set things as appropriate -- one can probably infer the structure for the record for a package from CRAN. (The hash field is optional as well and can be omitted; which just implies restores won't be able to use the cache)

**Comment by kevinushey** [comment]
It's now possible to update a lockfile using `renv::record()`. For example, in your case, the lockfile-first approach would be:

```
renv::record("KernSmooth@2.23-16")
renv::restore()
```

Ultimately, I think this is the cleanest way forward for your example, beyond just modifying the lockfile by hand (which is also a totally valid solution)
