### ISSUE TITLE
Bioconductor packages via `install.packages` are not restored

### ISSUE THREAD

**Issue by mxposed** [rstudio/renv#277]
Hello, thank you for `renv`, really hope that it will take environment management problem away.

I have a little bit strange setup for `packrat` that appears to not work with `renv`.
I have a project with CRAN and Bioconductor dependencies, but I install all of them via `install.packages` by first setting the repos with `setRepositories()`.
This works for `renv` too, but the recorded `renv.lock` file states that Bioconductor packages were installed via Bioconductor, so restoring them fails on the other machine.

I guess since `renv` has now support for Bioconductor, I should use that (and I'll try), but I thought this is probably not the intended behaviour.
Thank you

**Comment by kevinushey** [comment]
> This works for renv too, but the recorded renv.lock file states that Bioconductor packages were installed via Bioconductor, so restoring them fails on the other machine.

`renv` reads the package `DESCRIPTION` file to attempt to determine its source. For packages installed from Bioconductor, the `biocViews` field is set, and so `renv` assumes that the package should be retrieved from the "official" Bioconductor repositories.

As a workaround, in the development version of `renv`, you can use:

```
options(renv.bioconductor.repos = getOption("repos"))
```

to force `renv` to use the default package repositories when attempting to restore Bioconductor packages, as well.

The alternative would be to ensure that the repositories containing your Bioconductor packages are also recorded in `renv.lock`, since `renv` should attempt to use the union of Bioconductor + CRAN packages when attempting to install packages from CRAN.

**Comment by kevinushey** [comment]
(If you're still having issues, a reproducible example would be greatly appreciated.)

**Comment by kevinushey** [comment]
To the best of my knowledge this issue is handled now -- please feel free to re-open if you're still having trouble with the development version of `renv`.
