### ISSUE TITLE
encourage use of DESCRIPTION file for explicit dependency tracking

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#336]
`renv::status()` could report packages which are mentioned in the lockfile, but not in the project `DESCRIPTION` file.

**Comment by ndevln** [comment]
This is something I would really wish for, since renv does not provide a clear way for explicit dependency tracking. I would even go so far as to make renv ignore all other package definitions if a DESCRIPTION file is present to discourage hidden dependencies. Since the DESCRIPTION file is already a good format, it maybe should be adopted to non-package projects. Like this:

```
Project: Project Name
Title: Project Title
Version: 0.1
Authors@R: person("First", "Last")
Description: What the project does (one paragraph)
Depends: R (>= 3.1.0)
Imports: lubridate, dplyr
Suggests: testthat
```

I think there are a lot of good arguments for this. I would like to have something like the [pyproject.toml](https://python-poetry.org/docs/pyproject/) from python. 

1. All dependencies are visible from the project root.
2. When using renv::update() unused dependencies can be dropped and don't have to be updated (i.e. if one of my explicit dependencies drops a dependency)
3. Dev dependencies can be cleanly separated from production dependencies (this is already implemented in renv)

The best part is that renv can already be used this way. But 2 features would be really nice:

1. When running renv::install the package installed should be automatically added to  the DESCRIPTION file.
2. Include a wizard to help you generate a basic DESCRIPTION file (maybe renv::init() will ask you if you want to create one).

From there you can do a lot of other fun stuff. Like defining scripts to run standard tasks (renv::run() would run the default skript and renv:run("test"); ) would run the testing.

I know this a lot of intrusion into your work and I don't know what your vision for the project is. I just want to say thank you for your work. If you like this idea I am happy to help to implement it. If not, I'm just a random guy on the internet :)

**Comment by hadley** [comment]
My experiments suggest that the motivating issue has already been fixed.

@ndevln you can get the behaviour you want with `renv::settings$snapshot.type("explicit")`
