### ISSUE TITLE
Surfacing consistent information when dependencies() uncovers problems

### ISSUE THREAD

**Issue by karawoo** [rstudio/renv#342]
It seems that `dependencies()` only sometimes reports a warning when it uncovers errors in R code that prevent it from detecting dependencies, which can lead to hard-to-diagnose issues using renv. For example, take a project with the following file, and renv initialized:

```r
library("tidyverse")
test <- data.frame(a = 1 b = 2) # note missing comma
```

The first time I call `dependencies()` I see a warning message about the syntax error, and renv is returned as the only dependency. If I call `dependencies()` again, I don't see any warning, and just get renv as the single dependency. If I then edit anything in the file, save, and call `dependencies()` again, I see the warning again. 

In practice, what I experienced is I tried to snapshot a project that I had unwittingly introduced a syntax error into. This resulted in renv wanting to remove all packages from the lockfile. I puzzled about this for a while, and as part of trying to figure it out I called `dependencies()`. But since it had been called by `snapshot()` already, there was no warning message.

Is it intentional that `dependencies()` behaves this way? It would have helped me figure out the problem sooner if `dependencies()` always warned about issues it uncovers (and even better, if that warning came through `snapshot()` as well), but not sure if there's other reasoning behind this behavior.

**Comment by kevinushey** [comment]
This isn't intentional -- it's caused by `renv`'s caching system, which tries to avoid re-computing dependencies on a file which has not changed. (The intention was to ensure `renv::dependencies()` can run fast enough in larger projects, where most files may remain unchanged in a given session)

Unfortunately, because we only cache the result of the dependency lookup but not any errors, those errors don't get re-emitted on subsequent calls to `renv::dependencies()`. Even worse, if `renv::dependencies(quiet = TRUE)` is called, then those errors are just quietly swallowed.

So, there's two things to fix here:

1. Cache both the result and any errors that occur during dependency lookup;
2. Consider emitting warnings when running `renv::dependencies(quiet = TRUE)` if that lookup fails.

**Comment by kevinushey** [comment]
This should be better handled on master now. By default, if an error is detected while attempting to enumerate dependencies, `renv` will show those errors (always) and prompt the user as to whether we should proceed or abort.

Let me know if this sounds like the right approach, or if there's anything else you think I might be missing.
