### ISSUE TITLE
how should renv_dependencies() handle missing packages?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#35]
This concerns the use of `renv::init()` for a brand new project.

Suppose you have a project that depends on `dplyr`; however, for some reason your user library is missing the dependency `tibble`. In this case, we see output like the following:

```R
> deps <- renv:::dependencies()
> deps
                            Source Package Require Version
1 /Users/kevin/scratch/oops/deps.R   dplyr

> str(renv:::renv_dependencies(".", deps$Package))
List of 19
 $ tidyselect: chr "~/Library/R/3.5/library/tidyselect"
 $ R6        : chr "~/Library/R/3.5/library/R6"
 $ magrittr  : chr "~/Library/R/3.5/library/magrittr"
 $ assertthat: chr "~/Library/R/3.5/library/assertthat"
 $ graphics  : chr "/Library/Frameworks/R.framework/Resources/library/graphics"
 $ tools     : chr "/Library/Frameworks/R.framework/Resources/library/tools"
 $ plogr     : chr "~/Library/R/3.5/library/plogr"
 $ glue      : chr "~/Library/R/3.5/library/glue"
 $ utils     : chr "/Library/Frameworks/R.framework/Resources/library/utils"
 $ dplyr     : chr "~/Library/R/3.5/library/dplyr"
 $ tibble    : logi NA
 $ grDevices : chr "/Library/Frameworks/R.framework/Resources/library/grDevices"
 $ Rcpp      : chr "~/Library/R/3.5/library/Rcpp"
 $ stats     : chr "/Library/Frameworks/R.framework/Resources/library/stats"
 $ methods   : chr "/Library/Frameworks/R.framework/Resources/library/methods"
 $ rlang     : chr "~/Library/R/3.5/library/rlang"
 $ pkgconfig : chr "~/Library/R/3.5/library/pkgconfig"
 $ BH        : chr "~/Library/R/3.5/library/BH"
 $ purrr     : chr "~/Library/R/3.5/library/purrr"

> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Resolving missing dependencies  ...
Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/tibble_2.1.1.tgz' ...
        OK [downloaded 310.6 Kb in 0.1 secs]
Installing crayon [1.3.4] ...
        OK (linked cache)
Installing cli [1.1.0] ...
        OK (linked cache)
Installing fansi [0.4.0] ...
        OK (linked cache)
Installing utf8 [1.1.4] ...
        OK (linked cache)
Installing pillar [1.3.1] ...
        OK (linked cache)
Installing tibble [2.1.1] from CRAN ...
        OK (installed binary)
* Lockfile written to '~/scratch/oops/renv.lock'.
* renv activated -- please restart the R session.
```

So, `renv` is able to recover and automatically download and install `tibble`, which is helpful. Some questions:

Suppose a version of `tibble` was installed in the cache. In what situations can we use it? We could:

- Just use the newest version of `tibble`;
- Use a version from the cache if it matches the latest version available on CRAN;
- Use a version from the cache if it's equal to, or newer, than the version on CRAN;
- Ask the user?

**Comment by slopp** [comment]
This one is really tricky... I don't think users will understand what is happening if asked (unless the message is really clear, we'd be asking them to have a pretty complete mental model of the cache AND the idea of dependent packages). 

What does `renv` use for its source of truth on the missing dependency, does it use the `dplyr` DESCRIPTION file? If that file is old, then there really isn't any way of knowing what dependent version of `tibble` the installed version of `dplyr` needs... perhaps a better error would be something like:

```
renv detected that dplyr is currently in a broken state .... would you like renv to install the newest dplyr version? Select "no" to abort the initialization and fix dplyr manually"
```

That way instead of guessing about the tibble dependency version, we just reinstall dplyr which follows a well known happy path.

**Comment by kevinushey** [comment]
`renv` would just use the latest-available version of `tibble` from CRAN, which like you guessed could fail if `dplyr` was an older version not compatible with newer `tibble`.

It seems like there are a few options:

1. Install the latest version from CRAN and hope for the best;
2. Ask the user what version of the missing dependencies they'd like to install;
3. Reinstall `dplyr` and all its dependencies (potentially upgrading them in the process).

It seems like (1) and (3) would be useful for people who just want a working environment and aren't necessarily trying to pin themselves against particular versions of their dependencies; (2) is useful if someone is seeking a reproducible workflow but something went awry down the way.

FWIW I think this issue is independent of the cache; the cache is just one source from which packages can be recovered / installed.

**Comment by slopp** [comment]
I don't like #1, because it could lead to a a few  bad situations:
a. the install fails and the user goes "why is snapshot installing anything? my mental model of all the things must be broken"
b. the install succeeds, but loading dplyr fails, which means we just snapshotted something broken, and again the user hasn't seen any of the magic, so they're just confused

#2 or #3 both make sense, but for #2 the message would have to be pretty verbose (I think).  I like the idea that snapshot isn't too magical, just helpful. So perhaps a mix of solutions 2 and 3 would be throwing an error message that is helpful, e.g.: 

"dplyr is broken, we aren't going to snapshot a broken state. You should fix dplyr's missing tibble dependency, perhaps by reinstalling dplyr. Once fixed, try to snapshot again"

I think having snapshot do the work actually makes for a more confusing situation, where a user could easily get themselves intro trouble.  Having snapshot fail, forces the user to re-consider what they are trying to snapshot, and use other tools (e.g. renv::install) before snapshotting again. 

This feels similar to how git merge fails on merge conflicts and requires you to clean them up, instead of attempting to be too magical.

**Comment by kevinushey** [comment]
This is specifically for `renv::init()`, though -- `snapshot()` will warn if you try to snapshot a broken library; e.g.

```
> renv::snapshot()
The following package(s) depend on packages which are not currently installed:

        dplyr: [tibble]

Consider re-installing these packages before snapshotting the lockfile.
```

We could be more strict there and just make it a hard error / require `force = TRUE` to snapshot in such a case.

**Comment by kevinushey** [comment]
The primary goal of `init()` is to help ensure that a newly-created project is in a 'good' state, and I think at least in that case it's a bit more reasonable to expect users will have the latest versions of CRAN packages installed and available (although it's still not a perfect assumption)
