### ISSUE TITLE
Using functions from a package utilizing renv at command line

### ISSUE THREAD

**Issue by bbecker0** [rstudio/renv#352]
Would using renv package be appropriate for this situation:

I write and export functions into a custom, internal R package that I maintain on my personal laptop and a linux server. I often schedule a lot of these functions to run via CRON and they ETL data often delivering data through SFTP (I use reticulate to call python's paramiko package).

Will calling such functions from my internal R package through command line/cron respect renv? Will calling these functions in different working directories cause my functions to not use the packages installed within the renv library path instead of system path? 

Using within RStudio projects sounds great, but I'd love to better manage my package dependencies but call outside of the project directory.

**Comment by kevinushey** [comment]
> Will calling such functions from my internal R package through command line/cron respect renv? Will calling these functions in different working directories cause my functions to not use the packages installed within the renv library path instead of system path?

It depends on how R is being launched. By default, `renv` uses a project `.Rprofile` to automatically load that same project (and so set project-local library paths).

If you aren't working with a specific project though, then you'll need to manually call `renv::load()` or similar, passing the appropriate project path -- so that `renv` works in the context of that project, even if called from a separate working directory.

Does that make sense? I'm not sure how much of `renv`'s extra functionality you require.

**Comment by bbecker0** [comment]
That does make sense and seems easy to work with.

I'm hoping renv will help with using reticulate and managing the R package dependencies while not clobbering my other R projects' dependencies.
