### ISSUE TITLE
`purge`: add ability to purge older packages

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#367]
As touched upon in #255 [comment]( https://github.com/rstudio/renv/issues/255#issuecomment-591846721), would be nice to be able to remove all older versions of the packages from the cache. 

Two options come to my mind:

-  utility which would return all old packages in the cache. Then the user could map over those with `purge`.

- A new function `purge_old(, exclude = ...)` with the ability to exclude specific package

**Comment by kevinushey** [comment]
What if the user has packages both from CRAN and GitHub (or other remote sources) in the cache? Should we keep the latest version from GitHub? Keep both, but only delete older CRAN packages?

For what it's worth, `renv` does have a currently un-exported helper called `renv_clean_cache()`. It works in the following way:

1. Whenever an `renv` project is loaded, the project directory is appended to a global project list located at `${RENV_PATHS_ROOT}/projects`.

2. We read that project file, and then enumerate the project libraries used by each project.

3. Any packages in the cache not referenced by one of those projects is eligible for removal.

I haven't decided if this is the right approach (especially since project locations may not be stable; e.g. if project directories are mounted, unmounted, moved, and so on) but it might be useful in your case.

**Comment by vspinu** [comment]
> Keep both, but only delete older CRAN packages?

 It should be all up to the user I believe. I think predefining a bunch of common scenarios and building it into the "old_cash_extractor" utility might be a way to go. 

> I haven't decided if this is the right approach

I think this is a sane and necessary option. The "old_package_extractor" can have an argument `project_paths` which would be inspected _recursively_ for projects and `1,2,3` steps above performed. It can default to `RENV_PATHS_ROOT`.

**Comment by Fuco1** [comment]
I think since this is only a cache and in principle it could be deleted every time and not affect anything except convenience, it's OK to err a bit on the side of deleting too much.  But with multiple versions of packages, the cache can grow really large which can be annoying when building in CI environments with cache store/restore taking substantial time.

I'd also welcome some simple even if not always "correct" way to make the cache smaller.  At minimum, removing regular old versions, like here:

![image](https://user-images.githubusercontent.com/2664959/232550429-23980fea-fd7e-45ba-93fd-40a51d9e9070.png)

**Comment by hadley** [comment]
Closing, since it's really hard to figure out exactly what directories to delete, and this problem overall is rather underspecified.
