### ISSUE TITLE
Are you sure github ssh key support is working?

### ISSUE THREAD

**Issue by iperks** [rstudio/renv#383]
At this staging this is perhaps more a question than an issue at this time so please treat it as such.

We have some private github repos that we would like to pull in (specific versions) into our main umbrella application.  If I export a `GITHUB_PAT` it seems to work fine but for some reason it doesn't work for github ssh keys and we get a 404, this is despite `git` on the command line working fine. Any advice?

Am pretty standard Ubuntu 18.04, using `asdf` to manage multiple versions of R in different projects

**Comment by kevinushey** [comment]
How were these packages installed?

`renv` always tries to retrieve packages from GitHub using `https://`, which is why I suspect this fails. However, if the package is explicitly configured with a `git` remote (as opposed to GitHub), then `renv` will attempt to retrieve the package using `git` and so (in theory) pre-existing SSH keys should be respected.

In case it's helpful, you can use:

```
renv:::renv_snapshot_description(package = <package>)
```

to get the package 'record' as understood by `renv`, and this should also include the inferred remote source.

**Comment by iperks** [comment]
Also `renv:::renv_snapshot_description(package = <package>)` just yields an error.

**Comment by iperks** [comment]
By way of an update the only way I've been able to access private github repos is to use both .ssh keys and the GITHUB_PAT.  I probably need to organize a better example to more cleanly understand what's going on.  With the build taking 15-20 minutes it's not really possible with the projects I'm looking at right now. Closing issue.

**Comment by matthewstrasiotto** [comment]
Hi. This has been closed for some time, but I was also experiencing inconsistent behaviours with ssh keys on **windows** vs other platforms for a good deal of time, and understanding why was a frustrating process.

Essentially, the problem came down to how Rstudio (or R itself, I'm not sure) sets its default home paths, and how this leads to confusion between what to configure and where. I explain what happens & why in depth at https://github.com/rstudio/renv/issues/424#issuecomment-792724374
