### ISSUE TITLE
Docker FAQ notes

### ISSUE THREAD

**Issue by iperks** [rstudio/renv#385]
I read with interest the [FAQ](https://rstudio.github.io/renv/articles/docker.html) on using `renv` with Docker, perhaps I should've read it before going through what I've gone through!

In our case one of the objectives in our use of Docker is to get a repeatable build process.  There  are obvious advantages in locking your operating system, R itself and the R packages to defined versions.  Assuming those things are stable then you can change your code and get a consistency in the behavior of the container as you, test fix bugs or make other improvements.

We do things a little different than is noted in your FAQ, our `Dockerfile` uses a multi-stage build such that we do the build work in one container which functionally takes a base OS (containing R) copies our `renv`-enabled app into it and runs `renv::restore()` on it.  `renv` will bootstrap itself to the version in the lockfile: that is useful behavior.  After the restore we run `renv::settings$use.cache(FALSE)` to copy the global cache into the local project.  There is probably a different way to do this but I don't believe that a global cache has much of a benefit in this case, I can't see the point in holding all the packages outside of the project folder in a Docker container.

Once the build container has done that we copy the app from the build container into a new one, add an entry point and that becomes our actual container which does the work.

There are downsides to this approach: you have to do a lot of work - and consume a lot of time - before you can figure out if you've got a working container.

Interested in any comments on this.

**Comment by kevinushey** [comment]
> After the restore we run renv::settings$use.cache(FALSE) to copy the global cache into the local project. There is probably a different way to do this but I don't believe that a global cache has much of a benefit in this case, I can't see the point in holding all the packages outside of the project folder in a Docker container.

FWIW, the more "official" way of doing this is to call `renv::isolate()`, but it effectively does the same thing under the hood.

> There is probably a different way to do this but I don't believe that a global cache has much of a benefit in this case, I can't see the point in holding all the packages outside of the project folder in a Docker container.

The main reason to consider this would be to allow multiple containers to re-use the same package cache. This should speed up the package installation process, since each container would be able to re-use the same cache of packages, even if different containers had varying (but occasionally overlapping) package requirements.

I think this is similar in spirit to your approach, though -- with a base 'image' (containing requisite packages) and containers that then use or overlay their own packages as required.

> There are downsides to this approach: you have to do a lot of work - and consume a lot of time - before you can figure out if you've got a working container.

At least in theory, one of the goals in `renv` + the Docker FAQ is that if you can verify you have a working application locally from a single entrypoint, then you should be able to get a working application in Docker using just `renv::restore()` + running that same entrypoint. Of course, in reality this doesn't always go so smoothly due to differences in system requirements that often need some smoothing out during install.

I'm not sure if there's a great solution to this, though -- ultimately the experience is similar to trying to get something to test and run on CI, and slowly iterating until things work there as well.

**Comment by jameshowison** [comment]
Here's a slightly different approach to using renv and Docker, storing the renv cache on a docker buildx cachemount:

https://github.com/howisonlab/test_repo_buildx_renv

Advantage as I see it is that containers are independent of the environment in which they are built, downside is that there is still a little overhead in copying the packages from the build cache into the project folder.  I eventually hope to get this working with a mybinder type setup.

**Comment by vspinu** [comment]
One way to piggyback on the docker caching would be to split `.renv.lock` into sub-modules. This [comment](https://github.com/rstudio/renv/issues/253#issuecomment-621077351) for more details.

**Comment by iperks** [comment]
> FWIW, the more "official" way of doing this is to call `renv::isolate()`, but it effectively does the same thing under the hood.

This worked as expected and is neater than the other approach, thansk!

**Comment by iperks** [comment]
I wonder how much of this is just a function that R only compiles and runs things on a single core - which is one of the reasons why R is dead to me as a language regardless of how good it is at doing anything else.
