### ISSUE TITLE
[question] how do I update renv.lock to R 4.0.0?

### ISSUE THREAD

**Issue by JodyStats** [rstudio/renv#405]
I got these warnings

```r
Warning message:
Project requested R version '3.6.3' but '4.0.0' is currently being used
```

When I `renv::install()`, it does not update R version of `renv.lock` file. What are the instructions for dealing with R version upgrade? I am lost.

**Comment by kevinushey** [comment]
If you call `renv::snapshot()`, the lockfile will be updated, with the version of R that you're currently using for the project. Is that sufficient?

**Comment by JodyStats** [comment]
That is sufficient. So version of R has minimal impact on how `renv` operates? In what circumstances do we need to pay attention to change of R version?

Thanks I am closing this.

**Comment by kevinushey** [comment]
Right, that's correct -- `renv` just warns you to indicate the R version has changed, just to confirm whether it was intentional or not. The version of R is later updated on the next call to `renv::snapshot()`.

The main thing to look out for is that, after an upgrade to a new version of R, you may need to reinstall any packages used in the project (e.g. after upgrading from R 3.6 to R 4.0).

**Comment by cjvanlissa** [comment]
Still interested in this issue, because after updating to R4, I had endless errors because none of my packages and their dependencies were available anymore. Don't think this is an renv issue - I think it's related to the major update - but it was extra painful having to manually reinstall hundreds of packages both in vanilla R and renv. Anything renv can do to make this less awful?

**Comment by kevinushey** [comment]
For an `renv` project at least, you should be able to just call `renv::restore()` to reinstall any necessary packages (as declared in the project lockfile).

You could also create a lockfile from your old R library path, and then restore based on that. For example, something like this could work:

```
renv::snapshot(
  library  = "~/r/win-library/3.6",
  lockfile = "r-36.lock",
  type     = "simple"
)

renv::restore(
  lockfile = "r-36.lock"
)
```

**Comment by cjvanlissa** [comment]
You should tweet that! It would have saved me 2 days of work, no kidding! I love this!

**Comment by cjvanlissa** [comment]
Actually - I'll tweet and tag you

**Comment by neverfox** [comment]
Hmm. When I called `renv::restore()` I just got told that `* The library is already synchronized with the lockfile.`
