### ISSUE TITLE
Rstudio permission denied

### ISSUE THREAD

**Issue by sharkdeng** [rstudio/renv#426]
I was trying to install rattle but had this problem.

```
Warning in install.packages :
  cannot create file '/usr/local/Cellar/r/3.6.3_1/lib/R/doc/html/packages.html', reason 'Permission denied'
Warning in install.packages :
  cannot update HTML package index
```

I used following lines to change folder permission
```
ls -ld /usr/local/Cellar
sudo chmod a+w /usr/local/Cellar
```
The folder permission is as follows:
`drwxrwxrwx  118 dph  admin  3776 Apr 23 00:40 /usr/local/Cellar`

But the problem still not solved. I suspect RStudio doesn't have the right to access the folder. Am I right? If so, how to change? Thanks

**Comment by kevinushey** [comment]
Sorry, but this doesn't seem to be an issue with `renv`. Are you sure you've filed this in the correct place?

In addition, you likely need to change permissions recursively rather than just on the `/usr/local/Cellar` folder. (Maybe you launched R as root some time ago, e.g. `sudo R`, and now some files in your R installation are owned by root)
