### ISSUE TITLE
hydrate() without updating packages

### ISSUE THREAD

**Issue by py9mrg** [rstudio/renv#469]
Not sure if I'm missing something obvious, but it seems to me there's no way to `hydrate()` a project without also updating packages from the main R library. I'll try to expand on that explanation as it might not be clear.

Let's say I am working on a project using renv for package management. I then switch to a non-project R session, do some basic stuff, update some packages (ones which happen to be used in the project I was working on), then go back to the project.

Now, let's say I now need some new packages in the project so write the necessary code and then call `hydrate()` to get them pulled in from my main R library. The problem is, when I do this, `hydrate()` also updates the existing packages in my project library with the updates from my main R library - which I might not want to do.

I realise I could avoid this by bringing in the new packages to the project using `renv::install()` instead, but then I have to manually type them out, whereas `hydrate()` is just so bloody convenient!

Unless I'm missing something, it would be great to include an option such as `hydrate(update = FALSE)` to only bring in new packages and avoid pulling in the updates from the main R library for other packages used.

Hopefully that makes sense??

**Comment by kevinushey** [comment]
There isn't an explicit API for this right now, but I think you could accomplish something "by hand" with something like:

```
packages <- unique(renv::dependencies()$Package)
missing <- setdiff(packages, rownames(installed.packages()))
renv::hydrate(missing)
```

Is this (or something similar) what you were looking for?

**Comment by py9mrg** [comment]
Yeah I think that should do for now. Thanks a lot.

**Comment by krlmlr** [comment]
I wonder if we could enhance `hydrate()` to respect `getOption("repos")` only, and perhaps report differences to the package libraries. I'm moving projects that I have set up with MRAN to renv -- the manual approach works but I wonder if this should work more intuitively.

**Comment by kevinushey** [comment]
Can you elaborate a bit more on what exactly you're looking? `hydrate()` basically does the following:

1. Infer your project's R package dependencies via `renv::dependencies()`,
2. Copy those packages into the global `renv` package cache,
3. Copy and / or link those packages into your project library,
4. Install packages from CRAN if they otherwise weren't available.

For step (4), packages should be installed from the package repositories as declare by `getOption("repos")`.

Are you saying that you only want step (4) here, and you want to avoid (1) through (3)? If that's the case then I think `renv::install()` might be the right solution.

**Comment by krlmlr** [comment]
I'm looking for step 1 and 4 plus a snapshot, omitting step 2 and 3; this can be achieved with

```r
packages <- unique(renv::dependencies()$Package)
missing <- setdiff(packages, rownames(installed.packages()))
available <- intersect(missing, rownames(available.packages()))
renv::install(available)
renv::snapshot()
```

I'm even more interested in the resulting lock file than in actually installing anything, because the next logical step is to test `renv::restore()` on an fresh clone. Is there an operation that adds required packages to the lock file without installing them? (For now I wouldn't mind installing rmarkdown manually for dependency discovery; maybe we could inline the relevant code here too?)

**Comment by krlmlr** [comment]
Maybe: `renv::hydrate(library = c(), install = FALSE)` ?

`library = c()` might work today, will check next time I hydrate; `install = FALSE` could be a useful addition?

**Comment by krlmlr** [comment]
Am I looking for `renv::record(renv::dependencies()$Package)` ? What if `renv::record()` just worked?

**Comment by kevinushey** [comment]
I think I got it. Ultimately, you want a function that can go from <list of packages> => renv lockfile. Is that right? (With the list of packages being inferred automatically from project dependencies, perhaps.)

Package version could be drawn from the specified library paths, or only from the active package repositories, or from a set of pre-defined requirements as well. Solving this the right way would require a proper dependency solver, but a good enough start would be to just take everything current on CRAN at the time of creation.

**Comment by krlmlr** [comment]
For my workflow I try to disregard the global package library as soon as renv gets involved. As soon as a project switches to renv, it is tied to a stable RSPM snapshot and should get all packages from there, no matter what I might have installed in the global package library (which I tend to keep up-to-date-ish).

For users who have very few (or just one) project they're working on and who want to switch to renv, the current implementation (=consulting the local library) is better, because this avoid surprises when switching to renv. My objective is to minimize the set of package universes I'm using across all my projects, this is more important than exact replication of the current state of the package library. I might install GitHub packages on a case-by-case basis.

Ideally, for starting use of renv in a particular project, I'd do a variant of:

- `init(bare = TRUE, repos = c(RSPM = "https://packagemanager.rstudio.com/all/301"))` (bare-bones infrastructure with empty library and repo pointing to latest snapshot I've used in other projects)
- `record()` (auto-detect and record dependencies)
- `restore()` (to check if `restore()` will work on my colleague's machines)
- Run tests on the project (to check if any problems arise from potentially different package versions)

From time to time, I'd lift a project to a more recent RSPM snapshot:

- Edit `renv.lock`
- `update()`

Does this make sense?
