### ISSUE TITLE
Allow installing a package from non-CRAN repositories

### ISSUE THREAD

**Issue by Kodiologist** [rstudio/renv#471]
For example, `rearthdata` requires `rnaturalearthhires` for some tasks, which is typically installed from rOpenSci with `install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")`, but if I use `install.packages` instead of `renv::install`, `renv::snapshot` seems unable to see the library.

Perhaps related: #449, concerning the installation of repositories from BitBucket.

**Comment by kevinushey** [comment]
If I understand the problem correctly, the issue here is that `install.packages()` does not record any information about which repository was actually used when a package was retrieved, and so `renv` has to assume the package is available from one of the "default" repositories.

The simplest fix would be to ensure that this repository is set before snapshot; e.g.

```
repos <- getOption("repos")
repos["rOpenSci"] <- "http://packages.ropensci.org"
options(repos = repos)
```

If this doesn't work, then I think I'll need to the actual commands you're running + the error output you're seeing to better understand the issue.

**Comment by Kodiologist** [comment]
I made that change to `options(repos = …)` and did `renv::install("rnaturalearthhires")`, which seemed to work, but the lockfile created by `renv::snapshot` claims I got the package from CRAN:

    "rnaturalearth": {
      "Package": "rnaturalearth",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "946d1b43d7aba91dfa804f02302a5125"
    },

**Comment by Kodiologist** [comment]
I made that change to `options(repos = …)` and did `renv::install("rnaturalearthhires")`, which seemed to work, but calling `renv::snapshot` doesn't add `rnaturalearthhires` to the lockfile (the output is `* The lockfile is already up to date.`; the new repository was added from a previous call, but not the package).

**Comment by kevinushey** [comment]
I believe this is ultimately because packages from the rOpenSci don't declare their repository, so `renv` is forced to guess and so assumes that it must be available from CRAN.

A fix for this on the rOpenSci side would be to tag packages with `Repository: rOpenSci` in the DESCRIPTION file for any packages shared from that repository. Alternatively, `renv` could try to be smarter and match package names against the repository "name" used for a particular package.

Can you share your `renv.lock`, just for posterity? Does manually adding the rOpenSci repository to the lockfile make a difference?

**Comment by Kodiologist** [comment]
Please see my new comment above.
Attachment: [renv.lock.zip](https://github.com/rstudio/renv/files/4886936/renv.lock.zip)

**Comment by kevinushey** [comment]
> but calling renv::snapshot doesn't add rnaturalearthhires to the lockfile

Is `rnaturalearthhires` used in your project? You might be bumping into https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile.

**Comment by Kodiologist** [comment]
Thanks, I forgot that the default snapshot type is "implicit". I added a `loadNamespace("rnaturalearthhires")` to my code and `snapshot` added it to the lockfile, but with "Repository" set to null instead of "rOpenSci".

    "rnaturalearthhires": {
      "Package": "rnaturalearthhires",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": null,
      "Hash": "8e3c805f7e88dd4ac696aacc6d792fdb"
    }

**Comment by kevinushey** [comment]
This seems correct to me: `rnaturalearthhires` doesn't declare the repository it came from, so `renv` can't know which repository it actually came from. However, it can infer it came from _a_ repository, at least.

We could augment `renv::install()` to tag installed packages with the repository that was actually used for install, but ultimately the "right" fix, I believe, is for the rOpenSci repository to tag these packages with `Repository: rOpenSci` or similar.

**Comment by Kodiologist** [comment]
Would you consider adding a `repos` argument to `renv::install`, like that of `install.packages`?

**Comment by kevinushey** [comment]
We could, but I don't think that would resolve the root issue here, would it?

**Comment by mstr3336** [comment]
As a workaround, for now, you're probably able to install `rnaturalearthhires` directly from an rOpenSci GH repo, as in: 
I found it here: https://github.com/ropensci/rnaturalearthhires

`renv::install("ropensci/rnaturalearthhires")`

**Comment by Kodiologist** [comment]
@kevinushey I'm not sure. It might make it easier for `renv` to tag the package with its repository.

@mstr3336 Thanks, that works.
