### ISSUE TITLE
Libraries not available after renv::init

### ISSUE THREAD

**Issue by DarylMcCullough** [rstudio/renv#475]
Suppose I create a new R project, and do renv::init() to record the state of the packages. Afterwards, if I type library(devtools) in the R console, I get an error saying there is no such library. library(devtools) works fine before renv::init()

This is sort of a big deal, because I have to use devtools::install_version in order to install an older version of a library.

**Comment by kevinushey** [comment]
`renv::init()` only brings in packages that appear to be used in the project, so if you don't have `library(devtools)` in any R code files for a project then it won't be brought in. You can always use:

```
renv::install("devtools")
```

to later install `devtools` so that it's available in the project post-hoc. Or, if you wanted to bring in the version of `devtools` in the user library, you could use:

```
renv::hydrate(packages = "devtools")
```

Note that you can also use `renv::install()` to install older versions of R packages; for example, to install version 0.6.24 of digest you could use:

```
renv::install("digest@0.6.24")
```

**Comment by DarylMcCullough** [comment]
The problem is that devtools is used during development, it's not a library used in the code being developed.

**Comment by kevinushey** [comment]
If I understand correctly, you want to be able to "activate" different R libraries, based on the context you're working in. If that's the case, you might want to call `renv::deactivate()` to disable `renv` in the project (thereby using the "global" library), and later call `renv::activate()` to activate the project libraries to use the project-specific library.

**Comment by DarylMcCullough** [comment]
Thanks!

**Comment by DarylMcCullough** [comment]
This is very frustrating.

I don't understand why not, but renv::Install fails to install a package which devtools::install_version succeeds in installing. Unfortunately, if I do renv::deactivate to allow devtools to be used, then devtools::install_version installs the package globally but NOT in my project (just the opposite of what I want).

**Comment by DarylMcCullough** [comment]
The only way I can make it work is to remove all the renv files and directories, use devtools::install_version to change to an older version of a package, then use renv::init(), then finally use renv::deactivate and then reinstall the latest version. Surely there's a better way.

**Comment by kevinushey** [comment]
> renv::Install fails to install a package which devtools::install_version succeeds in installing

Are you able to share the output you see after the installation failure?

For what it's worth, you could also use the `remotes` package directly, instead of `devtools`. Since `remotes` doesn't have any dependencies, it shouldn't be an issue to install that in your project library. So:

```
renv::activate()
install.packages("remotes")
remotes::install_version(...)
```

should also work.

**Comment by DarylMcCullough** [comment]
The error message is that it failed to compile a dependent package, because program "make" was not found. (Sorry I can't paste the exact message, but it was on another machine, and transferring data between the machines is difficult for company security reasons.)

I don't really understand the cause (I guess it found the source, but not the compiled version, and it can't find the program to compile it), but in any case, it works fine if outside of renv, I use devtools::install_version(). I don't understand why it works in one case and not the other.

**Comment by kevinushey** [comment]
> The error message is that it failed to compile a dependent package, because program "make" was not found.

This usually implies that `renv` tried to install the package from sources, but failed because R build tools either aren't available or R wasn't able to locate them.

You could also force `renv` (and R's own `install.packages()`) to always use binaries by setting:

```
options(pkgType = "binary")
```

Ultimately though, if you find that you can't get installation working with `renv` then using other tools (e.g. `remotes::install_version()`) should still be an option. To diagnose the issue in `renv`, I think I would need a reproducible example.

**Comment by DarylMcCullough** [comment]
Neither renv::install nor remotes::install_version() succeeds. Setting pkgType = "binary" doesn't seem to help; it still tries to compile code. Maybe there isn't a binary? I'm sorry that I'm unable to give a reproducible example. But I do note that outside of renv, devtools::install_version works fine. So I'm trying to understand why it doesn't work inside renv.

The only thing I can get to work is to just remove all renv files, install the desired versions of all packages, then use renv::init(). Of course, that ends up affecting all other projects, so I have to reinstall the original versions. It's horrible.

**Comment by DarylMcCullough** [comment]
I obviously do not understand how renv works, at all. I want one of my projects to have an older version of a package. Version 1.3.2 of shiny, rather than version 1.5.0. Having tried and failed to change the version within renv, I was reduced to changing it globally, then using renv::init(), then changing it back. That doesn't work, either!

In RStudio, in the console, I type packageVersion("shiny"), and it tells me 1.3.2. Good. Then I do renv::init(). Afterward, I type packageVersion("shiny") and it tells me 1.5.0.

For some reason, renv::init() picked the latest version, instead of the current version.

**Comment by DarylMcCullough** [comment]
Okay, so it looks like renv::init() always uses the latest available? And then I have to do renv::install to get an earlier version?

**Comment by kevinushey** [comment]
`renv::init()` basically tries to "fork" the state of your user library into a project library, copying only the packages that appear to be used in that project. I'm not sure why it would be finding the latest available version of Shiny in your case (unless this is some behavior around calling `renv::init()` in a project that's already been initialized)

**Comment by DarylMcCullough** [comment]
I don't know, but it's definitely the case that after using renv::init(), the version of "shiny" changed to the latest.
