### ISSUE TITLE
install and restore have not the same behavior on lockfile

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#50]
* `renv::install` will update the lockfile
* `renv::remove` will not update the lockfile

It may be intented but as I find it not consistent I wanted to raise a comment. I would have expected it to be the opposite of each other.

**Comment by kevinushey** [comment]
I'm curious why you expected the opposite: in my view, it makes sense for both actions to either perform an automatic snapshot, or neither. (The behavior can be controlled on a project-specific basis with `settings$auto.snapshot()`)

**Comment by cderv** [comment]
I may have been not clear by the choice of my english word ☺️ Opposite was not the correct work. 
I meant that _install_ and _remove_ should be the perfect "ying and yang" function
* _install_: install & snapshot
* _remove_: remove & snapshot
Then behavior on opposite actions 😄 
The change is now offering the beahvior I was expecting. I think we can close.

**Comment by slopp** [comment]
@kevinushey what is the default for `settings$auto.snapshot()`? Did we decide against?

**Comment by kevinushey** [comment]
It's enabled currently, and when enabled calls `snapshot()` after `install()` or `remove()`. I'm still on the fence on whether we want to leave it on.

Also perhaps worth saying that we'd need to think about cases like:

1. User loads `renv` project,
2. User installs package 'A' in a way not tracked by `renv` (lockfile is not updated),
3. User calls `renv::install("B")`.

When the automatic snapshot happens, should only `B` be updated in the lockfile? Or both `A` and `B`?

**Comment by slopp** [comment]
This feels really dangerous.  I think that snapshot should be called by the user, as a way to say "my project is now ready" instead of happening automatically. Why? We rely on the user committing the lockfile in order to successfully revert to a prior state. If we are snapshotting automatically (much more frequently than committing), a user could easily install a package, learn that it broke their code, but then not have any recourse to go back to the prior state because they had not recorded their happy state through a commit. snapshot + commit is a cleaner workflow that indicates when the environment is in a functional state - so I'd highly encourage us to set the default to off.  

We could add an argument to `renv::install` that does auto-snapshot for users who desire this behavior.  As an example, npm install originally included a --save flag which auto updated the packages.json, but did not update the json otherwise.

**Comment by cderv** [comment]
I see your point. The assumption here is also that a user will regularly save the state of its project by committing + snapshoting. In dev phase, I could see some people never snapshoting or saving state of their lockfile. If so, then discovering an issue later on would mean revert to a state never registered too. 

It is like this would mean a renv project is very close to a git project, and snapshot + commit is essential. either manually or if automatically snapshoting + commiting or printing a message to do so. 

Would it make sense to do nothing by default but inform after each installation and removal about the current status of the project ? 
like a reminder of don't forget to snapshot and commit if you're happy of your change.

**Comment by kevinushey** [comment]
Closing this issue since the original issue (be consistent in behavior with install / remove) is resolved; whether or not auto.snapshot should be enabled by default is still an open issue.
