### ISSUE TITLE
Many processes using same renv project in parallel

### ISSUE THREAD

**Issue by kdkavanagh** [rstudio/renv#525]
Curious if there is guidance on how to allow many processes to activate the same renv project at the same time?  At the moment, I'm getting nondeterministic failures when the different processes all try to update the shared project library at the same time.  

Is `renv::isolate` the correct solution for this usecase, or that + some combination of environment variables to give each process its own temporary project directory?

**Comment by kevinushey** [comment]
I think multiple processes can share the same project library, as long as they treat the library as read-only -- as soon as you start installing or updating the project library, you risk running into these sorts of issues. I don't think `renv::isolate()` helps here since ultimately the same library path is still shared by multiple processes.

We could in theory implement some sort of interprocess locking mechanism to prevent issues like this, though (only allow one process at a time to update the project library).

That said, I think another solution would be to just give each process its own project library; e.g. something like:

```
# create new private library as clone of existing project library
libdir <- tempfile("renv-library-")
renv:::renv_file_copy("renv/library", libdir)

# set the new library directory
Sys.setenv(RENV_PATHS_LIBRARY = libdir)
```

This could be done in the project `.Rprofile`, before running the `renv` autoloader. The problem there is that updates to the project library would not be visible within the "real" project library, though.

Can you expand a bit more on what exactly you want to do?

**Comment by kdkavanagh** [comment]
I think setting a process-specific library (w/o explicitly copying the src library) before activating the project seems to have done the trick.  I dont execute the script from the script's directory itself, thus I manually run `renv::activate(project_dir)` anyway, which makes this easy (vs putting it in .Rprofile)

My usecase is some HPC-style computing where I have many (1000s) of processes that all spin up at the ~same time using the same R installation/package library and each try to activate the same renv project off of that base R installation.  Because the renv project may have different deps than what is in the base installation, they all may try to update/install the same packages at the same time.

**Comment by kevinushey** [comment]
I've now implemented project locking in the development version of `renv`. You can set:

```
options(renv.config.locking.enabled = TRUE)
```

to enable project locks. When this is enabled, `renv` will "lock" the project when executing an API that requires access to the project library. If another process attempts to use a similar API at the same time, it will see the active lock and wait until the lock is released by the other process.

If you have a chance, please give it a spin and let me know if you run into any issues.
