### ISSUE TITLE
Cannot hydrate/install/init projects when located in the Google G: drive

### ISSUE THREAD

**Issue by py9mrg** [rstudio/renv#544]
My company is insisting we keep all our work in the G: drive provided by Google Drive File Stream. I know. I am now having some issues with renv copying packages into the project libraries - even with a completely fresh project.

For example, if I make a fresh project in the G: drive and use a package that should be pulled in by `hydrate`, then It seems to stall specifically when copying the files into the project library, with a blinking cursor until I kill it:

```
> renv::hydrate()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... 
```

I wondered if it's related to issue [#251](https://github.com/rstudio/renv/issues/251), as my cache is also in the normal C: drive location on Windows 10, but that seems to be fixed. When I move the project onto the C: drive, `hydrate` etc do work fine.

**EDIT**: actually if I leave it long enough it will work - but it's *extremely* slow. It is currently on 14/77 (gargle being hydrated) despite being left to run for around 10 mins.

**Comment by kevinushey** [comment]
For context, this is likely because on Windows you cannot have cross-drive junction points (ie: you cannot link from a project library on the `G:/` drive to a cache on the `C:/` drive). When this occurs, `renv` falls back to copying rather than symlinking, which is evidently very slow in this configuration.

The solutions here would be:

1. Move the cache to the `G:` drive; e.g. by setting `RENV_PATHS_CACHE = G:/path/to/renv/cache`; see `?renv::paths` for more details;

2. Disable the cache entirely, via e.g. `renv::settings$use.cache(FALSE)`, for the projects on the G:/ drive.

**Comment by py9mrg** [comment]
Ah ok, thanks - let's blame it on my company insisting on going all in with bloody G Suite.
