### ISSUE TITLE
Not the same path for renv cache between Rproj

### ISSUE THREAD

**Issue by ScaonE** [rstudio/renv#559]
**Sys infos**
Windows 7
R version 4.0.2 (2020-06-22)
[renv 0.12.0]

**Issue**
I have previously been working on other Rproj with R 4.0.2 + renv 0.12.0.
The corresponding renv cache directory lives here : C:\Users\FR_SCAERW\AppData\Local\renv\cache\v5\R-4.0\x86_64-w64-mingw32 (182 packages, including dplyr)

Today I initialize a dummy Rproj with R 4.0.2 + renv 0.12.0.
``` R
library(dplyr)
```
> Error in library(dplyr) : aucun package nommé ‘dplyr’ n'est trouvé

**Checks**
``` R
.libPaths()
```
> [1] "C:/Statistiques/RnD/Test_BC_2/renv/library/R-4.0/x86_64-w64-mingw32" 
> [2] "C:/Users/FR_SCAERW/AppData/Local/Temp/Rtmp4kRhmp/renv-system-library"

``` R
renv::paths$library()
```
> [1] "C:/Statistiques/RnD/Test_BC_2/renv/library/R-4.0/x86_64-w64-mingw32"

``` R
renv::paths$cache()
```
> [1] "C:/Users/FR_SCAERW/AppData/Local/renv/cache/v5/R-4.0/x86_64-w64-mingw32"

``` R
Sys.getenv("RENV_PATHS_CACHE")
```
> [1] ""

I assumed that with renv, my .libPath() should contain both what's returned by renv::paths$library() & renv::paths$cache(). But it seems that renv created a new directory for the cache (should't it point to existing cache directory for this R version ?)

**Comment by kevinushey** [comment]
This looks like the expected behavior to me: both projects have the same cache path, but each has their own unique library paths.

> I assumed that with renv, my .libPath() should contain both what's returned by renv::paths$library() & renv::paths$cache().

This isn't the case -- `.libPaths()` should only include the project library path, plus the system library path. (and other library paths that users might optionally choose to include)

The global package cache is a separate entity that `renv` uses when populating project library paths, during install or restore.
