### ISSUE TITLE
lockfile example issue

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/renv#568]
The `lockfile()` example is not run, so there is a subtle issue that gets through the checks.  Since the function is not exported, [this example](https://github.com/rstudio/renv/blob/master/R/lockfile-api.R#L109) doesn't work:

```
lock <- lockfile("renv.lock")
```

I believe it should be:
```
lock <- renv:::lockfile("renv.lock")
```

I'm happy to submit a PR for this if you're open to it.

**Comment by kevinushey** [comment]
The `lockfile` function is intentionally un-exported as it's not really fully-baked and ready for regular use.

**Comment by bhogan-mitre** [comment]
Thanks.  I have found that helpful a couple times, for example to adjust the repositories.  I think there is value there and just wanted to point out that disconnect in the man file when I came across it.  I'm sure there's a reason it's un-exported for now.

**Comment by statnmap** [comment]
Would you consider `lockfile()` to be ready for regular use and export it now ?  
I'd like to use it in some packages like {attachment} or {golem} where we want to give the possibility to fully integrate {renv} in package development workflows.
Otherwise, we'll continue using `getFromNamespace()`, and that is also acceptable to us :smiley:
