### ISSUE TITLE
renv::status() queries dependencies and sanity of package cache

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#570]
According to [`?status`](https://rstudio.github.io/renv/reference/status.html), its job is to

> Report differences between the project's lockfile and the current state of the project's library (if any).

Both actions take too long in our use case. There's no progress, R just appears to hang. We have `snapshot.type: all` in our `settings.dcf` .

- Querying dependencies takes too much time when renv is used in a large monorepo or in `~` . We can work around the enumeration of dependencies by adding `*` to `.renvignore` . 

- Checking the R package cache in `renv_status_check_cache()` takes too much time if the cache is on a network drive. There seems to be no workaround.

Questions:

- Why are we querying dependencies?

- Would you be open to check the cache only in a dedicated `cache_status()` function, or to add a `cache = FALSE` (or even `cache = TRUE`) argument to `status()`?

CC @pat-s.

**Comment by kevinushey** [comment]
Thanks! Both issues should be fixed in https://github.com/rstudio/renv/commit/7db47ef454b3c1623cdb60e3dc0c8654c23a6cd4.

> Why are we querying dependencies?

Looks like this was an unintentional oversight: this would be necessary when using "implicit" snapshots, but not in your case.

> Would you be open to check the cache only in a dedicated cache_status() function, or to add a cache = FALSE (or even cache = TRUE) argument to status()?

I would! I made that change in https://github.com/rstudio/renv/commit/7db47ef454b3c1623cdb60e3dc0c8654c23a6cd4.
