### ISSUE TITLE
renv not preserving options(repos) in user .Rprofile

### ISSUE THREAD

**Issue by brianrepko** [rstudio/renv#589]
Setup
* renv 0.12.3 on R 3.6.1
* ~/.Renviron - sets env vars for corp proxies (all projects)
* ~/.Rprofile - add a WORK repo to options(repos)
```
local({
  r <- getOption("repos")
  r["WORK"] <- "https://repo.example.com/CRAN"
  options(repos = r)
})
```
* <project>/.env - set project-specific env vars
```
RENV_PATHS_LIBRARY_ROOT=~/.renv/library/data
RENV_CONFIG_USER_PROFILE=TRUE
```
* <project>/.Rprofile - renv activation and pickup of .env
```
suppressWarnings(readRenviron(".env"))
source("renv/activate.R")
```

Expects
* renv activation will run both ~/.Rprofile and <project>/.Rprofile
* WORK repo will be included in the set of repositories

Output
* renv activation runs twice
* WORK repo is not included

**Comment by brianrepko** [comment]
Also tried this with `RENV_CONFIG_USER_PROFILE` line removed (so back to default of FALSE) and moved the code to add the WORK repository to <project>/.Rprofile - both before activation and after.

I'm still getting the same output - activation runs twice and WORK repo is not included.

**Comment by kevinushey** [comment]
I suspect this is because when the project is opened, `renv` applies the repositories encoded in the lockfile, overwriting any changes that might've been made within any `.Rprofile` scripts.

If that's indeed the case, then the solution should be:

1. Manually set the repositories you want, e.g. via `options(repos = c(...))`,
2. Invoke `renv::snapshot()` to update those repositories in the lockfile,
3. Restart R.

I'm also not able to reproduce your case with the `renv` activation script running twice -- I would need more information to confirm.

**Comment by brianrepko** [comment]
Hi @kevinushey - thanks for this.

I get it now - I added the repository to the renv.lock file and now it is there. This is actually best.
I just wasn't expecting renv to complete setup options("repos") but it makes sense that it does.
I was thinking it would append.

I was also looking at this in R vs RStudio to see about the "double activation" and it only happens with RStudio.
So I'm not so worried about it. Might be something about how RStudio starts the session when you open the project.
Anyway, I'll close this - thanks for the reply.
