### ISSUE TITLE
Renv assumes CRAN-like placement for older versions of package

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/renv#595]
Related to https://github.com/rstudio/renv/issues/209

We're using the Nexus Package Manager for internal R-package-repositories. The Nexus package manager implements the minimum requirements for a R-repository, but does not place older versions in contrib/Archive, as is the case with CRAN. Instead, all versions are placed in /scr/contrib

Thus, installation of older versions with renv::install fails:

```r
install.packages("internalpackage@3.0.0")

Retrieving 'https://nexus/repository/internal/src/contrib/Archive/internalpackage/internalpackage_3.0.0.tar.gz' ...
Error: failed to retrieve package 'internalpackage'
In addition: Warning messages:
1: curl: (22) The requested URL returned error: 404 Not Found 
```

As per https://issues.sonatype.org/browse/NEXUS-25130, a "monkey-patch" has been suggested by the Nexus community:
``` r
library(renv)

# see: https://github.com/rstudio/renv/blob/master/R/retrieve.R 
utils::assignInNamespace(
  "renv_retrieve_repos_archive", 
  function(record) 
  {
    name <- sprintf("%s_%s.tar.gz", record$Package, record$Version)
    for (repo in getOption("repos")) {
      archive_repo <- file.path(repo, "src/contrib/Archive", record$Package)
      status <- renv:::catch(renv:::renv_retrieve_repos_impl(record, "source", name, archive_repo))
    
      if (identical(status, TRUE))
        return(TRUE)

      nxrm3_repo <- file.path(repo, "src/contrib")
      status <- renv:::catch(renv:::renv_retrieve_repos_impl(record, "source", name, nxrm3_repo))
      if (identical(status, TRUE))
        return(TRUE)
      }  
      return(FALSE)
  }, 
  "renv")
```

Since contrib/Archive is not a requirement for R-repositories per se, could this hard-coded logic be changed (https://github.com/rstudio/renv/blob/ff7aa1ed8de5b48cb1138ee567029eeb9a6fe1bd/R/retrieve.R#L529)?

Thank you

**Comment by kevinushey** [comment]
My understanding is that this should already "just work", assuming that the repository's PACKAGES index file is correctly populated. For such a configuration, Nexus would need to use:

```
tools::write_PACKAGES(..., latestOnly = FALSE)
```

to ensure that the PACKAGES index includes all packages located in the `src/contrib` folder. Are you able to confirm if that's the case?

**Comment by johanneswaage** [comment]
Indeed you’re right, and this has been brought up on the Nexus GitHub issues page. Seems we have to wait for a fix on Nexus’ side.

**Comment by kevinushey** [comment]
(FWIW I'm still open to implementing a similar workaround in `renv` if it seems unlikely that this would get fixed timely on the Nexus side)

**Comment by kevinushey** [comment]
Is there a public Nexus repository that I could try to test with?

**Comment by kevinushey** [comment]
You can also give https://github.com/rstudio/renv/commit/8e342ffe6fb918f86c748a4d218527a01f7a828d a try and let me know if that seems to help.

**Comment by griverorz** [comment]
Unfortunately, I don't know of a public Nexus repository. I just tested `0.15.4-28` in a private one and it works seamlessly. Thank you for your extremely prompt response!

**Comment by kevinushey** [comment]
That's great to hear. Thanks!

I'll try to prepare a CRAN release of `renv` soon.

**Comment by arnauddeblic** [comment]
Dear @kevinushey,
First, thanks for your very usefull package 'renv'.
I saw what you did concerning Nexus and archived packages (issue #595).
I understand this workaround is designed to work for older versions of "source" packages.
Would it be possible to develop such a workaround for old "binary" packages ?
Basically, to have a function like "renv_retrieve_repos_archive_path", which would aim at finding an older binary package based on its caracteritics (name, version, etc)...
I know that MRAN functionnality aims at retrieving older versions of binary packages, but I cannot use it in my company's context (access to CRAN and MRAN via Nexus, but no access to https://rstudio-buildtools.s3.amazonaws.com/renv/mran/packages.rds because of firewall..)
From what I undersandn the following methods are tested in this order - until one succeeds :
1. renv_retrieve_repos_binary (when binary explicitly requested by user)
2. renv_retrieve_repos_mran (when binary explicitly requested by user and mran enabled)
3. renv_retrieve_repos_source
4. renv_retrieve_repos_archive
The idea would be to introduce a step between step 1 and step 2, some kind of renv_retrieve_repos_binry_archive function, that would try to download an older binary that Nexus has stored, despite it is no longer in PACKAGES.gz (which only contains latest versions).
Do you think such implementation would be possible ?
Please contact me if you need more details on my requested
In advance many thanks
Kind regards
Arnaud

**Comment by kevinushey** [comment]
I could add something like that if you can tell me the format you plan to use for binary packages within the archive -- e.g. given a package name + version, how can I find the archived version of a binary?

**Comment by arnauddeblic** [comment]
Many thanks @kevinushey for your very quick and positive answer !

To make it simple, Nexus (aka Nexus Repository Manager, by Sonatype) is deployed by my IT teams on our company's servers.
Nexus aims at achieving two main goals:
* **Proxifying** external repositories (such as CRAN)
* **Storing** persistently packages downloaded from these repositories, for future usage (cache functionality).

In the Rprofile.site we deploy on our machines, the repository is set using the Nexus root URL for R repository (miror of CRAN). Thanks to this configuration:
* When I install an R package that nobody in my company has already installed (same package, same version, same type, architecture if binary, etc), Nexus downloads it from CRAN, serves it to me and stores it for future usage
* Afterwards, when a colleague (or myself from another machine) tries to install it, Nexus serves the package it has already stored internally.

The **architecture** of Nexus storage is **the same as the original CRAN repository**. For example :
* R source packages will be stored in /src/contrib/<PACKAGE_NAME>_<PACKAGE_VERSION>.tar.gz
* R windows binary packages will be stored in /bin/windows/contrib/<R_VERSION_X.Y>/<PACKAGE_NAME>_<PACKAGE_VERSION>.zip
* and so on.

The **main difference** with CRAN is that **older versions are kept**, and still available thanks to Nexus internal storage functionality.

### Binary packages

Here is an example for binary package `rlang` in my Nexus architecture:
```
___ bin
    |___ windows
         |___ contrib
              |___ 4.1
                   |___ rlang_1.0.3.zip
                   |___ rlang_1.0.4.zip
                   |___ rlang_1.0.5.zip
                   |___ PACKAGES
                   |___ PACKAGES.gz		 
                   |___ PACKAGES.rds
```
As said above, older versions are still available for download, even if they are not explicitly listed in PACKAGES.gz (which only includes latest version since it is the proxyfied version of CRAN’s PACKAGES.gz file):
```
Package: rlang
Version: 1.0.5
Depends: R (>= 3.4.0)
Imports: utils
Suggests: cli (>= 3.1.0), covr, crayon, fs, glue, knitr, magrittr,
        methods, pillar, rmarkdown, stats, testthat (>= 3.0.0), tibble,
        usethis, vctrs (>= 0.2.3), withr
License: MIT + file LICENSE
```
The idea would be to determine the theoretical URL and try such URL when restoring the project, if the requested package is not explicitly listed in PACKAGES.gz.
In our example, if the renv.lock file contains the record `rlang@1.0.4`, we should try URL bin/windows/contrib/4.1/rlang_1.0.4.zip.

### Source packages

The same idea could also be used for source packages, in order to take advantage of Nexus storage functionnality.
Here is an example for source package `rlang` in my Nexus architecture:

```
___ src
    |___ contrib
         |___ rlang_1.0.3.tar.gz
         |___ rlang_1.0.4.tar.gz
         |___ rlang_1.0.5.tar.gz
         |___ PACKAGES
         |___ PACKAGES.gz		 
         |___ PACKAGES.rds
```
Again, older versions are still available for download, even if they are not explicitly listed in PACKAGES.gz (which only includes latest version since it is the proxyfied version of CRAN’s PACKAGES.gz file):
```
Package: rlang
Version: 1.0.5
Depends: R (>= 3.4.0)
Imports: utils
Suggests: cli (>= 3.1.0), covr, crayon, fs, glue, knitr, magrittr,
        methods, pillar, rmarkdown, stats, testthat (>= 3.0.0), tibble,
        usethis, vctrs (>= 0.2.3), withr
Enhances: winch
License: MIT + file LICENSE
MD5sum: 0419b9b94b400f3ec1f2792ab7f228e2
NeedsCompilation: yes
```
I saw the code you wrote retrieve.R file, for `renv_retrieve_repos_archive_path()` function.
I understand (but not 100% sure) that when requested package is neither in binary PACKAGES.gz file nor in source PACKAGES.gz, this function:
* [first tries to find](https://github.com/rstudio/renv/blob/b27db509dfb3740861bd8d7e4d8d06f4ca998eb4/R/retrieve.R#L756) the package "src/contrib/Archive/<PACKAGE_NAME>/"
* [then](https://github.com/rstudio/renv/blob/b27db509dfb3740861bd8d7e4d8d06f4ca998eb4/R/retrieve.R#L767) in "src/contrib/" (to deal with initial request hereabove).

(If voluntary ignore the [step](https://github.com/rstudio/renv/blob/b27db509dfb3740861bd8d7e4d8d06f4ca998eb4/R/retrieve.R#L761) related to issue #602, to keep this post as simple as possible !)

If the package has been moved to Archive subfolder in CRAN, Nexus will download it and store it with the same architecture, in folder "src/contrib/Archive/<PACKAGE_NAME>/".

At the end of the day, the same source package will be duplicated in Nexus storage : both in "src/contrib/" (initial download) and in "src/contrib/Archive/<PACKAGE_NAME>/" (second download, when package is moved to Archive in CRAN) :
```
___ src
    |___ contrib
         |___ Archive
              |___ rlang
                   |___ rlang_1.0.3.tar.gz          # redudant storage since already available
                   |___ rlang_1.0.4.tar.gz          # in Nexus outside of Archive folder
         |___ rlang_1.0.3.tar.gz
         |___ rlang_1.0.4.tar.gz
         |___ rlang_1.0.5.tar.gz
         |___ PACKAGES
         |___ PACKAGES.gz		 
         |___ PACKAGES.rds
```
If we could avoid this, this would prevent from unnecessarily increase the storage volumetry.
For Nexus’like configurations, I would suggest to try first in "src/contrib/", and then in "src/contrib/Archive/<PACKAGE_NAME>/".

### Conclusion

To put in a nutshell, my suggested sequence would be :

1. renv_retrieve_repos_binary (when binary explicitly requested by user)
2. renv_retrieve_repos_binary_older (when binary explicitly requested by user) – **new step**
3. renv_retrieve_repos_mran (when binary explicitly requested by user and MRAN enabled)
4. renv_retrieve_repos_source
5. renv_retrieve_repos_source_older – **new step**
6. renv_retrieve_repos_archive

I don't know if repository managers like Nexus are largely used by R users. If you don't want to systematically try oldest versions, a user-level configuration to trigger steps 2 and 5 could make sense:
For instance, using a new option `renv.config.retrieve.try.older` (or `RENV_CONFIG_RETRIEVE_TRY_OLDER` as  environment variable), with default to `FALSE`.

Would you have any question, please contact me.
And if you prefer that I create an new issue on Github, please tell me.
Kind regards
Arnaud

**Comment by kevinushey** [comment]
Thanks for the extensive write-up! I've copied that to a new issue at https://github.com/rstudio/renv/issues/1074.

I think the original issue in this thread should be resolved, so I'll close it and we can follow up in https://github.com/rstudio/renv/issues/1074. Thanks!
