### ISSUE TITLE
activate.R installs file from source; option for install from binary

### ISSUE THREAD

**Issue by dhbrand** [rstudio/renv#616]
Hi, I have an issue where I cannot successfully use renv without editing the activate.R file. I'm running Windows Server 2016 and my renv/git/Rstudio project is saved on a networked location. We are not able to install any packages from source per our IT restraints. I've seen the upgrades to renv which allows for the use of MRAN, something we rely on. I do not understand why the activate.R still tries to bootstrap and download/install a source file from CRAN even with an MRAN repo set in the lock file and all options related to package installation: pkgType = 'binary' and install.from.source = 'never', etc setup to not allow source packages. Is there an option I'm not understanding correctly or does the bootstrap process always rely on download and install from source?

**Comment by kevinushey** [comment]
> Is there an option I'm not understanding correctly or does the bootstrap process always rely on download and install from source?

The latter -- this is because the `activate.R` bootstrap script bundles only the scripts necessary to install `renv` as retrieved from a package repository; it does not know how to install `renv` itself from binaries via MRAN.

More specifically, here:

https://github.com/rstudio/renv/blob/460391a790bb00e77cf0dcfff275a661e8996900/R/bootstrap.R#L103-L111

When `type = "both"`, R still prefers downloading a source package. We should try to install binaries here as well.

**Comment by dhbrand** [comment]
Just to make sure I understand correctly, if `getOption('pkgType') = 'binary'` then R would install the binary for the requested version of the package. Unless requesting the current release (or commonly one back) from CRAN then an old version of renv would come from the archive and therefore install from source. Is it possible to adapt the mran.R script to find historical versions of renv using binaries with pkgType is binary?  Would this be a feature/enhancement request? Thanks.

**Comment by hadley** [comment]
This seems somewhat academic now that MRAN is going away.
