### ISSUE TITLE
FR: distinguish between runtime and developer packages

### ISSUE THREAD

**Issue by d-sci** [rstudio/renv#624]
This has been a recurring struggle for me since I've started to use renv.

My project/package needs, say:
- data.table
- DBI
- lubridate

But to do any work on it I inevitably need:
- devtools
- testthat
- roxygen2
- styler
- lintr

If I'm using my `renv.lock`, say, to create a Docker image to deploy the application, I really only want to include the runtime dependencies, in particular because `devtools` brings along an enormous chain of recursive dependencies that bloat the image. But if I don't include devtools et al in the lockfile, then, well ... my project library won't have devtools after`renv::restore()`. Even if I manually `renv::install()` (but don't record) it, I'd have to tell everyone else working on my project to do that to, and we wouldn't necessarily have the same version of everything, thus leading to spurious changes in e.g. test behaviour (testthat 2 vs 3), documentation files (roxygen 6 vs 7), etc.

Do you think it would be possible to record both types of packages, but somehow in different tiers -- something like `[packages]` vs `[dev-packages]` in Pipenv?

(And if not -- might you have any wisdom?)

**Comment by kevinushey** [comment]
Thanks for the issue -- I've been thinking about this as well.

What do you think is the "right" way to declare to `renv` that a particular package is a "development" package? In general, is there a way to indicate that a particular package belongs to some "class" of packages, and should be tagged as such? What's the best way for a user to encode this in their project? (since IIUC for a package to be categorized in this way, the user needs to explicitly tell `renv` what class a particular package belongs in)

One possibility would be for the user to encode this in the package `DESCRIPTION` file in some way; e.g. something like:

```
Config/renv/packages/development: devtools, testthat, roxygen2, styler
```

but I'm open to other thoughts or suggestions.

**Comment by jeffkeller87** [comment]
I have had the same desire dating back to the `packrat` days, but never really knew what it might look like until I (recently) started working with Pipenv.

One thing that I think can be done better than Pipenv, is to support arbitrary tags, rather than just dev and non-dev. This would allow more complex projects to more efficiently manage the installation of packages. E.g., a project comprised of numerous "jobs" that each requires only a subset of the packages recorded in the `renv.lock` manifest. One project might have these tags corresponding with different tasks/activities:

* `data-processing`
* `model-training`
* `shiny`
* `plumber`
* `packaging`
*  `dev`
* `etljob1`
* `etljob2`
* ...

I don't know of _the best way_ to encode this information, but here is what came to mind:

* An array of tags per package is encoded in `renv.lock`
* `renv::record` gets a new, optional parameter `tags` to accept a character vector of tags
* `renv::restore` gets a new, optional parameter `tags` to accept a character vector of tags to restore. Ultimately this behaves similarly to the `packages` argument, and in a way, may just be a new interface to the `packages` argument.
* Maybe some other utility functions to hydrate _and tag_ a selection of files/directories, to make tagging easier

```json
"shiny": {
    "Package": "shiny",
    "Version": "1.6.0",
    "Source": "Repository",
    "Repository": "CRAN",
    "tags": ["shiny", "dev"],
    "Hash": "5c0cdb37f063c58cdab3c7e9fbb8bd2c"
}
```

A key bit about the `tags` argument to `renv::restore` is that I can specify multiple tags for which to restore packages. If no tags are provided, all dependencies are restored as usual.

Dependency resolution obviously needs to be sophisticated enough to identify appropriate tagging for dependencies. This

```r
renv::record("shiny", tags = c("shiny"))
```
would also need to tag all of `shiny`'s dependencies with `"shiny"`, currently:

Rcpp R6 rlang BH later magrittr promises httpuv mime jsonlite xtable digest base64enc htmltools sourcetools crayon fastmap withr commonmark glue fs rappdirs sass jquerylib bslib cachem ellipsis lifecycle

**Comment by d-sci** [comment]
I don't have any brilliant ideas at the moment, but encoding in the `DESCRIPTION` file makes sense to me. I almost wonder if `Config/renv/packages/development` is even necessary; although it's not the exact same purpose, I imagine you'd basically be putting the same packages here as in `Suggests`, so you could perhaps just use that. 

Probably the main thing to think through is how to make`snapshot()` "just work" with the various different snapshot types (and the `package.dependency.fields` option?). I think the general logic would roughly be: "include whatever you were going to include in the lockfile, but if it's in`Suggests` (or `Config/renv/whatever`), or it's a strong dependency of something there and not also something else, mark it as a "dev-package".  `record()` could perhaps just gain an explicit like a boolean `dev` argument.

`restore()` would of course have a boolean `dev` argument. In the lockfile itself, we already have top-level sections `"R"` and `"Packages"` so it'd be easy to just add `"Dev-Packages"`.  Of course that would be more complicated if you allow arbitrary tags as per Jeff's idea.

**Comment by kevinushey** [comment]
I've started exploring a slightly different approach in this PR:

https://github.com/rstudio/renv/pull/626

Basically, this introduces the notion of different "profiles" in a project, which can each have their own disparate libraries + lockfiles. The intention is that you can use and switch profiles based on the "mode" you want to develop in.

It still requires the user to maintain separate libraries + lockfiles (and I need to think about how this plays together with automatic dependency discovery) but overall I think this is a relatively clean + ergonomic solution.

**Comment by d-sci** [comment]
Awesome! If there are separate lockfiles/libraries, would there be some mechanism to ensure that any packages appearing in multiple "profiles" have the same version?

**Comment by kevinushey** [comment]
We could in theory introduce the notion of "inheritance", so that one lockfile could be viewed as a layer on top of another lockfile, but that introduces a number of other challenges. Mainly around reconciling the differences between the project libraries for each profile in that case.

For that to work "cleanly" I think the user would have to opt into a mechanism where they define which packages go into the lockfile, as opposed to inferring the appropriate versions from the project library.

**Comment by mik3y64** [comment]
> We could in theory introduce the notion of "inheritance", so that one lockfile could be viewed as a layer on top of another lockfile, but that introduces a number of other challenges. Mainly around reconciling the differences between the project libraries for each profile in that case.
> 
> For that to work "cleanly" I think the user would have to opt into a mechanism where they define which packages go into the lockfile, as opposed to inferring the appropriate versions from the project library.

Hi @kevinushey I am all for this notion "inheritance". It is nice for users to define dev packages "on top" of certain profiles. Example of a very common use case "production" profile + "dev" profile.

"Main/production" profile
* DBI

"Dev" profile
* devtools

To manage the "dev" profile, I'd like to do just, for example
* `renv::activate(profile = "dev")`
* `renv::install("devtools")`
* Declare `Config/renv/profiles/dev/dependencies: devtools` in description

This "dev" profile sits on top of "main/production" profile. Thus, it is easier to add "dev" packages "on top" of existing profile. It means the "Dev" profile contains

"Dev" profile
* DBI
* devtools

**Comment by hadley** [comment]
We believe that add inheritance to profiles is likely to be too much work given the expected gain. You might instead try a tool like https://github.com/MilesMcBain/capsule.
