### ISSUE TITLE
Error: install of package 'tibble' failed

### ISSUE THREAD

**Issue by jdrengifoc** [rstudio/renv#625]
I create a project and init renv. Then I tried to install ggplot but appeared the following error.
Error: install of package 'tibble' failed
If i uninstall renv the installation procedes properly.
![imagen](https://user-images.githubusercontent.com/41349362/106343094-b4dad980-6271-11eb-8d1b-82a8f75b50db.png)

**Comment by kevinushey** [comment]
Can you please also provide the output of `sessionInfo()`? What do you see if you run `utils::install.packages("tibble")`?

It looks like `tibble` was just updated on CRAN so you might need to wait until binaries are available. Alternatively, you an set:

```
options(pkgType = "binary")
```

to force `renv` to install the latest binary rather than from sources.

**Comment by jdrengifoc** [comment]
@kevinushey When I enter `sessionInfo()` the output is the following.
![imagen](https://user-images.githubusercontent.com/41349362/106346864-20c83c80-6288-11eb-8481-a907d18bdca4.png)
With `utils::install.packages("tibble")`, the installation was made successfully. Then I procced to install ggplot2 and all seems to look fine. Thank you very much for your quick response.
