### ISSUE TITLE
dealing with Suggest dependencies

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#66]
How Suggest dependencies of a package are dealt with ? 

I am currently giving a try to renv for a presentation project with xaringan. There is a function call `inf_mr` which can use is installed the `rstudioapi`
```r
  if (missing(moon) && requireNamespace('rstudioapi', quietly = TRUE)) {
```
So I need to install it in the renv project. 

However, it is find into `renv::clean()` because not seen as a :package: I used.
```r
The following packages are installed in the project library,
but appear to be no longer used in your project.

	rstudioapi

These packages will be removed.
```

I believe it is not seen as a dependency of xaringan even it is in [Suggest field](https://github.com/yihui/xaringan/blob/83b76f7ee164106dd70dffedc394f8668bd20584/DESCRIPTION#L35)

Not sure what should be done here...

**Comment by kevinushey** [comment]
"Suggests" are indeed not included in the dependency lookup by default; mainly out of worry that it could lead to more packages used in a project than are truly used.

The simplest workaround would be to create a file called `deps.R` and add `library(rstudioapi)` there. I'll need to think a bit about whether there's a cleaner overall solution to the problem, though.

**Comment by cderv** [comment]
Thanks. That is indeed a nice workaround. 
It makes me see this as a more generalize way of handling manual dependency. How to to go above renv and add packages that go against renv automatic mechanism. 

I would see that as way to make some exception that renv would know about, would continue to remind me they exist but do nothing about in its automatic behavior. 

The `deps.R` file you are suggesting could also be a project DESCRIPTION. I believe renv knows how to deal with it.

**Comment by kevinushey** [comment]
I believe @hadley has mentioned in the past that he feels that the DESCRIPTION file is the right place to declare package dependencies as well, even outside of R package projects. It might be nice to outline what such a DESCRIPTION file would look like.

**Comment by cderv** [comment]
I agree with this feeling.

I already use a DESCRIPTION file to declare dependencies sometime and easily install them if I moved the project or for deployment, using `remotes::install_deps()`, that parses the DESCRIPTION.

I use a dummy field `Type: Project` or `Type: Shinyapp`, different than `Type: Package`. 
The other fields are as useful as for a package to document the project (who, Title, Description, Import, Suggest, ...)

The "power" of the DESCRIPTION depends also on the tool that is used to parse it. 
In all case, I agree that this feels the standard way to declare dependencies and store metadata on the project.

**Comment by cboettig** [comment]
:+1: I also use DESCRIPTION files to list dependencies in lightweight projects, e.g. like so: https://github.com/ds421/climate-template/blob/master/DESCRIPTION.  `renv` would still work since there are still `library` calls for those (i.e. like @cderv I use `remotes::install_deps()` and then load these as normal in the package), but I agree with @hadley that a DESCRIPTION is a natural way to collect package dependencies.  (among other things, it tends to play nicely with travis, and `remotes`/`devtools` tooling understands the `Remotes:` field in a DESCRIPTION which is convenient for GitHub dependencies, which `renv` may mistake for merely "local" packages with no identified source if all it finds is a `library()` call for them. So it would be great if `renv` could also just parse the DESCRIPTION (including `Remotes:` field) for dependencies of any form.

**Comment by kevinushey** [comment]
`renv` now has machinery for installing packages as declared in a `DESCRIPTION` file. If you run:

```
renv::install()
```

within the root directory of a project that contains a `DESCRIPTION` file, the packages and Remotes within will be parsed and installed in the project.
