### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/renv#70]
Hi,

We are using RStudio Package Manager, but were unable to install a new local package from it because the renv cache did not update automatically and only contained the old version of the package.
It seems like the cache is updated every hour, so instead of waiting we had to go to following location and deleting the cache files by hand.
/home/xxx/.local/share/renv/repos/R-3.5/x86_64-redhat-linux-gnu/

What would be a good solution for us to be able to use renv and the Package Manager when we update it with new package versions frequently?

Thanks,
Martin

**Comment by slopp** [comment]
@mac-pfa  I'm not sure I follow your question, the renv cache will maintain multiple versions of each package - this is expected.

Instead, my best guess is that your R session cache'd what was available in the repository. This is the default behavior for `available.packages` (it stores a copy of the repo's PACKAGES file so that subsequent requests don't all pull the same info from the repo, however it means if the R session is long lived the repository information can become stale).  

I'd recommend restarting the R session and seeing if that resolves the behavior, as opposed to removing things from the renv cache - that shouldn't be necessary. But please let me know if you are seeing evidence to the contrary.

**Comment by kevinushey** [comment]
`renv` does attempt to cache the output of `available.packages()` across sessions, just to avoid slow attempts to re-query the set of available packages. Perhaps a function `renv::refresh()` would be useful for refreshing the repository cache?

Or perhaps the extra attempts to cache `available.packages()` across sessions is misguided?

**Comment by slopp** [comment]
Thanks for clarifying @kevinushey , I didn't realize `renv` also cache'd available.packages, but I guess that makes sense since it is an renv shim around the actual function.

FWIW I have always found the available.packages caching, even in base R for a single session, confusing. The call to the PACKAGES file is rarely the slow part of package installation. So the speed up is really only useful if you are frequently checking to see "no updates", which I seldom see users (or myself) do. 

So I'd argue the risk of a stale cache here is bigger than the benefit the cache is providing. But perhaps I am missing how often that cache is hit in regular workflows

**Comment by kevinushey** [comment]
I've just pushed a commit that makes the following changes;

1. No more caching of repositories to use cross-session. (Note that we still cache available packages on a per-session basis, using the same logic as R does by default)

2. I've added a function `renv::refresh()` to forcefully update the set of available packages as seen by `renv`. Of course, restarting the R session is another way to request a new cache, but I think on occasion one might want to refresh the available packages cache without an R session restart.

We can revisit cross-session caching in the future if we find it's really necessary for some reason.

@mac-pfa I think this should address your concerns; please upgrade to the latest version of `renv` and let us know if you have any trouble!

**Comment by mac-pfa** [comment]
@kevinushey Thanks for the help - it seems to work now :)
