### ISSUE TITLE
renv::restore() pulling libraries from wrong repository

### ISSUE THREAD

**Issue by mbellis111** [rstudio/renv#701]
Hi,

Our project has a .lock file using both cran & an internal cran repository from artifactory.

When calling renv::restore() using renv 0.12.5 it is pulling libraries from the internal cran even though they are listed in the lock file as coming from the regular cran repository.

```
"R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.10/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.10/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.10/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.10/workflows"
      },
      {
        "Name": "NIBR_CRAN",
        "URL": "https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  }
...
"Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.72.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8f9ce74c6417d61f0782cbae5fd2b7b0"
    },
    "DBI": {
      "Package": "DBI",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4744be45519d675af66c28478720fce5"
    },
...
 "Ziploc": {
      "Package": "Ziploc",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "NIBR_CRAN",
      "Hash": "e519fb3f5e75cc56f1e4a82734a07d0d"
    },
```

Renv prints the proper location of the packages

```
10:53:28  The following package(s) will be updated:
10:53:28  
10:53:28  # CRAN ===============================
10:53:28  - BH               [* -> 1.72.0-3]
10:53:28  - DBI              [* -> 1.1.0]
10:53:28  - R6               [* -> 2.5.0]
10:53:28  - RCurl            [* -> 1.98-1.2]
10:53:28  - RSQLite          [* -> 2.2.1]
...
10:53:28  # NIBR_CRAN ==========================
10:53:28  - Ziploc           [* -> 1.1.0]
```

However when downloading the packages it will use the wrong cran repository.

```
10:53:31  * Querying repositories for available source packages ... Done!
10:53:34  Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/BH/BH_1.72.0-3.tar.gz' ...
10:53:35  	OK [file is up to date]
10:53:39  Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/DBI/DBI_1.1.0.tar.gz' ...
10:53:39  	OK [file is up to date]
10:53:39  Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/R6_2.5.0.tar.gz' ...
```

And finally it does not properly form the path to the archive for the project actually in the internal cran, which should be 
"https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/Ziploc/1.1.0/Ziploc_1.1.0.tar.gz"
```
Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/Ziploc/Ziploc_1.1.0.tar.gz' ...
10:54:09  The following error(s) occurred while retrieving 'Ziploc':
10:54:09  
10:54:09  	- character(0)
10:54:09  	- character(0)
10:54:09  
10:54:09  Error: failed to retrieve package 'Ziploc'
```

Thanks,
Matt

**Comment by kevinushey** [comment]
> And finally it does not properly form the path to the archive for the project actually in the internal cran, which should be
"https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/Ziploc/1.1.0/Ziploc_1.1.0.tar.gz"

This should be resolved in the latest release of `renv` (0.13.2).

> However when downloading the packages it will use the wrong cran repository.

This is a current limitation of `renv`. When restoring packages, it looks in each declared repository from first to last to see if the declared package is available. If that repository provides the requested package, then it is retrieved from there.

I'll see if it might be possible to re-arrange the repositories so that the marked repository (if any) is preferred over any other repositories that might be set.

**Comment by mbellis111** [comment]
Thanks - I can confirm that re-ordering the repositories to put CRAN above our internal one help resolve the first issue. It preferred cran over internal when downloading and listed first in the .lock file.

If possible I think preferring the marked repositories (if listed in the lock file) would help with clarity.  While it shouldn't make a difference which repo you are getting a package from, it is confusing if you mark one and it is using another.

I upgraded to renv 0.13.2 and I can confirm that it is using the correct path again. I'll look into the commits to see what fixed this out of curiosity.

```
* Project <path here>' loaded. [renv 0.13.2]
> renv::install("Ziploc@1.1.0", rebuild=T)
Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/Ziploc/1.1.0/Ziploc_1.1.0.tar.gz' ...
	OK [file is up to date]
Installing Ziploc [1.1.0] ...
	OK [built from source]
> renv::restore(clean=T)
* The library is already synchronized with the lockfile.
> renv::remove("Ziploc")
* Removing package(s) from project library ...
Removing package 'Ziploc' ... Done!
> renv::purge("Ziploc")
The following packages will be purged from the cache:

	Ziploc 1.1.0 [Hash: 836ee4e754595d57c294dc18de51884c]
	Ziploc 1.1.0 [Hash: e519fb3f5e75cc56f1e4a82734a07d0d]

Do you want to proceed? [y/N]: y
* Removed 2 packages from the cache.
> renv::restore(clean=T)
The following package(s) will be updated:

# NIBR_CRAN ==========================
- Ziploc   [* -> 1.1.0]

Do you want to proceed? [y/N]: y
Retrieving 'https://<INTERNAL_CRAN_PATH>/artifactory/CRANNew/src/contrib/Archive/Ziploc/1.1.0/Ziploc_1.1.0.tar.gz' ...
	OK [file is up to date]
Installing Ziploc [1.1.0] ...
	OK [built from source]

```

**Comment by brianrepko** [comment]
Hi @kevinushey and @mbellis111 - I think that there are two interrelated items here:

1. renv will potentially restore from a different repository than the one listed in the renv.lock file
2. the Artifactory URL is not correct for an archived version

The initial fix for item 2 is already in the codebase for 0.12.5 - see https://github.com/rstudio/renv/issues/602
So I don't understand the comment about this being fixed in 0.13.2.
I don't see anything in the commits from 0.12.5 to 0.13.2 on this.

IIRC (and it is my last comment on issue #602 ) is that Artifactory can also host a CRAN mirror which is CRAN-like.
So in our case, because of item 1 - renv picks up an archived package in the Artifactory CRAN mirror and thinks it is CRAN-like.
Then when it looks in the non-CRAN-mirror part (the local repo), it fails to build and test the correct URL.

If we fix item 1 (CRAN before Artifactory - or use of the renv.lock data) - then item 2 is basically fixed which I think is what @mbellis111 is showing above - if the FIRST archive lookup against the repo is Ziploc, then it works.

My apologies @kevinushey - I did not realize that item 1 was there or we would have continued development earlier.

**Comment by brianrepko** [comment]
We might also fix item 1 just by reordering the repositories in the renv.lock file as well.

**Comment by kevinushey** [comment]
I've just pushed a change to `renv` that allows `renv` to prefer the repository whose name matches that as encoded in the lockfile, so that your attempts to restore Ziploc should use the NIBR_CRAN repository regardless of the ordering of repositories. If you have time, please try out the development version and let me know if things work as expected.

**Comment by brianrepko** [comment]
Thank you!! I'll take a look and run a test and let you know!
