### ISSUE TITLE
DESCRIPTION file constraints are ignored

### ISSUE THREAD

**Issue by tannerntannern** [rstudio/renv#767]
Following https://rstudio.github.io/renv/articles/packages.html tells me that `renv` can install dependencies specified in a `DESCRIPTION` file via `renv::install()` with no parameters.  This does seem to pick up packages properly but version constraints are completely ignored.

In my description file I have:
```
Imports:
    dplyr (< 1.0.3),
    ...
```

While running `renv::install()` I see `Installing dplyr [1.0.6] ...` which clearly violates the constraint.  This is more obvious if you use an unsatisfiable constraint, such as `dplyr (> 5.0.0)` (current latest version is 1.0.6).  `renv` happily installs this as well.

**Comment by kevinushey** [comment]
If you request a specific version of `dplyr`, e.g. `dplyr (== 1.0.3)` that should do what you expect, but note that `renv` does not attempt to recursively solve package versioning constraints (as R packages almost never state that they only work with "older" versions of a package)

**Comment by kenahoo** [comment]
It is quite common for me to supply an upper bound on a package in my `DESCRIPTION` files, since packages can change in incompatible ways at major version boundaries.

**Comment by kenahoo** [comment]
I must say - the inability to provide package version constraints and have those honored by any of the major R toolchains is the number one problem my (large) organization has with deploying R code to production and organizing code into libraries.  I do hope this need can be addressed somehow so that the version-satisfying mechanisms people are used to from python, javascript, julia, etc. can be brought to the R world.

**Comment by hadley** [comment]
@kenahoo I get that it's frustrating, I just think it's too big a lift for us to tackle this because literally no one in the R community is used to it. I don't think it's ever going to be possible to port the version satisfying mechanism from other languages because CRAN is just so different.
