### ISSUE TITLE
support restore from r-universe repositories

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#789]
For example, with latest `rlang`:

```
Package: rlang
Version: 0.4.11.9000
Title: Functions for Base Types and Core R and 'Tidyverse' Features
Description: A toolbox for working with base types, core R features
  like the condition system, and core 'Tidyverse' features like tidy
  evaluation.
Authors@R: c(
    person("Lionel", "Henry", ,"lionel@rstudio.com", c("aut", "cre")),
    person("Hadley", "Wickham", ,"hadley@rstudio.com", "aut"),
    person(given = "mikefc",
           email = "mikefc@coolbutuseless.com", 
           role = "cph", 
           comment = "Hash implementation based on Mike's xxhashlite"),
    person(given = "Yann",
           family = "Collet",
           role = "cph", 
           comment = "Author of the embedded xxHash library"),
    person("RStudio", role = "cph")
    )
License: MIT + file LICENSE
ByteCompile: true
Biarch: true
Depends: R (>= 3.3.0)
Imports: utils
Suggests: cli (>= 2.5.0), covr, crayon, fs, glue, knitr, magrittr,
        methods, pak, pillar, rmarkdown, stats, testthat (>= 3.0.0),
        tibble, usethis, vctrs (>= 0.2.3), withr
Enhances: winch
SystemRequirements: C++11
Encoding: UTF-8
RoxygenNote: 7.1.1
Roxygen: list(markdown = TRUE)
URL: https://rlang.r-lib.org, https://github.com/r-lib/rlang
BugReports: https://github.com/r-lib/rlang/issues
Config/testthat/edition: 3
Repository: https://r-lib.r-universe.dev
RemoteUrl: https://github.com/r-lib/rlang
RemoteRef: HEAD
RemoteSha: 869f00a27acfda52b2e428cdf7292895c4e8061c
NeedsCompilation: yes
Packaged: 2021-06-28 12:21:58 UTC; root
Author: Lionel Henry [aut, cre],
  Hadley Wickham [aut],
  mikefc [cph] (Hash implementation based on Mike's xxhashlite),
  Yann Collet [cph] (Author of the embedded xxHash library),
  RStudio [cph]
Maintainer: Lionel Henry <lionel@rstudio.com>
Built: R 4.1.0; x86_64-w64-mingw32; 2021-06-28 12:24:59 UTC; windows
Archs: i386, x64
```

I think we would want to detect the use of `r-universe` within the Repository field, and then use + other remote fields to set the repositories to use before restore.

**Comment by jeroen** [comment]
Let me know if I can help here! 

R-universe does not archive old versions of packages at this point (because they may be updated very often). But all r-universe packages eventually are installed from git. My intention was that by including `RemoteUrl` and `RemoteSha` in the DESCRIPTION, renv woud be able to restore the package from Git, in the same way as when it had been installed from Git directly, rather than via R-universe.

**Comment by kevinushey** [comment]
> A related aspect is that currently renv seems to connect a locally built package to the r-universe repository if the package has an (older) build in r-universe, without warning. (Let me know if I should move this to a separate issue)
>
> n2khab package is misjudged as coming from the 'inbo' r-universe, while it's locally built. I assume this cannot work on restore. I'd rather expect this should give a warning that it's not recommended to record locally built packages in renv.lock; anyway it should not link to the r-universe.

This is at least partly intentional; see https://github.com/rstudio/renv/blob/4642f5dc7058e067438966ef99a28c0b84fd87c8/R/snapshot.R#L684-L697. The intention here is to allow packages which were installed from sources, but at least appear to be available from a package repository, to be restored from that repository.

My guess is that this package is indeed available (in some version) from that universe repository URL, and so it's recorded as such.

> the 'inbo' r-universe is depicted twice, in a different manner (its URL vs its name)

This seems correct to me? The actual repository name + URL pair itself is recorded in the Repository field (since that's what was active in your session), and the package was recorded with that repository name in the lockfile. Of course, the fact that all of the remote fields are missing likely implies `renv` will fail to restore the package, but the solution seems clear to me -- install an updated version of the package directly from the r-universe repository.

**Comment by florisvdh** [comment]
Thank you @kevinushey for explaining the logic and pointing to the remark in `snapshot.R`, makes sense.

If such locally built package is _absent_ from any repository, `renv::status()` triggers a warning (`renv::init()` however doesn't):

```r
> renv::status()
* The project is already synchronized with the lockfile.
The following package(s) were installed from an unknown source:
         _
  n2khab   [0.5.0.900]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).
```

This warning would also hold for the previous case, where it is present in a repo but not in the local state, but in that case `renv::status()` is silent (just saying 'The project is already synchronized with the lockfile'). Going off-topic here, since that's indeed not specific to r-universe repositories :thinking:. I agree with the logic that you explained, but IMHO it would be good that at least `renv::init()` throws a warning about what it is doing in such case. Would that make sense to you?

**Comment by florisvdh** [comment]
Regarding how the 'inbo' r-universe is depicted in two different ways, I was referring to the difference between packages INBOtheme and n2khab in the output of `renv::init()`:

```
# https://inbo.r-universe.dev ========
- INBOtheme       [* -> 0.5.9]
```

versus

```
# inbo ===============================
- n2khab          [* -> 0.5.0.900]
```

Same in the above example `renv.lock`:

```
      "Source": "Repository",
      "Repository": "https://inbo.r-universe.dev",
```

 versus

```
      "Source": "Repository",
      "Repository": "inbo",
```

Sure it is not wrong, it's just not 100% consistent; I'd expect either the name or the URL in both cases.

BTW - I love `renv`!

**Comment by kevinushey** [comment]
@florisvdh, coming back to this now -- I wonder if this is ultimately due to a change in how `r-universe` annotated the repository in the DESCRIPTION file for a downloaded package? For example:

```
> options(repos = c(
+     rstudio = 'https://rstudio.r-universe.dev',
+     CRAN = 'https://cloud.r-project.org'))
> renv::install("rstudioapi")
Installing rstudioapi [0.13.0-9000] ...
	OK [copied cache]
> desc <- renv:::renv_description_read(package = "rstudioapi")
> desc[["Repository"]]
[1] "https://rstudio.r-universe.dev"
```

I wonder if `r-universe` changed how it recorded the Repository field for these different universes.

From what I can see, `renv` can handle `r-universe` repositories without any changes required, as long as those repositories are also recorded within the lockfile at the top level. However, we could probably make this a bit more robust -- in particular, if the Repository field starts with `https://`, then we should explicitly use that repository URL when attempting to restore the package.

**Comment by kevinushey** [comment]
> R-universe currently does not archive old versions of packages, because they may be updated very often. But all r-universe packages are taken from git by design. Hence my intention was that by including the upstream RemoteUrl and RemoteSha in the DESCRIPTION for r-universe packages, renv woud be able to restore the package from Git, in the same way as when it had been installed from Git directly, rather than via R-universe.

This makes sense -- I'll see if we can use this when installing a package from the "archive" rather than looking into the regular repository archive locations.

**Comment by florisvdh** [comment]
@kevinushey thanks for the hints.

`n2khab` has no `Repository` field in its _local_ build:

```r
> desc <- renv:::renv_description_read(package = "n2khab")
> desc[["Repository"]]
NULL
```
It is the locally built package that caused the `# inbo ========` heading (same in `renv.lock`). Presumably that `inbo` name is based on the GitHub "inbo" account where the package refers to - or could it be that it derives the mere presence of the package at r-universe from a list of packages present at inbo.r-universe.dev, and makes the connection in that way? Apart from emailadresses, the only reference to inbo in the (locally built) package DESCRIPTION are:

```
URL: https://inbo.github.io/n2khab, https://github.com/inbo/n2khab
BugReports: https://github.com/inbo/n2khab/issues
```

Anyway, the absence of `r-universe` (or any) Repository from DESCRIPTION will indeed be explanation of not appearing under the `# https://inbo.r-universe.dev ======` heading (same in `renv.lock`), so it doesn't come from a change in r-universe but just from using the local package source. The corresponding source package at r-universe does have `Repository: https://inbo.r-universe.dev` in its DESCRIPTION, so that one should work normal.

`inbo` is also the name of the r-universe repository in `renv.lock`:

Extract from `renv.lock`:

```json
{
  "R": {
    "Version": "4.1.2",
    "Repositories": [
<lines omitted>
      {
        "Name": "inbo",
        "URL": "https://inbo.r-universe.dev"
      }
    ]
  },
  "Packages": {
    "n2khab": {
      "Package": "n2khab",
      "Version": "0.5.0.900",
      "Source": "Repository",
      "Repository": "inbo",
      "Hash": "9aafc0465394ce0bd93a7220c20db697"
    },
```
So the essential point is that the locally built package is assumed to come from a Repository (notably `inbo`), while it doesn't. It should be treated as just another locally built package (and ideally warned for like [above](https://github.com/rstudio/renv/issues/789#issuecomment-944047539)).

**Comment by kevinushey** [comment]
Restoration of packages installed from r-universe repositories should now be handled. For example, with the lockfile:

```
{
  "R": {
    "Version": "4.1.2",
    "Repositories": [
      {
        "Name": "rlib",
        "URL": "https://r-lib.r-universe.dev"
      }
    ]
  },
  "Packages": {
    "rlang": {
      "Package": "rlang",
      "Version": "0.4.11.9001",
      "Source": "Repository",
      "Repository": "https://r-lib.r-universe.dev",
      "RemoteUrl": "https://github.com/r-lib/rlang",
      "RemoteRef": "HEAD",
      "RemoteSha": "26c4a878473578cf7b4c630f457a3bdfc46c8c31"
    }
  }
}
```

I see:

```
> renv::restore(packages = "rlang")
The following package(s) will be updated:

# https://r-lib.r-universe.dev =======
- rlang   [* -> 0.4.11.9001]

Do you want to proceed? [y/N]: y
* Querying repositories for available source packages ... Done!
Installing rlang [0.4.11.9001] ...
        OK [built from source]
Moving rlang [0.4.11.9001] into the cache ...
        OK [moved to cache in 0.29 milliseconds]
```

In this case, `renv` saw that no binary or source copy of this version of `rlang` was available in the current r-universe repository, and so fell back to installing directly using git.

**Comment by pfuehrlich-pik** [comment]
That's great news, thank you so much! :smile: Is there a CRAN release planned anytime soon?

**Comment by florisvdh** [comment]
Amazing :rocket:, thanks a lot @kevinushey. Could reproduce that! I've experimented a little further.

As you explained earlier, the behaviour of `renv` to tie local packages to a repository when possible, is intentional, and this already seemed to work in `renv` 0.14.0 for any repository, including r-universe repositories - so my latest reported output should be considered just fine, sorry about the confusion.

There seems to be a change for the case where the local package cannot be linked to an active repository:

Both below cases only have the CRAN repo enabled (`options(repos = c(CRAN = "https://cloud.r-project.org/"))`).

#### with `renv` 0.14.0-50 (github):

This locally built package (which is not on CRAN, only in the inbo r-universe repo = disabled in this session) is now stored like:

```json
    "n2khab": {
      "Package": "n2khab",
      "Version": "0.5.0.900",
      "Source": "Repository",
      "Repository": null,
      "Hash": "9aafc0465394ce0bd93a7220c20db697"
    },
```

So a local package is now always set as coming from a repository, here being the 'null' repository (before, it would have been source 'unknown', not considered as coming from a repo).

In this case no warning came anymore from `snapshot()` (which now reports this package under `# Repository ========`) or `status()`.

==> **Suggestion**: should a warning not have been risen, as it was in 0.14.0? - see below

#### with `renv` 0.14.0 (CRAN):

Local package registered as:

```json
    "n2khab": {
      "Package": "n2khab",
      "Version": "0.5.0.900",
      "Source": "unknown",
      "Hash": "9aafc0465394ce0bd93a7220c20db697"
    },
```

Where warnings occurred:

```r
> renv::snapshot()
The following package(s) were installed from an unknown source:
         _
  n2khab   [0.5.0.900]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).

Do you want to proceed? [y/N]: y
The following package(s) will be updated in the lockfile:
# CRAN ===============================
...
# (Unknown Source) ===================
- n2khab       [* -> 0.5.0.900]
Do you want to proceed? [y/N]: y
* Lockfile written to '/.../renv.lock'.

> renv::status()
* The project is already synchronized with the lockfile.
The following package(s) were installed from an unknown source:
         _
  n2khab   [0.5.0.900]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).
```

**Comment by zkamvar** [comment]
I'm wondering if there is a way to flag universe repositories as "in development" in the lockfile and have {renv} restore from the latest version. 

The reason I ask is that I use the universe for two reasons:

1. to distribute packages that are undergoing rapid development
2. to distribute compiled dependencies that are frustrating to install on mac and windows when their versions update on CRAN ({stringi} and {textshaping} are two examples that update often enough where this becomes a problem).

In the latter case, it would be really good to have a mechanism for people to restore to the latest binary version.

**Comment by ddsjoberg** [comment]
@zkamvar perhaps this issue about tracking the most recent release (rather than the current version on GitHub) will be helpful?
https://github.com/rstudio/renv/issues/792

**Comment by kevinushey** [comment]
I'll think about a CRAN release soon, but given the amount of code changes that have become part of the development version I'd like to give users (like yourselves!) more of a chance to kick the tires to make sure there aren't any unintended regressions.

Re: https://github.com/rstudio/renv/issues/789#issuecomment-972704634; would you mind distilling this into a separate issue?

**Comment by zkamvar** [comment]
@ddsjoberg, you are my hero today! This along with [the '*release' branch tag in the r-universe packages.json](https://github.com/r-universe-org/demo-registry/blob/f19b934aca20e184baeae26aed7fd34e581dc6e9/packages.json#L19-L23) is _exactly_ what I needed ^_^

**Comment by kevinushey** [comment]
This has been implemented on the main branch now; I think this can be closed. Please feel free to file an issue if you encounter any other issues!
