### ISSUE TITLE
calling `renv` deletes the package `base`

### ISSUE THREAD

**Issue by markjrieke** [rstudio/renv#835]
So I was following along some of the renv vingettes while trying to setup a github Action & I'm not quite sure what happened. I believe I called:

* `renv::status()`
* `renv::snapshot()`
* `renv::restore()`

I then tried to run the workflow, which depends on the `tidyverse`, and I got an error along the lines of `Warning: there is no installed package called tidyverse`

I thought that was a bit strange so I ran `install.packages("tidyverse")`, and it looks like it installed all the packages into the Repo itself. I tried to open a new studio session & it gave me this error:

![image](https://user-images.githubusercontent.com/31866288/135896268-fa3b70f2-4bda-483b-b32f-1f9bb55308b6.png)

Now I can't open RStudio. I think what's going on is that RStudio is trying to reference the library folder that was created in the repo by renv (which just contains tidyverse packages at this point). All my other packages (and tidyverse packages) are still in the expected folder on my computer. I've got a twofold question:

* How do I get RStudio working again?
* What did I do incorrectly beforehand?

Apologies for the lack of a reprex, I can't get into RStudio right now unfortunately!

**Comment by markjrieke** [comment]
update: I uninstalled/reinstalled R/RStudio & am now back in, but still not sure what I did beforehand (also a bit scared to attempt to recreate the issue!)

**Comment by kevinushey** [comment]
Unfortunately, without a reproducible example, it's very hard for me to know what went wrong.

**Comment by CinnamonJP** [comment]
Thank you for your quick reply. I reinstall prior release (0.13.1). I didn't have this issues when I was using version 1.13.1. Is it a problem specific to 0.14.x?

**Comment by kevinushey** [comment]
Unfortunately I still don't have any good ideas as to what could've caused this to happen. If the problem occurs again please let me know and provide as much detail as possible. (Ideally, I would be able to reproduce this myself locally)

**Comment by kevinushey** [comment]
https://github.com/rstudio/renv/issues/614 made it clear that one way this could happen is if something tries to recursively delete things in the temporary directory when the `renv` sandbox is active. I've since disabled the sandbox by default to avoid this issue -- hopefully that would imply ultimately fixing the OP's issue as well.

**Comment by svethitov** [comment]
Hello,

It appears that after re-enabling the sandbox in version 0.16 the problem has returned.

It happened to me after upgrading to renv 0.16 on Windows. I have administrator rights on the server that it happened! Maybe that has something to do with it, as I discovered that the packages' folders in the system library are empty after initiating or activating a renv project.
By disabling the Sandbox the problem disappeared. For some reason renv is deleting the packages from the system library.

**Comment by kevinushey** [comment]
@svethitov, any chance you could share a set of steps I could use to try and reproduce this locally?

Are you running any tools that try to periodically clean out e.g. temporary directories or anything like that?

**Comment by antonmalko** [comment]
Hi,

On Windows, R temporary directory is sometimes deleted *even if the R session has been active and running*. In such cases R would suddenly complain about being unable to create some temporary file, and you have to manually re-create the temp dir. This has happened to me multiple times. See also the StackExchange threads below (people complain about similar problems, and sometimes mention that Windows cleanup routines / third-party cleanup services appear to be disabled):

+ https://stackoverflow.com/questions/38086356/launching-r-help-error-in-fileout-wt-cannot-open-the-connection
+ https://superuser.com/questions/1463748/temp-folder-being-deleted-in-users-appdata?rq=1
+ https://stackoverflow.com/questions/56078433/is-windows-10-or-r-itself-deleting-my-temp-directory
+ https://stackoverflow.com/a/57474039

`renv` changelog for v 0.16.0 indicates that `renv` stores the sandbox in the R tempdir. Perhaps, an easy solution could be to use a different default directory for the sandbox (i.e., not in "AppData/Local/Temp")?

**Comment by kevinushey** [comment]
> Perhaps, an easy solution could be to use a different default directory for the sandbox (i.e., not in "AppData/Local/Temp")?

The question here is, what should that directory be? It's a surprisingly hard question to answer, because `renv` uses Windows junction points, and these have some restrictions:

1. These only work on NTFS-formatted disks,
2. As I understand, they do not work across different disks / mounts.

In a perfect world, we would use symlinks, but Windows still doesn't enable symlinks for non-admin accounts (unless you jump through some hoops, which the average user likely would not do).

By putting the junction points in the temporary directory, we have a fairly good chance of ensuring that the links are on the same disk as the R installation itself, and we also ensure that these links are automatically cleaned up when the R session exits.

Unfortunately, apparently buggy software that cleans items in the temporary directory deletes these junction points by _recursing into these junctions_, rather than just removing the junctions themselves. Hence the issue seen here.

Another potential solution would be to copy, rather than link, the system packages into the sandbox on Windows... but this could be slow, especially on systems with older (non-SSD) drives.

Perhaps there's some other user storage location that would be "safe" from such cleaners, e.g. `AppData/Local/renv` or something.

**Comment by kevinushey** [comment]
I've made a change in the development version of `renv` that should help here:

https://github.com/rstudio/renv/commit/21f7cba4d28d62d4fe711e7f229acdba02a1f7ac

For example:

```
* Project '~/scratch/example.renv' loaded. [renv 0.16.0-37]
> renv::paths$sandbox()
[1] "C:/Users/kevin/AppData/Local/R/cache/R/renv/sandbox/R-4.2/x86_64-w64-mingw32/1dfb4315"
```

If necessary, the sandbox path can be customized via the `RENV_PATHS_SANDBOX` environment variable as well; this is most likely relevant for users with projects or R installations on network mounts or similar (the sandbox should probably exist in the same mount as the R installation)

**Comment by beansrowning** [comment]
This is positive news. I'll test the new dev version with my team. It's been a huge pain point for us that crops up almost weekly and requires a complete re-install of R each time.

**Comment by kevinushey** [comment]
@beansrowning I'm sorry for the trouble. 😞  I'll try to get a new release of `renv` out soon if you can confirm the development version resolves the issue you're seeing.

**Comment by renejuan** [comment]
@kevinushey I have been using [21f7cba](https://github.com/rstudio/renv/commit/21f7cba4d28d62d4fe711e7f229acdba02a1f7ac) for a about 1 week now and no issues so far. Thank you so much! 😀

**Comment by kevinushey** [comment]
Phew! Thank you for taking the time to confirm; I'll start preparing a CRAN release soon.
