### ISSUE TITLE
Auto-link `~/.Rprofile` if exists

### ISSUE THREAD

**Issue by akgold** [rstudio/renv#868]
I keep API keys and other environment scripts in my `~/.Rprofile` so it gets run every time I start a new R session in every project.

When I use an `renv` project, it auto-creates a project-level `.Rprofile`, which blocks my main one from getting sourced. I end up adding `source("~/.Rprofile")` in almost every project...but usually only after I've forgotten and hit an error, which can sometimes take a while to realize why it's happening. 

If `renv` detected the existence of a `~/.Rprofile` and automatically (or optionally) added a line to source it to the project-level `.Rprofile`, this would resolve a lot of hassle.

**Comment by kevinushey** [comment]
You can use `options(renv.config.user.profile = TRUE)` to tell `renv` to try and source `~/.Rprofile` on startup. (It's off by default since, in theory, sourcing an arbitrary `~/.Rprofile` could break encapsulation in `renv` projects.)

See https://rstudio.github.io/renv/reference/config.html for more details.

As an aside, is setting these in your `~/.Renviron` an option? `renv` will always read environment variables from that location.

**Comment by akgold** [comment]
Wow! TIL. 

If there is ever deeper `renv` integration into RStudio, it'd be really helpful to have a checkbox for this when you start a new project.

`~/.Renviron` is an option -- but I generally prefer to only manage 1 file and I've got some things that aren't just setting env vars.
