### ISSUE TITLE
In the presence of pak, renv does not symlink cached packages but builds them again from cache

### ISSUE THREAD

**Issue by michaelmayer2** [rstudio/renv#928]
**Expected behaviour:**

step 1 is installing `SuppDists` as expected - download from RSPM, install it and add it to `renv` cache
step 2 detects the existence of `SuppDists` in the `renv` cache and symlinks it into the `renv` directory as it is default behaviour of `renv` without `pak`

**Actual behaviour**

step 1 is ok
step 2 the package is retrieved again from cache and installed (also evident from the timing)

**Reproducible example**

See below. Run in docker container rocker/r-ver:4.1.2 after running

```bash
apt-get update && apt-get install libxt6 libxtst6 pandoc vim
R -q -e "install.packages(c('styler','reprex'))"
```

Note 1: Example below uses admin privileges to install `renv` and `pak` but if `renv`/`pak` is already present this step can easily be omitted.
Note 2: `reprex` does not show `pak` output - I had to manually copy the pak output into the reprex output.  
Note 3: When installing `tidyverse` it is even more evident that (for binary packages) the cached (step 2) install takes the same amount of time than step 1 minus the download time. 

``` r
# Set up immutable URL from public RSPM 
options(repos = "https://packagemanager.rstudio.com/all/2022-01-31+MTo3OTU2NzYxLDI6NDUyNjIxNTs5RDdCN0EyMg")

# pre-requisites: setup workdir and install renv into R library

testdir<-paste0(Sys.getenv("HOME"), "/renv-test")
dir.create(testdir)
setwd(testdir)
install.packages(c("renv","pak"), paste0(Sys.getenv("R_HOME"),"/library/"))
#> Updating HTML index of packages in '.Library'
#> Making 'packages.html' ... done

# enable pak in renv 

options(renv.config.pak.enabled=TRUE)

# step 1: Create fresh renv, install SuppDists package and clean up renv in workdir

renv::init()
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Lockfile written to '~/renv-test/renv.lock'.
renv::install("SuppDists")
                                                                          
→ Will install 1 package.
→ Will download 1 CRAN package (141.80 kB).
+ SuppDists   1.1-9.7 [bld][cmp][dl] (141.80 kB)
ℹ Getting 1 pkg (141.80 kB)
✔ Got SuppDists 1.1-9.7 (source) (339.86 kB)                             
✔ Downloaded 1 package (339.86 kB)in 3.6s                                
ℹ Building SuppDists 1.1-9.7
✔ Built SuppDists 1.1-9.7 (1.6s)                                
✔ Installed SuppDists 1.1-9.7  (117ms)                            
✔ 1 pkg: added 1, dld 1 (339.86 kB) [33.7s]    
#> 

system("rm -rf renv* .Rprofile")

# step 2: Repeat step 1  

renv::init()
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Lockfile written to '~/renv-test/renv.lock'.
renv::install("SuppDists")
                                                                          
→ Will install 1 package.
→ Will download 1 CRAN package (141.80 kB).
+ SuppDists   1.1-9.7 [bld][cmp][dl] (141.80 kB)
ℹ Getting 1 pkg (141.80 kB)
✔ Cached copy of SuppDists 1.1-9.7 (source) is the latest build
✔ No downloads needed, all packages are cached                     
ℹ Building SuppDists 1.1-9.7
✔ Built SuppDists 1.1-9.7 (1.5s)                                
✔ Installed SuppDists 1.1-9.7  (188ms)                            
✔ 1 pkg: added 1 [3.2s]     
#> 

system("rm -rf renv* .Rprofile")
```

<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by michaelmayer2** [comment]
Performance impact on installing `tidyverse` via `renv::install("tidyverse")`

All times in seconds on an MacBook Pro M1, Ubuntu Bionic x86_64 container with R 4.1.2 from RStudio. 

* binary packages from RSPM

|  | no pak | pak enabled |
| ------------- | ------------- | ------------- |
| clean renv  | 541.8 | 358.1  |
| packages in renv cache  |  12.0| 188.0  |

* Source packages from MRAN

|  | no pak | pak enabled |
| ------------- |     ---: | ---: |
| clean renv  | 13427.3 | 4896.0  |
| packages in renv cache  |  44.9 | 8969.6  |

It is strange that with `pak` enabled and `renv` cache fully populated it takes longer than with a clean `renv`. It seems that `pak` is thinking a long time about which packages to build and then rebuilds and recompiles them anyway.

**Comment by kevinushey** [comment]
The main problem is that `pak` doesn't know anything about the `renv` cache, so it doesn't know it can find already-built packages to be used from the `renv` cache.

It's not clear to me if this is `pak`'s job or `renv`'s job; ideally, `pak` would be able to find packages in the `renv` cache and use them, since otherwise I think `renv` would be responsible for solving the installation plan.

@gaborcsardi, what is the right way forward for `renv` here? It seems like we'd need to be able to do something like:

1. Ask `pak` to solve the installation plan (so we know where packages should be installed from, and their versions),
2. Look in the cache, and pre-populate the library with symlinks,
3. Run the regular `pak::pkg_install()` machinery.

Does that sound right? If so, what are the `pak` APIs available for (1)? Maybe one of the `pak` lockfile functions?

Another alternative, I think, would be for `pak` to learn how to find things in the `renv` cache when installing packages.

**Comment by gaborcsardi** [comment]
Yeah, you can do that. `lockfile_create()` creates an install plan and writes it out to a json file. `lockfile_install()` installs it. Between the two you can remove the packages from the plan that you can symlink locally.

Ideally you would create an install plan for all packages in the project, I guess.

OTOH, I think if renv is in charge of deciding what exactly to install and from where, then renv could work everything out and tell pak to download and install the packages that are not cached in the renv cache, without pak doing any dependency resolution at all.

**Comment by Polkas** [comment]
It will be great to get some consensus here as the pak option without cache seems to be not so useful.
On the other hand when hundreds of packages have to be installed on the linux machine the pak is able to reduce the time significantly so I assume the idea behind the issue is very important.  It is important even from the ecological perspective as we will save a lot of energy and time;)

**Comment by hadley** [comment]
Tracking this in https://github.com/r-lib/pak/issues/284
