### ISSUE TITLE
.Rprofile crashes R Jupyter notebook

### ISSUE THREAD

**Issue by nbafrank** [rstudio/renv#929]
Hi all,

I am using a Jupyter notebook with an R kernel and we want to use `renv` with a particular project. After initializing the env, we find that the presence of .Rprofile in the folder crashes the R kernel in the notebook. If we remove .Rprofile from the folder and activate manually, everything works. This also works if we activate the `renv` manually from a different folder (e.g. using renv::activate("path to folder")), because the .Rprofile file is not there.

Any ideas?

Thank you so much for your time and help

**Comment by kevinushey** [comment]
Thanks for the bug report -- can you provide some instructions so that I might be able to easily reproduce myself?

**Comment by micdonato** [comment]
I was having the same issue. This seems to be due to Jupyter trying to load IRKernel from the renv, and if that has not been installed, it fails.

This was the code that broke it. This code needs to be in a cell in a notebook **within the directory where `renv` is**.

```
setwd('/home/micdonato/rtest') 
library(renv)
init()
renv::install('tinytest')
```
Trying to restart the kernel creates the error.

The error was this (part of it):

```
Error in loadNamespace(x) : there is no package called 'IRkernel'
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
[I 2022-02-03 19:21:15.261 SingleUserLabApp restarter:75] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
Error in loadNamespace(x) : there is no package called 'IRkernel'
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

(mind that the notebook needs to be in the same directory of the `renv`)

Then I tried to check what the `.libPaths()` were. `renv` does not know about `/usr/local/lib/R/site-library` but it knows only about `/usr/local/lib/R/library`. I think that makes sense, to isolate the packages installed in the environment from the ones installed globally.

The solution then is either letting `renv` know about `/usr/local/lib/R/site-library` (removing the isolation) or installing `IRkernel` when setting up the environment with `renv::install("IRkernel")`. If I do that the kernel starts properly.

**Comment by hadley** [comment]
IMO this is more of a jupyter issue — failure to find `IRKernel` shouldn't cause jupyter to crash, but should instead generate a useful message.

**Comment by hadley** [comment]
Actually we should solve this by adding IRKernel as a dependency when we see jupyter notebooks, and we should also parse `.ipynb`s for package dependencies.
