### ISSUE TITLE
Restore env from `DESCRIPTION`

### ISSUE THREAD

**Issue by JackCaster** [rstudio/renv#940]
Is it possible to restore the env based upon `DESCRIPTION` file? 

The use case is:
1. I create an R project and install the packages from the `DESCRIPTION` with `renv::install()`
1. Anytime I need a new package I write in the `DESCRIPTION` file and type `renv::install()` again. With the auto snapshot, this will also update the `renv.lock` file
1. I "mistakenly" install a package from the console with `renv::install('<package>')` (without including it in `DESCRIPTION`) and snapshot it. 

Now, `DESCRIPTION` and `renv.lock` have diverged, but any action on the environment will prioritize `renv.lock` while I would like to prioritize `DESCRIPTION`. 

Ideally, I would like `renv::install()` to remove all deps **not** in `DESCRIPTION`, so to keep `DESCRIPTION` and `renv.lock` aligned. Another solution is to allow `renv::restore()` to point to `DESCRIPTION`. Another note, I would suggest to make `renv::install()` a little more verbose with something like `renv::install(DESCRIPTION)`

**Comment by JackCaster** [comment]
I just saw that `renv::snapshot()` can be set to use the snapshot type ([link](https://rstudio.github.io/renv/reference/snapshot.html#snapshot-type)):
> "explicit"
> Only capture packages which are explicitly listed in the project DESCRIPTION file. This workflow is recommended for users who > wish to manage their project's R package dependencies directly.

I think this is something that could be beneficial for my usecase

**Comment by kevinushey** [comment]
For the underlying philosophy here:

- `renv::snapshot()` and `renv::restore()` are both tools for saving and loading the library state, respectively. In that respect, `renv::snapshot()` should always treat `renv.lock` as the source of truth, especially because the `DESCRIPTION` file may not have all of the information necessary to restore the exact requested version of the package in use. In particular, the `DESCRIPTION` file does not usually "lock" the versions of packages that are required; `renv.lock` does.

- `renv::install()` and friends are tools for installing packages, and is not coupled to `renv.lock` in any way. We have some tooling for installing packages as declared in the `DESCRIPTION` file with `renv::install()`.

In effect, I _think_ you just want `renv::install()` (to install packages as declared in the `DESCRIPTION` file) + `renv::clean()` (to remove old packages).

**Comment by JackCaster** [comment]
> For the underlying philosophy here:
> 
>     * `renv::snapshot()` and `renv::restore()` are both tools for saving and loading the library state, respectively. In that respect, `renv::snapshot()` should always treat `renv.lock` as the source of truth, especially because the `DESCRIPTION` file may not have all of the information necessary to restore the exact requested version of the package in use. In particular, the `DESCRIPTION` file does not usually "lock" the versions of packages that are required; `renv.lock` does.
> 
>     * `renv::install()` and friends are tools for installing packages, and is not coupled to `renv.lock` in any way. We have some tooling for installing packages as declared in the `DESCRIPTION` file with `renv::install()`.
> 
> 
> In effect, I _think_ you just want `renv::install()` (to install packages as declared in the `DESCRIPTION` file) + `renv::clean()` (to remove old packages).

I understand. Would it be possible to have something like `renv::install(clean=TRUE)`, or have it as a settings so that I can ensure my collaborators and I will have the same deterministic environment?

**Comment by kevinushey** [comment]
> I understand. Would it be possible to have something like renv::install(clean = TRUE), or have it as a settings so that I can ensure my collaborators and I will have the same deterministic environment?

That seems worth considering to me.

**Comment by hadley** [comment]
Please let us know if that doesn't handle your use case, and we'll reopen this issue.
