### ISSUE TITLE
Running .Rmd file on cluster with renv

### ISSUE THREAD

**Issue by lucygarner** [rstudio/renv#959]
Hi,

I have an renv environment that I am using within RStudio server, however I would like to be able to run my Rmarkdown script (with the same renv) using `Rscript -e` so that I can submit it as a job to the cluster.

I submitted the following command to a compute node:
```
Rscript -e "rmarkdown::render('Rscripts/normalisation_clustering_gex.Rmd', params = list(sample_name = 'sampleset2'), output_file = '../reports/sampleset2_gex.html')"
```

And got the following error:
```
# Bootstrapping renv 0.14.0 --------------------------------------------------
Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
  cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
* Downloading renv 0.14.0 ... FAILED
Error in bootstrap(version, libpath) : failed to download renv 0.14.0
Calls: source ... eval.parent -> eval -> eval -> eval -> eval -> bootstrap
```

I assume it is attempting to redownload all the packages? Is there a way that I can get around this?

Alternatively, if I run the script in a Conda environment instead, can I turn renv off temporarily? (so that I use renv when I'm working interactively only)

Best wishes,
Lucy

**Comment by lucygarner** [comment]
Yes, the internet is not accessible from the compute nodes. If I were to run `renv::restore()`, would this require the packages to be redownloaded? How would I run this if I am running the Rmarkdown file with `Rscript -e`?

**Comment by kevinushey** [comment]
Sorry, I see now you're using renv 0.14.0; you should consider updating to the latest release if possible.

For that release, you can use the variable `RENV_ACTIVATE_PROJECT = FALSE`; the name was later changed to be more consistent.

**Comment by kevinushey** [comment]
But yes, one way or another if you want to run your script remotely you'll need to ensure the packages your project requires are installed remotely as well. Normally, this would be done via `renv::restore()` but if your compute node doesn't have internet access then you would have to find another way to install the requisite packages on your compute nodes.

Without knowing more about your compute infrastructure it's hard to say what the easiest way to solve this problem is.

**Comment by lucygarner** [comment]
Hi @kevinushey,

I have updated renv now. As well as adding `RENV_AUTOLOADER_ENABLED = FALSE` to a project .Renviron, should I remove `source('renv/activate.R')` from the project .Rprofile or should I leave that so that I can use renv interactively?

I am still unclear why renv should not run on the compute nodes. The cluster that I am using has shared disk storage (https://www.medsci.ox.ac.uk/divisional-services/support-services-1/bmrc/cluster-usage), so renv and the packages I have installed with renv on one node should be available on the other nodes as well. 

Best wishes,
Lucy

**Comment by kevinushey** [comment]
> I have updated renv now. As well as adding RENV_AUTOLOADER_ENABLED = FALSE to a project .Renviron, should I remove source('renv/activate.R') from the project .Rprofile or should I leave that so that I can use renv interactively? If I want to use renv interactively, what do I need to run to load up the renv environment? renv::load()? It seems like this requires internet access which is causing me issues...

If you want to use `renv` interactively, it should suffice to call `renv::load()`. Presumedly, `renv::load()` is failing because the required version of `renv` isn't installed in the project library path, and so `renv` is trying and failing to bootstrap itself. Does that sound right?

> I am still unclear why renv should not run on the compute nodes. The cluster that I am using has shared disk storage (https://www.medsci.ox.ac.uk/divisional-services/support-services-1/bmrc/cluster-usage), so renv and the packages I have installed with renv on one node should be available on the other nodes as well.

How is your shared disk storage configured? That is, what directories are shared between nodes? It's possible that all you need to do is set something like (in your `.Renviron`):

```
RENV_PATHS_LIBRARY = /shared/storage/path/project/library
```

That way, `renv` will use an R package library located on shared storage, and packages installed there will "automatically" be available and visible to other compute nodes. This assumes that your host + compute nodes are using the same operating system and so on; if not, you would need to rebuild and reinstall packages as appropriate for the different compute node architectures.

In this setting, I think you would install packages from your "host" node into that shared storage space, and then compute nodes would see those packages available automatically. This project would still be isolated from other projects by virtue of using renv + a custom library path. Does that make sense?

**Comment by hadley** [comment]
@lucygarner are you still interested in following up on this issue?

**Comment by lucygarner** [comment]
Hi @hadley, 

Yes it would be great if there was a way to achieve this.

Best wishes,
Lucy

**Comment by hadley** [comment]
@lucygarner in that case, do you want to respond to the last round of questions from Kevin?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested information. If you still care about this bug, please open a new issue with needed details.

**Comment by lucygarner** [comment]
Thank you. I will need to request further information from our system administrators, as the storage system has been updated recently.
