### ISSUE TITLE
Can't install packages with renv on docker container (rocker/verse:3.6.3): permission denied on staged install

### ISSUE THREAD

**Issue by bautheac** [rstudio/renv#980]
I'm running a docker container from shell using the `rocker/verse:3.6.3` image:
```
docker run --rm \
  -e DISABLE_AUTH=true -e ROOT=true \
  -v "$(pwd):/home/rstudio/project:rw" \
  -p 8787:8787 \
  --name rstudio rocker/verse:3.6.3
```
`install.packages('renv')` works fine. `renv::init()` fails however; returns "permission denied" error when trying to move files from staging to library directory while installing missing dependencies. Same error shows when trying to install any package with either `install.packages` or `renv::install`. I tried to disable staged installation using `options(renv.config.install.transactional = FALSE)`, also tried via environment variables--`Sys.setenv(RENV_CONFIG_INSTALL_TRANSACTIONAL = FALSE)`--with no luck; both `install.packages()` and `renv::install()` seem to stick to staged installation. Am I missing something?

**Comment by kevinushey** [comment]
Can you please provide the full error message you're seeing?

**Comment by ATpoint** [comment]
That is probably because the user is `rstudio` while you must be user `root` to make changes such as creating files. I used to tackle this by creating a folder like `renv_dir` directly into the `/` of the container and then `chown` it to be owned by user `rstudio`, both done via the Dockerfile.

```
FROM your/image:tag
RUN mkdir /renv_dir/ && chown -c rstudio /renv_dir/
RUN R -e "install.packages('renv')"
```

...and then create your renv project into that folder `renv_dir/`.
